### ISSUE TITLE
Potential error with push notifications?

### ISSUE THREAD

**Issue by samemory** [samemory/homebridge-eufy-security#10]
I am seeing this error in my homebridge log: 
`{"name":"eufyLog","hostname":"homebridge","pid":29432,"level":50,"msg":"Error: Error: EACCES: permission denied, open '/usr/local/lib/node_modules/@samemory/homebridge-eufy-security-control/node_modules/eufy-security-client/persistent.json'\n    at Object.openSync (fs.js:476:3)\n    at Object.writeFileSync (fs.js:1467:35)\n    at EufySecurity.writePersistentData (/usr/local/lib/node_modules/@samemory/homebridge-eufy-security-control/node_modules/eufy-security-client/src/eufysecurity.ts:620:17)\n    at EufySecurity.savePushCredentials (/usr/local/lib/node_modules/@samemory/homebridge-eufy-security-control/node_modules/eufy-security-client/src/eufysecurity.ts:647:14)\n    at PushNotificationService.<anonymous> (/usr/local/lib/node_modules/@samemory/homebridge-eufy-security-control/node_modules/eufy-security-client/src/eufysecurity.ts:170:18)\n    at PushNotificationService.emit (events.js:315:20)\n    at PushNotificationService._open (/usr/local/lib/node_modules/@samemory/homebridge-eufy-security-control/node_modules/eufy-security-client/src/push/service.ts:504:18)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at PushNotificationService.open (/usr/local/lib/node_modules/@samemory/homebridge-eufy-security-control/node_modules/eufy-security-client/src/push/service.ts:544:9) {\n  errno: -13,\n  syscall: 'open',\n  code: 'EACCES',\n  path: '/usr/local/lib/node_modules/@samemory/homebridge-eufy-security-control/node_modules/eufy-security-client/persistent.json'\n}","time":"2021-06-07T14:13:14.058Z","v":0}`

**Comment by schliemann** [comment]
I believe the error is thrown because eufy security client tries to persist data and is denied. I'll try and set The persistentPath of eufy config tonight.

**Comment by schliemann** [comment]
When the persistPath on eufyConfig is set the error goes away. Just not sure if the right thing is to use this.api.user.storagePath(). Will test some more tonight.

**Comment by schliemann** [comment]
Birkirs repo also uses this.api.user.storagePath().

https://github.com/birkir/homebridge-plugin-eufy-security/blob/b8a54c0c898e5c745fd6f01dca84abf274b2b155/src/platform.ts#L86

**Comment by lenoxys** [comment]
I think we can use it, I've put your code on my test lab and no issue since 3 days.
