### ISSUE TITLE
Ability to turn cameras on/off and motion

### ISSUE THREAD

**Issue by xraywinedrinker** [samemory/homebridge-eufy-security#100]
**Is your feature request related to a problem? Please describe:**
Additional camera controls

**Describe the solution you'd like:**

Add the ability to turn on/off eufy 2C and indoor 2k cameras, and motion on/off on indoor 2k cameras.

Right now the Eufy 2C cameras have the motion on/off control but the indoor 2k cameras only register as a motion device without the ability to activate motion. Same with on/off switch. This feature was active in earlier versions but seems to have to been removed.

**Comment by schliemann** [comment]
Did these controls work on the indoor 2k cameras actually work? Because a lot of report were created about error logs that motionDetection and  IsEnabled wasn't supported.

Might be a problem with the client library. I don't have an indoor 2k camera, so I can't test it.

**Comment by xraywinedrinker** [comment]
I was able to turn the indoor 2k cameras on/off on prior versions. Since there is no security settings for the indoor 2k cam, I use the on/off feature to disable my alarm mode.

**Comment by xraywinedrinker** [comment]
this appears to be fixed in the 0.3.14 beta.
