### ISSUE TITLE
Local IP Address (Homebase)???

### ISSUE THREAD

**Issue by ollieslats** [samemory/homebridge-eufy-security#105]
What IP is this asking for in the CONFIG? Door-bell, hoobs??

Thanks for the help, I think my main issues is Im old:)

**Comment by schliemann** [comment]
It is for the Homebase. But I don't think we use it.

**Comment by schliemann** [comment]
We should remove the ip address from the config.

**Comment by lenoxys** [comment]
PR #110

**Comment by lenoxys** [comment]
Lan IP address can be catch later. Better if we use the function instead of relying on this static settings which could be pretty hard to guess.
