### ISSUE TITLE
Camera responsiveness 

### ISSUE THREAD

**Issue by Soneji** [samemory/homebridge-eufy-security#106]
Hi

currently I have a ring camera and use the ring homebridge plugin, it’s not that great as it can often take anywhere between 10 and 60+ seconds to initialise and connect to the camera feed. I was wondering if this is also the case for the eufy cameras as I was considering getting one

Thanks so much

**Comment by schliemann** [comment]
It takes about 10 seconds to load my doorbell rtsp video in homekit. It might be possible to improve the video by using the stream directly from the Homebase. But it is a work in progress and not currently available in the plugin.

**Comment by lenoxys** [comment]
Same than @schliemann it's highly depending of your ISP bandwidth and latency.

**Comment by Soneji** [comment]
This is interesting to hear from you guys, I will take this up with the ring homekit team too, as it seems that the ring app loads the rstp feed quicker than the home app. I have pretty fast internet so I don't think that's the issue. 

What do you mean when you say "Homebase" @schliemann ? 

Thanks so much for your help :)

**Comment by lenoxys** [comment]
hub/station. In fact we got the stream from the cloud. We still struggling to get the stream from the hub itself which could save seconds.

Actually here what append : 

Camera/Doorbell => Hub => Eufy Cloud => Homebridge with Eufy plugin => Apple Device

**Comment by Soneji** [comment]
Ah fab that's really cool! Thanks once again. Will let you know how I find the Eufy cameras I bought 😉 
(Feel free to close this if you don't need it for anything else)

**Comment by lenoxys** [comment]
Thanks for your feedback. in case of issue please open a new one.
