### ISSUE TITLE
eufyLog: No devices found.

### ISSUE THREAD

**Issue by semmtex** [samemory/homebridge-eufy-security#108]
**Describe The Bug:**
No devices are found. Using a guest account for Eufy which only has access to the Doorbell.

**To Reproduce:**
Installed in a Docker, through HomeBridge with GUI. If I try the birkir plugin, the Doorbell shows up in Home, however that one doesn't seem to work when enabling Push notifications.

**Expected behavior:**
A Doorbell that shows up in the Home app.

**Logs:**
Starting to advertise 'Homebridge 0BDF' using bonjour-hap backend!
[8/1/2021, 2:01:52 PM] Homebridge v1.3.4 (Homebridge) is running on port 51826.
{"name":"eufyLog","hostname":"redacted","pid":350,"level":30,"msg":"No stations found.","time":"2021-08-01T12:01:52.949Z","v":0}
{"name":"eufyLog","hostname":"redacted","pid":350,"level":30,"msg":"No devices found.","time":"2021-08-01T12:01:53.300Z","v":0}
{"name":"eufyLog","hostname":"redacted","pid":350,"level":30,"msg":"No stations found.","time":"2021-08-01T12:01:53.345Z","v":0}
[0;37m[8/1/2021, 2:01:53 PM] [0m[0;36m[Homebridge UI][0m [0;33mHomebridge Config UI X v4.41.2 is listening on 0.0.0.0 port 8124[0m
{"name":"eufyLog","hostname":"redacted","pid":350,"level":30,"msg":"No devices found.","time":"2021-08-01T12:01:53.727Z","v":0}
{"name":"eufyLog","hostname":"redacted","pid":350,"level":30,"msg":"Push notification connection successfully established","time":"2021-08-01T12:02:04.399Z","v":0}
{"name":"eufyLog","hostname":"redacted","pid":350,"level":30,"msg":"Push notification connection successfully established","time":"2021-08-01T12:02:04.399Z","v":0}

**Plugin Config:**
{
            "username": "redacted@hotmail.com",
            "password": "redacted",
            "enableDetailedLogging": true,
            "enableCamera": true,
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 0,
            "hkOff": 63,
            "hkDisarmed": 6,
            "platform": "EufySecurity"
        }

**Screenshots:**
Not applicable.

**Environment:**

* **Plugin Version**: v0.2.13
* **Homebridge Version**:  v1.3.4
* **Node.js Version**: v0.9.4
* **NPM Version**: Unkown
* **Operating System**: Docker

**Comment by schliemann** [comment]
Have you given access to the devices to the guest account?

**Comment by semmtex** [comment]
> @semmtex Have you given access to the devices to the guest account?

Yes, I have. That's why I tried the Birkir plugin, with which the doorbell did show up in de Home app.

**Comment by schliemann** [comment]
It is most likely an error you should report to bropat in this repos https://github.com/bropat/eufy-security-client

**Comment by semmtex** [comment]
Thanks @schliemann. I will post it there as well. Thanks for the quick replies.

**Comment by lenoxys** [comment]
After digging, found an issue. Let me know if the last dev version works (0.3.21)

https://github.com/samemory/homebridge-eufy-security/wiki/How-to-switch-on-dev-branch

**Comment by jblaster** [comment]
> After digging, found an issue. Let me know if the last dev version works (0.3.21)
> 
> https://github.com/samemory/homebridge-eufy-security/wiki/How-to-switch-on-dev-branch

I had the same problem, with version 0.3.21 all my devices are recognized.

**Comment by lenoxys** [comment]
So now device are recognized ?

**Comment by jblaster** [comment]
> So now device are recognized ?

Exactly. But I can’t havé access to live stream. I’ve installed Ffmpeg

**Comment by lenoxys** [comment]
> > So now device are recognized ?
> 
> 
> 
> Exactly. But I can’t havé access to live stream. I’ve installed Ffmpeg 

I've tested on a fresh install with node 14 and I don't need to install ffmpeg my self only eufy plugin installation is enough

**Comment by jblaster** [comment]
> > > So now device are recognized ?
> > 
> > 
> > Exactly. But I can’t havé access to live stream. I’ve installed Ffmpeg
> 
> I've tested on a fresh install with node 14 and I don't need to install ffmpeg my self only eufy plugin installation is enough

I'm on node 14 but can't have live stream, the log :

**Comment by lenoxys** [comment]
Con you enable debug within the config ?

**Comment by jblaster** [comment]
> Can you enable debug within the config and post the output here ?

Sorry for the late reply, I was not home. When I returned to Homebridge, there was a plugin update v1.0.0 and there the live works!

**Comment by semmtex** [comment]
I tried the new version as well, too bad for me, it's still showing 0 devices found. :( 

Starting to advertise 'Homebridge 0BDF' using bonjour-hap backend!
[8/18/2021, 2:01:19 PM] Homebridge v1.3.4 (Homebridge) is running on port 51826.
[[37m2021-08-18T12:01:20.266Z[39m] [90mDEBUG[39m: ef/349 on v1.0.0-rc.0: [36mFound 0 stations.[39m
[[37m2021-08-18T12:01:20.266Z[39m] [90mDEBUG[39m: ef/349 on v1.0.0-rc.0: [36mFound 0 devices.[39m
[[37m2021-08-18T12:01:20.318Z[39m] [35m WARN[39m: ef/349 on v1.0.0-rc.0: [36mPush Closed![39m
[0;37m[8/18/2021, 2:01:20 PM] [0m[0;36m[Homebridge UI][0m [0;33mHomebridge Config UI X v4.41.2 is listening on 0.0.0.0 port 8124[0m
[[37m2021-08-18T12:01:21.130Z[39m] [90mDEBUG[39m: ef/349 on v1.0.0-rc.0: [36mPush Connected![39m
[[37m2021-08-18T12:01:26.260Z[39m] [90mDEBUG[39m: ef/349 on v1.0.0-rc.0: [36mPush Connected![39m
[[37m2021-08-18T12:01:26.260Z[39m] [90mDEBUG[39m: ef/349 on v1.0.0-rc.0: [36mPush Connected![39m

**Comment by lenoxys** [comment]
> > Can you enable debug within the config and post the output here ?
> 
> Sorry for the late reply, I was not home. When I returned to Homebridge, there was a plugin update v1.0.0 and there the live works! Thanks for your help!

thanks for your feedback, I'm closing this issue !

@semmtex I've opened a new one for yours.
