### ISSUE TITLE
Not updating changes

### ISSUE THREAD

**Issue by Jurgem** [samemory/homebridge-eufy-security#13]
The status of entry sensor is not updating, when I open (or close) a door it stay in the same status (opened or closed). It only change when I reboot home bridge

Awesome plugin!

**Comment by samemory** [comment]
Right now I believe it's only updating status when it refreshes the data according to the polling interval. The default is 10 mins but in the config you can change it. Haven't tested a different polling interval though personally. 
Hope to find a better solution for this, it's kind of annoying.

**Comment by lenoxys** [comment]
In fact, we do report the the open/close but relying on the polling interval which is 10min by default or push notification. For this last if you select a security profile (home, away, cust), you have to enable to mouvement reaction and push notification. If you do so, the status is updated right away (but you will receive notification on your phone as well each time the status change if you have the application installed ).

**Comment by Jurgem** [comment]
i see, when I activate the push notification in Eufy security, it update instantly. Ok, so when im in home I don't want to eufy send me notifications, so I think that the minimum is to put the polling interval  = 1?

**Comment by lenoxys** [comment]
Hello,

You right ! It's done because HomeKit will triggered the event of getting or if we receive a push notification.

I think we shouldn't rely on polling the value, I can see I can get ban for a day because I generated too much requests.

Regards,
Aurelien

**Comment by schliemann** [comment]
How many requests did you send 🤔😅

**Comment by lenoxys** [comment]
A lot, but since the push notification it's more easy to debug without doing too much request. I've to setup a dedicated account link to the first one to avoid blocking everything.

**Comment by schliemann** [comment]
I just tested this and can verify that the push notifications for entry sensor works.

**Comment by schliemann** [comment]
I think refreshData could be used to discover newly added devices to the hub. But it is a "nice to have" feature. And probably not worth implementing :)

**Comment by lenoxys** [comment]
Yeah but the Eufy app is really noisy when enabling push while at home. Does p2p would work without the need of enabling push ?

**Comment by samemory** [comment]
It does look like there's another way to get updates using p2p based on eufy-security-client code. Looks like there are some emitters that could be used but just haven't had time to dig into it yet. I could be completely wrong. Maybe the examples in this library would be helpful: https://github.com/bropat/eufy-security-ws
