### ISSUE TITLE
Doorbell Bidirectionnal audio

### ISSUE THREAD

**Issue by lenoxys** [samemory/homebridge-eufy-security#130]
What I can see in the debug logs, we're not seeing any more exceptions:

`{"name":"eufyLog","hostname":"xxxxxxx","pid":25517,"level":20,"msg":"Front Door Triggered SET HomeKitCameraActive: 1","time":"2021-08-03T13:35:03.172Z","v":0}
{"name":"eufyLog","hostname":"xxxxxxx","pid":25517,"level":20,"msg":"Front Door Triggered SET EventSnapshotsActive: 1","time":"2021-08-03T13:35:03.172Z","v":0}
{"name":"eufyLog","hostname":"xxxxxxx","pid":25517,"level":20,"msg":"Front Door Triggered GET MotionDetected","time":"2021-08-03T13:35:21.368Z","v":0}
{"name":"eufyLog","hostname":"xxxxxxx","pid":25517,"level":20,"msg":"Front Door Triggered GET BatteryLevel","time":"2021-08-03T13:35:21.368Z","v":0}`

`{"name":"eufyLog","hostname":"xxxxxxx","pid":25517,"level":20,"msg":"Front Door Handle Camera Motion:  --  false","time":"2021-08-03T13:38:09.612Z","v":0}
{"name":"eufyLog","hostname":"xxxxxxx","pid":25517,"level":20,"msg":"Front Door Handle Current battery level:  --  91","time":"2021-08-03T13:38:09.612Z","v":0}`

Camera seems to be working ok. Set to "Seen as sensor" in plugin settings.

Doorbell functions may be a outside scope of this issue but 2 observations from this build:

1. Chime does not play via HomePod (not sure if this is a plugin issue)
2. I'm aware of the HW limitations around audio (half-duplex etc.), but but is there any possibility of getting an audio stream back to the doorbell from HomeKit? Even on a snapshot vs a live video feed?

Thanks.

_Originally posted by @jakobyte in https://github.com/samemory/homebridge-eufy-security/issues/75#issuecomment-891882188_

**Comment by lenoxys** [comment]
We don't deactivate the chime. On my setup, 3 chimes (one from the DoorBell, One from my previous Chime and one from the app as notification.

For bidirectionnal, for now, it's a lot of work to achieve this milestone.

**Comment by jakobyte** [comment]
On the HomePod Chime, I’m referring to the setting in the screenshot. Is the chime notification passed back into HomeKit to activate this?
![F7BD3633-9F3E-4AB9-878E-18B27F6BE9D0](https://user-images.githubusercontent.com/4356634/128084670-00f064ef-9794-4693-92cd-519ac673e5e8.jpeg)

**Comment by lenoxys** [comment]
I think it should be trigger like an apple device ring when get the notification. I couldn't check this I don't have homepod at home but I got notification on apple TV should be the same.

**Comment by schliemann** [comment]
Homepod works as a chime in my setup.

**Comment by jakobyte** [comment]
Looks like I have another problem to debug at home then 😁. Thanks All.

**Comment by lenoxys** [comment]
> @lenoxys Homepod works as a chime in my setup.

does this works ?

**Comment by schliemann** [comment]
@lenoxys Yes.

**Comment by lenoxys** [comment]
Cool so where is a catch ?

**Comment by schliemann** [comment]
No catch afaik.

**Comment by jakobyte** [comment]
Agreed. No catch on HomePod Chime. That part seems to be working. I think my issues are external to the plugin so I will have to do more testing, but I don't think there is anything else to do with the plugin . I think this enhancement can be refocussed on the bi-directional audio. Thanks.

**Comment by jakobyte** [comment]
Hi @lenoxys . Is this still on the roadmap, or do you think it won't be feasible?

**Comment by lenoxys** [comment]
this need to be implemented on Bropat lib.
