### ISSUE TITLE
Any plan to support "Eufy Smart Lock touch & Wifi"?

### ISSUE THREAD

**Issue by lenoxys** [samemory/homebridge-eufy-security#135]
### Discussed in https://github.com/samemory/homebridge-eufy-security/discussions/132

<div type='discussions-op-text'>

<sup>Originally posted by **CapnPicard** August  4, 2021</sup>
As title says, any plan to support it? At least just a "lock/unlock" button so we can make automation. It's the latest model with builtin wifi so it's always connected to the network.

thanks</div>

**Comment by lenoxys** [comment]
I don't have such device on my setup. Not such a big fan to ask for sharing since I could open your door not really safe.

I will try to implement something

**Comment by lenoxys** [comment]
hello, can you test on dev ? https://github.com/samemory/homebridge-eufy-security/wiki/How-to-switch-on-dev-branch

I've implemented on the 0.3.10

The lib doesn't provide the ability to interact with the lock so for now it's only getting the lock/unlock status

**Comment by CapnPicard** [comment]
> 
> 
> hello, can you test on dev ? https://github.com/samemory/homebridge-eufy-security/wiki/How-to-switch-on-dev-branch
> 
> I've implemented on the 0.3.10
> 
> The lib doesn't provide the ability to interact with the lock so for now it's only getting the lock/unlock status

I just tried it. I now have the tile for the lock but it always show as locked. I even tried to restart homebridge to see if it would update at launch but no, it doesn't update.

**Comment by lenoxys** [comment]
can you enable detailed looging on the plugin config and send me the log ?

**Comment by lenoxys** [comment]
make sure you enable push notification on the alarm mode for your lock

**Comment by CapnPicard** [comment]
For the log, do you want "debug" or "insane" ?
For the alarm mode, the lock isn't related to any mode. It's really a standalone product but I enabled notifications in the eufy app on the lock settings


 
 

    On Wednesday, August 4, 2021, 9:12:33 a.m. EDT, Aurélien ***@***.***> wrote:  
 
 


make sure you enable push notification on the alarm mode for your lock

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CapnPicard** [comment]
[eufy.txt](https://github.com/samemory/homebridge-eufy-security/files/6931593/eufy.txt)

Here's the lock when I start homebridge and I then did some lock/unlock in the app

**Comment by lenoxys** [comment]
when you lock/unlock did anything happend on log ?

**Comment by CapnPicard** [comment]
unfortunately, no.

**Comment by lenoxys** [comment]
can you join this chat : https://gitter.im/homebridge-eufy-security/135

**Comment by schliemann** [comment]
> can you enable detailed looging on the plugin config and send me the log ?
> 
> level debug would be enough

How do you enable different log levels?

**Comment by lenoxys** [comment]
I've put 0,1,2 0 normal, 1 debug and 2 insane

Here is the part which do the job https://github.com/samemory/homebridge-eufy-security/blob/dev/src/platform.ts#L85

**Comment by lenoxys** [comment]
In the hand of Bropat
https://github.com/bropat/eufy-security-client/pull/36

**Comment by shadydude047** [comment]
Just wanted to double check if only T8500 will be supported? I have T8520 and when switched to dev branch, it complains that
`
[EufySecurity] This accessory is not compatible with this plugin: Front Door Type: 51
`

**Comment by Dentifreak** [comment]
I did some tests and it seems the plugins works! But problem is it takes at least 10-15 min to update but always end up updated.

So it would need to make it instantaneous to fix it

**Comment by Dentifreak** [comment]
> Just wanted to double check if only T8500 will be supported? I have T8520 and when switched to dev branch, it complains that
> `[EufySecurity] This accessory is not compatible with this plugin: Front Door Type: 51`

I have the same. You need the get the last dev version, not stable. But note it’s note currently working perfectly.

**Comment by lenoxys** [comment]
Yeah that's why I've pushed a PR for bropat to bring the push notification and get instant notification while lock/unlock happend.

**Comment by Dentifreak** [comment]
> Yeah that's why I've pushed a PR for bropat to bring the push notification and get instant notification while lock/unlock happend.


Do you think In the future we’ll be able to not only see the status but be able to lock/unlock from homekit?

**Comment by lenoxys** [comment]
It's depending if the bropat lib I don't have a lock and bropat as well to do investigation and test to help him

**Comment by CapnPicard** [comment]
> It's depending on the bropat lib I don't have a lock and bropat as well to do investigation and test to help him

I’m still available for tests if you need me for this.

**Comment by bropat** [comment]
Lock/unlock currently works for T8500 (50) and should work for T8510 (52; untested). It is not yet implemented (in progress) for T8501 (53) and T8520 (51). For T8520 you can also read the progress here: 

https://github.com/bropat/ioBroker.eufy-security/issues/138

If I can get T8520 to work, then T8501 should also work. 
I have already written a few lines of source code: 

https://github.com/bropat/eufy-security-client/blob/7d8689dd03b21ed3bf9a8e1fa534eb2ea014d70d/src/http/station.ts#L2682-L2708

But the most important thing is missing, the key:

https://github.com/bropat/eufy-security-client/blob/7d8689dd03b21ed3bf9a8e1fa534eb2ea014d70d/src/http/station.ts#L2700

If someone has skills in decoding C/C++ code just let me know ;)

**Comment by CapnPicard** [comment]
I have no coding skill but THANK YOU guys, you are incredible! If you need testers, I'm here.

**Comment by lenoxys** [comment]
@CapnPicard can you test on the latest beta version?

**Comment by CapnPicard** [comment]
Sorry for the delay.

I tried 0.3.25 and .27.  One thing I noticed, they add 2 doorlocks in homekit. One always shows locked and the other unlocked. Both don't update.

I also see this in the logs:

**Comment by lenoxys** [comment]
do you mind sharing the lock ?

**Comment by CapnPicard** [comment]
> 
> 
> do you mind sharing the lock ?

send me a private chat like the last time and you can do it

**Comment by lenoxys** [comment]
https://gitter.im/homebridge-eufy-security/135

**Comment by lenoxys** [comment]
I may switch on discord next time. When we get verified by homebridge team it's possible to request a channel for the plugin on their community.

**Comment by Taik** [comment]
@lenoxys I also have this same lock and am happy to provide access and help where I can.

**Comment by bropat** [comment]
Good news: I was able to decrypt the communication. I can now close and open the lock.
I still have to decipher and implement a few small things so that everything runs smoothly, but the hardest part is now behind me.
In the next few days I will publish the new version with support for the device.

**Comment by rriewerts** [comment]
Request if this was ever finalized?  I have the T8520 and am still unable to operate the lock?

**Comment by kunwarsethi** [comment]
Looks like Bropat just updated it to work for the T8520 today, so we just have to wait for this plugin to be updated to the latest bropat lib!
