### ISSUE TITLE
Night Arming Mode 

### ISSUE THREAD

**Issue by saltysmith1** [samemory/homebridge-eufy-security#146]
**Describe Your Problem:**
When selecting Custom 1/2/3 under HomeKit Night in configuration, this doesn't seam to change on the Eufy App when Arming the system via Home App, but Home, Away does work, is this something ive done wrong or is there an error somewhere.

I have included a screenshot from the Eufy app to show the Arming changes, (Yes before someone mentions) I have set up 3 different custom modes on the Eufy app, I haven't called them Custom 1/2/3 tho 

**Environment:**

* **Plugin Version**: 0.2.13
* **Homebridge Version**: HOOBS 4
* **Node.js Version**: 14.17.4
* **NPM Version**: 0.12.13
* **Operating System**: Raspberry Pi

**Comment by saltysmith1** [comment]
![Screenshot 2021-08-07 at 14 51 24](https://user-images.githubusercontent.com/87123578/128603033-114d2967-6c12-498d-92e7-98534b5c3aaf.png)

**Comment by saltysmith1** [comment]
I know you don't support HOOBS but i have just installed the plugin on Homebridge and the arming change works, im guessing its some issue with HOOBS. ill leave it open for now but if you want to close it :-)

**Comment by lenoxys** [comment]
Yeah, wasn't able to reproduce. More clear. I will close this ticket since it's related to HOOBS issue.
