### ISSUE TITLE
Dumb Question Adding new Device 

### ISSUE THREAD

**Issue by saltysmith1** [samemory/homebridge-eufy-security#160]
Sorry for the Dumb question, ive just brought a new Eufy Motion Sensor, added in the Eufy App as normal, but how do i get it to show up in the Home App, Do i need to remove and add the bridge again ( ive tried restarting the bridge in HomeKit No luck)

Ive checked in the Home App under bridges and can see all my Eufy devices except this new one am i being stupid can someone point me in the right direction 

Cheers 

Chris

**Comment by schliemann** [comment]
@saltysmith1 Should work if you restart homebridge.

**Comment by saltysmith1** [comment]
> @saltysmith1 Should work if you restart homebridge.

sorry  it was me being dumb i forgot to share the new device with my second account sorry will close this my bad sorry
