### ISSUE TITLE
Local LiveStream

### ISSUE THREAD

**Issue by lenoxys** [samemory/homebridge-eufy-security#173]
Provide ability to fetch the stream from the station instead of the cloud.

ATM :

Camera > Station > EufyCloud > Homebridge > Apple Device

Plan : 

Camera > Station > Homebridge > Apple Device

**Comment by lenoxys** [comment]
@schliemann, hey there ! I know you did a lot of work on getting the livestream. Did you work as well on the local one ?

**Comment by schliemann** [comment]
@lenoxys it was actually @samemory who fixed the remote stream. The local stream got stuck ok night vision not working. 

https://github.com/schliemann/homebridge-eufy-security-control/blob/F-Realtime_Snapshot/src/streamingDelegate.ts#L199-L378

**Comment by schliemann** [comment]
@lenoxys Would it make sense to merge beta into master? I think most users would want to use local livestream anyway?

**Comment by lenoxys** [comment]
Yeah almost done as before merging into master I'm working to allow people customise ffmpeg per camera before.
