### ISSUE TITLE
FFmpeg issue

### ISSUE THREAD

**Issue by embryocargo** [samemory/homebridge-eufy-security#179]
Hello,
First, thank you for your hard work and ingenuity. _||_
I installed plugin in Homebrew running on macOS 10.13.6 to be visible in Homekit. However the camera window is there, it gives no image feed. I installed homebridge-camera-ffmpeg v3.1.2 but it didn't help, even with reconnected unbridged camera. Help!

**Logs:**

[8/17/2021, 4:03:04 PM] [Homebridge UI] [HapClient] [192.168.1.198:51044 (0E:9D:23:C8:2F:A8)] Got Event: [{"aid":8,"iid":22,"value":"AQEB"}]
[8/17/2021, 4:03:04 PM] [EufySecurity] dyld: Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
[8/17/2021, 4:03:04 PM] [EufySecurity]   Referenced from: /usr/local/bin/ffmpeg
[8/17/2021, 4:03:04 PM] [EufySecurity]   Reason: Incompatible library version: ffmpeg requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0
[8/17/2021, 4:03:04 PM] [EufySecurity] FFmpeg exited with code: null and signal: SIGABRT (Unexpected) Doorbell

**Plugin Config:**

        {
            "platform": "EufySecurity",
            "username": "xxx@xxx.com",
            "password": "xxx",
            "ignoreStations": "",
            "ignoreDevices": "",
            "enableCamera": true,
            "pollingIntervalMinutes": 30,
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 63,
            "enableDetailedLogging": 0
        },

**Environment:**

* **Plugin Version**: v1.0.0-rc.0
* **Homebridge Version**: v1.3.4
* **Node.js Version**: v14.17.3
* **NPM Version**: v6.14.13
* **Operating System**: macOS High Sierra

**Comment by lenoxys** [comment]
Hello,

`homebridge-camera-ffmpeg` is another plugin and not used by our plugin. It won't solved your issue.

You should install following this installation method described here : 
https://github.com/samemory/homebridge-eufy-security/wiki/Installation

For Mac OS x, you will need to install XCODE but normally when the installation occurs it will prompt you to install it. If it occur, please uninstall the plugin then reinstall it.

Finally, you will need to install `brew` then `brew install ffmpeg`. Then restart homebridge. That should solve the issue.

If nothing is solved after that I'm sad to say we (and Apple) doesn't support High Sierra. We recommend to upgrade to the latest available Mac OS X.
