### ISSUE TITLE
HOOBS Issue

### ISSUE THREAD

**Issue by mcarroll779** [samemory/homebridge-eufy-security#183]
**Describe Your Problem:**l

Is there any support for HOOBS? I’ve installed it and I’m getting this in the log when I start running the plug-in

Eufy SecurityWARNINGunhandled rejection: TypeError: Cannot read property 'indexOf' of undefined

**Environment:**

* **Plugin Version**: 1.0 rc
* **Homebridge Version**:  1.3.4 as HOOBS v4.0.100
* **Operating System**: Raspbian

**Comment by lenoxys** [comment]
I've asked HOOBS team to update their repo because it was pointing to really old version. Now it's fixed. I've to dig on why it's not working.

**Comment by lenoxys** [comment]
Managed to make it work on HOOBS (4.0.100). But it doesn't take care of the new UI so you can't use an Eufy account with OTP configured.

If you go to advanced config use the one below with your credentials. 

    {
        "platforms": [
            {
                "platform": "EufySecurity",
                "username": "******@*******.****",
                "password": "*******************",
                "enableDetailedLogging": 0,
                "enableCamera": false,
                "pollingIntervalMinutes": 5,
                "ignoreStations": "[]",
                "ignoreDevices": "[]"
            }
        ]
    }
