### ISSUE TITLE
Wrong username or password

### ISSUE THREAD

**Issue by anotherMetha** [samemory/homebridge-eufy-security#186]
I've installed the latest version of the plug-in but when the UI has me log in I get "wrong username or password". I know I put in the correct credentials but keep getting the error.

In the logs I get: [EufySecurity] Not connected can't continue!

My JSON Config is:
{
    "platform": "EufySecurity",
    "username": "********@******.com",
    "password": "*********",
    "enableCamera": false,
    "pollingIntervalMinutes": 30,
    "hkHome": 1,
    "hkAway": 0,
    "hkNight": 3,
    "hkOff": 63,
    "enableDetailedLogging": 0,
    "ignoreStations": "",
    "ignoreDevices": ""
}

**Environment:**

* **Plugin Version 1.0.0-rc.2
* **Homebridge Version 1.3.4
* **Node.js Version 14.17.5
* **NPM Version**: 6.14.14
* **Operating System macOS

**Comment by anotherMetha** [comment]
Not sure what happened but by using a different email address I was able to fix the problem.

**Comment by lenoxys** [comment]
We do recommend to use a specific account for HB. Glad to hear that your issue is solved!
