### ISSUE TITLE
Just an update / I've reverted back to 0.3.34

### ISSUE THREAD

**Issue by lenoxys** [samemory/homebridge-eufy-security#187]
Just an update / I've reverted back to 0.3.34

For me this is the most stable version to get a live feed from my battery 2k cam.

Just my 2 penny's worth

_Originally posted by @steverae68 in https://github.com/samemory/homebridge-eufy-security/issues/176#issuecomment-903090141_

**Comment by lenoxys** [comment]
It's surprising because besides the lib version modification all the other changes concern the new GUI.

https://github.com/samemory/homebridge-eufy-security/compare/v0.3.34...1.0.0-rc.2

**Comment by steverae68** [comment]
Yeah, for some unknown reason, 0.3.34 is the most reliable version for live streams for me, obviously I get the few seconds of white page and eufy logo but the logo keeps rolling and the live stream starts after around 10 seconds - on other, newer versions, the eufy logo stops scrolling and the live stream often fails to appear.

Again just my honest opinion, as always, happy to alow you to test with my doorbell if needed.  If you need logs, can provide those too.

**Comment by lenoxys** [comment]
since the RC is provided by default when you login into HB, I'm expecting more people testing the RC having more feedback

**Comment by steverae68** [comment]
Happy to test next release as always 👍

Top work from everyone involved

**Comment by steverae68** [comment]
Running now latest rc13 release - even better than 3.34 beta - happy to close this issue

**Comment by lenoxys** [comment]
Thanks for your feedback
