### ISSUE TITLE
Video Doorbell Phantom Rings and HomeBase2 False Alarm Triggering[Bug]: 

### ISSUE THREAD

**Issue by AppleNips** [samemory/homebridge-eufy-security#189]
### What happened?

Since updating to v1.0.0-rc.2 my HomeBase2 displays the "alarm triggered" status in homekit when the system is set to Eufy's "Off" mode rather than "Disarmed." And today I started getting phantom rings on the doorbell. I still haven't fixed this issue. The doorbell will ring every 30 minutes or so. The doorbell may just be a hardware issue with the chime, but I wanted to bring it up for your SA.

Thank you for all of the work you've done on this plug-in!

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Raspbian

**Comment by lenoxys** [comment]
Hello,

Are you sure using v1 ?

About the off/disarmed :
Can you go back to the plugin settings and choose disarmed instead of off ? We disabled the off settings. 
Know issue will fix in 1.1.0 #147

For the phantom ring. Can you enable debug and send us the log output ?
