### ISSUE TITLE
EufySecurity    ERROR        Not connected can't continue!

### ISSUE THREAD

**Issue by Gaby690** [samemory/homebridge-eufy-security#190]
### What happened?

What can I do to fix it?

EufySecurity     Finished initializing Eufy Security Platform
EufySecurity     ERROR        Not connected can't continue!

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Raspbian

### Relevant log output

```shell
8/21/2021, 5:39:03 PM Home EufySecurity Finished initializing Eufy Security Platform
8/21/2021, 5:39:05 PM Home EufySecurity ERROR Not connected can't continue!
```

**Comment by lenoxys** [comment]
Hello,

Can you enable debug and post the log output ?

**Comment by Gaby690** [comment]
8/22/2021, 12:55:32 PM Home[[37m2021-08-22T16:55:32.440Z[39m] [36m INFO[39m: ef/2744 on v0.3.36: [36mFinished initializing Eufy Security Platform[39m

8/22/2021, 12:55:32 PM Home[[37m2021-08-22T16:55:32.553Z[39m] [90mDEBUG[39m: ef/2744 on v0.3.36: [36mdiscoveringDevices[39m

8/22/2021, 12:55:34 PM Home[[37m2021-08-22T16:55:34.056Z[39m] [90mDEBUG[39m: ef/2744 on v0.3.36: [36mEufyClient connected false[39m

8/22/2021, 12:55:34 PM Home[[37m2021-08-22T16:55:34.057Z[39m] [31mERROR[39m: ef/2744 on v0.3.36: [36mNot connected can't continue![39m

8/22/2021, 12:55:35 PM Home WARNING unhandled rejection: Error: Request failed: https://mysecurity.eufylife.com/api/v1/passport/login -> 100028 - Failed to request.

**Comment by lenoxys** [comment]
Can you update to 1.0.0-rc2 and do the `Start over the wizard process` within the plugin config ?

**Comment by Gaby690** [comment]
it's on 1.0.0-rc2 and I'm using Hoobs

**Comment by Gaby690** [comment]
I did a factory reset to the Hoobs and installed 1.0.0-rc2 version and put the username and password but still

8/22/2021, 3:16:27 PMEufy Security Bridge starting

8/22/2021, 3:16:32 PMEufy Security BridgeInitializing HAP-NodeJS v0.9.4...

8/22/2021, 3:16:53 PMEufy Security BridgeLoaded plugin 'homebridge-eufy-security'

8/22/2021, 3:16:53 PMEufy Security BridgeRegistering platform 'homebridge-eufy-security.EufySecurity'

8/22/2021, 3:16:53 PMEufy Security BridgeLoading 1 platforms...

8/22/2021, 3:16:53 PMEufy Security BridgeEufySecurityFinished initializing Eufy Security Platform

8/22/2021, 3:16:54 PMEufy Security BridgePreparing Advertiser for 'Eufy Security Bridge F892' using bonjour-hap backend!

8/22/2021, 3:16:54 PMEufy Security BridgeStarting to advertise 'Eufy Security Bridge F892' using bonjour-hap backend!

8/22/2021, 3:16:54 PMEufy Security BridgeBridge is running on port 51826.

8/22/2021, 3:16:54 PMEufy Security BridgeEufySecurityERRORNot connected can't continue!

8/22/2021, 3:17:20 PMEufy Security BridgeConfiguration change

8/22/2021, 3:17:20 PMeufysecuritybridge stopping

8/22/2021, 3:17:25 PMEufy Security Bridge starting

8/22/2021, 3:17:30 PMEufy Security BridgeInitializing HAP-NodeJS v0.9.4...

8/22/2021, 3:17:34 PMEufy Security BridgeLoaded plugin 'homebridge-eufy-security'

8/22/2021, 3:17:34 PMEufy Security BridgeRegistering platform 'homebridge-eufy-security.EufySecurity'

8/22/2021, 3:17:34 PMEufy Security BridgeLoading 1 platforms...

8/22/2021, 3:17:34 PMEufy Security Bridge[[37m2021-08-22T19:17:34.567Z[39m] [36m INFO[39m: ef/12217 on v1.0.0-rc.2: [36mEufy Security Plugin: enableDetailedLogging on[39m

8/22/2021, 3:17:34 PMEufy Security Bridge[[37m2021-08-22T19:17:34.592Z[39m] [36m INFO[39m: ef/12217 on v1.0.0-rc.2: [36mFinished initializing Eufy Security Platform[39m

8/22/2021, 3:17:34 PMEufy Security Bridge[[37m2021-08-22T19:17:34.597Z[39m] [90mDEBUG[39m: ef/12217 on v1.0.0-rc.2: [36mdiscoveringDevices[39m

8/22/2021, 3:17:34 PMEufy Security BridgePreparing Advertiser for 'Eufy Security Bridge F892' using bonjour-hap backend!

8/22/2021, 3:17:34 PMEufy Security BridgeStarting to advertise 'Eufy Security Bridge F892' using bonjour-hap backend!

8/22/2021, 3:17:34 PMEufy Security BridgeBridge is running on port 51826.

8/22/2021, 3:17:35 PMEufy Security Bridge[[37m2021-08-22T19:17:35.224Z[39m] [90mDEBUG[39m: ef/12217 on v1.0.0-rc.2: [36mEufyClient connected false[39m

8/22/2021, 3:17:35 PMEufy Security Bridge[[37m2021-08-22T19:17:35.226Z[39m] [31mERROR[39m: ef/12217 on v1.0.0-rc.2: [36mNot connected can't continue![39m

**Comment by Gaby690** [comment]
8/22/2021, 3:53:40 PM Home [[37m2021-08-22T19:53:40.659Z[39m] [90mDEBUG[39m: ef/14550 on v1.0.0-rc.2: [36mdiscoveringDevices[39m

8/22/2021, 3:53:40 PM Home [[37m2021-08-22T19:53:40.676Z[39m] [90mDEBUG[39m: ef/14550 on v1.0.0-rc.2: [36mAuthenticate and get an access token { token: null, tokenExpiration: null }[39m

8/22/2021, 3:53:40 PM Home[[37m2021-08-22T19:53:40.683Z[39m] [90mDEBUG[39m: ef/14550 on v1.0.0-rc.2:

8/22/2021, 3:53:40 PM Home[90m    [36mRequest: {

8/22/2021, 3:53:40 PM Home method: 'post',

8/22/2021, 3:53:40 PM Home endpoint: 'passport/login',

8/22/2021, 3:53:40 PM Home baseUrl: 'https://mysecurity.eufylife.com/api/v1',

8/22/2021, 3:53:40 PM Home token: null,

8/22/2021, 3:53:40 PM Home data: { email: 'XXX@gmail.com', password: 'XXX' },

8/22/2021, 3:53:40 PM Home headers: {

8/22/2021, 3:53:40 PM Home app_version: 'v2.8.0_887',

8/22/2021, 3:53:40 PM Home os_type: 'android',

8/22/2021, 3:53:40 PM Home os_version: '30',

8/22/2021, 3:53:40 PM Home phone_model: 'EUFYCLIENT',

8/22/2021, 3:53:40 PM Home country: 'US',

8/22/2021, 3:53:40 PM Home language: 'en',

8/22/2021, 3:53:40 PM Home openudid: '327a9b5618b0bc3',

8/22/2021, 3:53:40 PM Home uid: '',

8/22/2021, 3:53:40 PM Home net_type: 'wifi',

8/22/2021, 3:53:40 PM Home mnc: '02',

8/22/2021, 3:53:40 PM Home mcc: '262',

8/22/2021, 3:53:40 PM Home sn: '6b2514e00ac2',

8/22/2021, 3:53:40 PM Home Model_type: 'PHONE',

8/22/2021, 3:53:40 PM Home timezone: 'GMT-04:00'

8/22/2021, 3:53:40 PM Home }

8/22/2021, 3:53:40 PM Home }[39m

8/22/2021, 3:53:40 PM Home[39m


For what it seems it can't get the token so it can log in

**Comment by Gaby690** [comment]
I uninstalled it, installed it again, did the username and password on the script and now it got it connected but still its not showing the cameras and I'm getting the warning at the bottom. I only get that warning with Eufy if I uninstall it it doesn't show it.

8/23/2021, 2:03:02 AM Home EufySecurity Finished initializing Eufy Security Platform

8/23/2021, 2:03:02 AM Home EufySecurity discoveringDevices

8/23/2021, 2:03:03 AM Home Setup URI 'X-HM://0023ISYWY06IT'

8/23/2021, 2:03:03 AM Home EufySecurityEufyClient connected true

8/23/2021, 2:03:03 AM Home EufySecurityPollingInterval: 10

8/23/2021, 2:03:03 AM Home EufySecurityRefresh data from cloud and schedule next refresh.

8/23/2021, 2:03:03 AM Home Starting to advertise 'Home 0D7C' using bonjour-hap backend!

8/23/2021, 2:03:03 AM Home Bridge is running on port 51826.

8/23/2021, 2:03:08 AM Home EufySecurityFound 2 stations.

8/23/2021, 2:03:08 AM Home EufySecurityFound Station _Serial Number of my device_ Home Base STATION { value: '192.168.1.14', timestamp: 1629619166000 }

8/23/2021, 2:03:08 AM Home WARNING unhandled rejection: TypeError: Cannot read property 'indexOf' of undefined

**Comment by lenoxys** [comment]
Can you do that again but enable debug straigh away ?

**Comment by Gaby690** [comment]
8/23/2021, 3:36:13 AMHome[[37m2021-08-23T07:36:13.416Z[39m] [36m INFO[39m: ef/3091 on v1.0.0-rc.2: [36mEufy Security Plugin: enableDetailedLogging on[39m
8/23/2021, 3:36:13 AMHome[[37m2021-08-23T07:36:13.438Z[39m] [36m INFO[39m: ef/3091 on v1.0.0-rc.2: [36mFinished initializing Eufy Security Platform[39m
8/23/2021, 3:36:13 AMHome[[37m2021-08-23T07:36:13.537Z[39m] [90mDEBUG[39m: ef/3091 on v1.0.0-rc.2: [36mdiscoveringDevices[39m
8/23/2021, 3:36:13 AMHome[[37m2021-08-23T07:36:13.913Z[39m] [90mDEBUG[39m: ef/3091 on v1.0.0-rc.2: [36mEufyClient connected true[39m
8/23/2021, 3:36:13 AMHome[[37m2021-08-23T07:36:13.915Z[39m] [90mDEBUG[39m: ef/3091 on v1.0.0-rc.2: [36mPollingInterval: 10[39m
8/23/2021, 3:36:13 AMHome[[37m2021-08-23T07:36:13.916Z[39m] [90mDEBUG[39m: ef/3091 on v1.0.0-rc.2: [36mRefresh data from cloud and schedule next 
8/23/2021, 3:36:32 AMHome[[37m2021-08-23T07:36:32.861Z[39m] [90mDEBUG[39m: ef/3091 on v1.0.0-rc.2: [36mFound 2 stations.[39m
8/23/2021, 3:36:32 AMHome[[37m2021-08-23T07:36:32.880Z[39m] [90mDEBUG[39m: ef/3091 on v1.0.0-rc.2: [36mFound Station T8010P1320450AE4 Home Base STATION { value: '192.168.1.14', timestamp: 1629619166000 }[39m
8/23/2021, 3:36:32 AMHomeWARNINGunhandled rejection: TypeError: Cannot read property 'indexOf' of undefined
8/23/2021, 3:36:43 AMHome[[37m2021-08-23T07:36:43.985Z[39m] [90mDEBUG[39m: ef/3091 on v1.0.0-rc.2: [36mPush Connected![39m

**Comment by Gaby690** [comment]
I put the default settings in Pollong intervals, ignoring devices and ignoring stating, and it shows them but it doesn't open them

8/23/2021, 3:52:52 AMHomeEufySecurityRestoring existing accessory from cache: Home Base
8/23/2021, 3:52:52 AMHomeEufySecurityWARNINGBackyard looks station but it's not could imply some errors Type: 3
8/23/2021, 3:52:52 AMHomeEufySecurityRestoring existing accessory from cache: Backyard
8/23/2021, 3:52:52 AMHomeEufySecurityRestoring existing accessory from cache: Front of the House
8/23/2021, 3:52:52 AMHomeEufySecurityWARNINGBackyard Looks like not compatible with hasBattery
8/23/2021, 3:52:52 AMHomeEufySecurityRestoring existing accessory from cache: Backyard
8/23/2021, 3:55:56 AMHome[Backyard] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.
8/23/2021, 3:56:02 AMHome[Front of the House] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.
8/23/2021, 3:56:04 AMHomeEufySecurityStarting video stream: 1280 x 720, 30 fps, 299 kbps Backyard
8/23/2021, 3:56:16 AMHomeEufySecurityDevice appears to be inactive. Stopping stream. Backyard
8/23/2021, 3:56:16 AMHomeEufySecurityStopped video stream. Backyard

**Comment by lenoxys** [comment]
can you share your device to me ?
eufy-plugin-test@secugrator.com

**Comment by Gaby690** [comment]
I just send you the invite

**Comment by Gaby690** [comment]
Now it's working but it takes long time to load

Also the logs are showing this:

8/23/2021, 4:17:39 AM Eufy ERROR [Eufy A2B7@Backyard@Enabled@On] Unhandled error thrown inside read handler for characteristic: Cannot read property 'value' of undefined
8/23/2021, 4:17:39 AM Eufy ERROR [Eufy A2B7@Backyard@Motion@On] Unhandled error thrown inside read handler for characteristic: Cannot read property 'value' of undefined

**Comment by Gaby690** [comment]
[log.txt](https://github.com/samemory/homebridge-eufy-security/files/7030632/log.txt)

**Comment by lenoxys** [comment]
Was able to reproduce, look like lib issue need more time to identify where and push a PR to bropat

**Comment by Gaby690** [comment]
Ok at least you could find what us happening

**Comment by lenoxys** [comment]
erf sorry Can I ask you to reshare to me ? I'm not getting the same issue. Looks like FLASHLIGHT CAMERA related.

**Comment by lenoxys** [comment]
Can you test on rc3 ?

**Comment by Gaby690** [comment]
It takes a long time to stream the cameras, sometimes it works and sometimes it just shows No Response this camera is not responding message in HomeKit

**Comment by Gaby690** [comment]
Eufy[[37m2021-08-24T02:09:08.776Z[39m] [90mDEBUG[39m: ef/28139 on v1.0.0-rc.3: [36mFFmpeg exited with code: null and signal: SIGKILL (Expected) Front of the House true[39m

**Comment by Gaby690** [comment]
[log.txt](https://github.com/samemory/homebridge-eufy-security/files/7035973/log.txt)
