### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hanses89** [samemory/homebridge-eufy-security#205]
### What happened?

A bug happened!

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

other (UnSupported)

### NodeJS Version

other (UnSupported)

### Operating System

Other

### Relevant log output

```shell
Hi.

I guess this is not a bug, but i cant get this plugin to work at all.
Im using hoobs... 

i get this in my logs:
8/25/2021, 10:16:01 AMeufysecuritybridge stopping
8/25/2021, 10:16:06 AMEufy Security Bridge starting
8/25/2021, 10:16:10 AMEufy Security BridgeLoaded plugin 'homebridge-eufy-security'
8/25/2021, 10:16:10 AMEufy Security BridgeLoading 1 platforms...
8/25/2021, 10:16:10 AMEufy Security BridgeEufySecurityFinished initializing Eufy Security Platform
8/25/2021, 10:16:10 AMEufy Security BridgeBridge is running on port 51886.
8/25/2021, 10:16:12 AMEufy Security BridgeWARNINGunhandled rejection: TypeError: Cannot read property 'indexOf' of undefined
```

**Comment by lenoxys** [comment]
Hello,

please have a look here : 

https://github.com/samemory/homebridge-eufy-security/wiki/Common-Issues

**Comment by hanses89** [comment]
Why did i choose hooobs then:P 

Thanks anyway

**Comment by hanses89** [comment]
The biggest difference between hoobs and homebridge is what?
Does either have more or less / the same plugins?

Installation done via terminal vs not?

Please elaborate

**Comment by lenoxys** [comment]
Don't know I'm not using HOOBS
