### ISSUE TITLE
Storing SnapShot Locally

### ISSUE THREAD

**Issue by lenoxys** [samemory/homebridge-eufy-security#207]
ok find out, it appear Eufy Security Cloud is not storing the snapshot image, so when we try to retrieve it it trow an error. I've removed it and put a message instead. 

We'll need to build snapshot store in order to make it available through HomeKit. Please bear with us on that feature request. It won't be implemented on 1.0.0. Maybe 1.1.0 but need to see with the other collaborators. I'm openning a new case to track that request.

_Originally posted by @lenoxys in https://github.com/samemory/homebridge-eufy-security/issues/185#issuecomment-905517899_

**Comment by steverae68** [comment]
Cool, is this the effect you mean.

Running the latest rc13 with the latest ffmpeg - we have sound !!! - sorry, getting carried away.

So when ever I move to my doorbell page, it displays an old picture from ages ago (last doorbell bell I believe) live stream then starts by tapping the preview and shows the live stream (super fast)

A new snapshot should be taken each time the preview is displayed - in theory like my other Poe cams.  I know this is a battery doorbell and will drain the battery more but this could be turned on or off in the plugin I guess

Another donation on the way guys - keep up the good work
