### ISSUE TITLE
[Bug]: Floodlight 2K with 2500 Lumen - Two Switches which don’t do anything 

### ISSUE THREAD

**Issue by superpower10** [samemory/homebridge-eufy-security#214]
### What happened?

Floodlight 2K with 2500 Lumen lights:

Two switches are added to HomeKit but don’t do anything. I hoped that one was for turning on the lights and the other for deactivating the camera. But no.

The switch for the light is essential for me, because I turn on the light with the HomePod so I don’t have to get my iPhone, open Eufy-App and the turn on light manually.

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Docker

**Comment by fullphat** [comment]
#221 was closed as a duplicate but refers to the older Floodlight cam.  Can any resolution to this issue please also be retrofitted to the older model?

**Comment by lenoxys** [comment]
Same implementation as I can see

**Comment by lenoxys** [comment]
Duplicate #221
