### ISSUE TITLE
[enhancement]: Expose floodlight cam lights as Light Bulb

### ISSUE THREAD

**Issue by fullphat** [samemory/homebridge-eufy-security#221]
### Describe the solution you'd like

As per title, if the floodlight cam (T8420) lights could be exposed as a light switch, I can then turn them on or off manually, or via HomeKit automations, and this would be very cool. 👍🏼

**Comment by lenoxys** [comment]
Duplicate #214

**Comment by fullphat** [comment]
This appears to be working as of the latest beta (V1.1.1 beta 1) - great job! 👍🏼
