### ISSUE TITLE
[Bug]: Entry sensor always open in homekit

### ISSUE THREAD

**Issue by ppernet** [samemory/homebridge-eufy-security#231]
### What happened?

Hi,

I've added a entry sensor to my eufy install. I see it in Home app. In eufy app everything is ok. When the door is closed, the sensor appear closed in eufy app but not in homekit. In home app, the sensor is always open.
I've restarted homebridge and sensor appears closed until I open the door then, it stays open in homekit...
Any idea  ? Thank you !

### Device Type

Contact Sensor (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Raspbian

**Comment by schliemann** [comment]
@ppernet Did you enable push notifications for the entry sensors? Otherwise it won't currently work.

**Comment by ppernet** [comment]
Yes, i've seen that. Now it works. Thanks.
