### ISSUE TITLE
[enhancement]: Hide station without hiding attached devices

### ISSUE THREAD

**Issue by sswany** [samemory/homebridge-eufy-security#232]
### Describe the solution you'd like

Thanks for all your work on this!

It would be helpful to allow for hiding the station itself without hiding attached devices. My use case is to use an associated battery doorbell but without exposing the station to HomeKit as a security system. Since I already have a security system in HomeKit, Siri always asks 'which one' even though I never have the need to change the setting on the Eufy station.

**Comment by lenoxys** [comment]
Hello,

Can you test `1.1.1-beta.1` ?
https://github.com/samemory/homebridge-eufy-security/wiki/Beta-Version

**Comment by sswany** [comment]
That seems to work great! Thank you 🙏🏼

**Comment by lenoxys** [comment]
Thanks for your feedback

**Comment by CooperCGN** [comment]
Is this already included in the latest non beta version?
