### ISSUE TITLE
[Bug]: open/close trigger is not implemented 

### ISSUE THREAD

**Issue by tecken415** [samemory/homebridge-eufy-security#233]
### What happened?

I am attempting to implement eufy lock into homebridge I get the front door open/close trigger is not implemented along with the handle battery level get wrong return value. What in the config file do I need to change or add? Thank you 

### Device Type

Station (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Mac OS X

**Comment by tecken415** [comment]
I did with no luck

Mark J. Restivo
________________________________

**Comment by lenoxys** [comment]
Hello,

Lock/Unlock is not officially supported.

**Comment by tecken415** [comment]
Is there a beta that I can install in homebridge to be able to test it?

Mark J. Restivo
________________________________

**Comment by tecken415** [comment]
Does it matter thag I have the t8510? I know that the 8500 is supported

**Comment by afalahi** [comment]
Will the smart lock be supported in the future? Thanks!
