### ISSUE TITLE
[enhancement]: Alarm statuses as switches

### ISSUE THREAD

**Issue by lpaso** [samemory/homebridge-eufy-security#238]
### Describe the solution you'd like

The idea is to have, in addition to the « security system » mode, 4 switches (1 per status) to be able to control the eufy security via automations, as there are limitation to control « security systems » items via automations.

**Comment by lenoxys** [comment]
Good idea!

**Comment by fullphat** [comment]
+1 as HomeKit insists on prompting me to run an automation that involves a Security System when all I want is to switch from Home to Away mode. 👍🏼

**Comment by schliemann** [comment]
@kengura3 Should be possible already now?
