### ISSUE TITLE
[Bug]: SoloCam S40 battery consumption problems

### ISSUE THREAD

**Issue by artomal** [samemory/homebridge-eufy-security#247]
### What happened?

Hi there! 

I’ve been testing this plugin with new SoloCam S40 currently and noticed that battery consumption is pretty bad when the camera is configured with this plugin, it cannot keep up with the solar charge. Once I disabled the plugin, camera was able to recharge itself from 78% to 100% in 4-5 days under the same load.

### Device Type

other (UnSupported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian

**Comment by schliemann** [comment]
Do you have any device that tries to fetch snapshots or live footage via Homekit often?

**Comment by artomal** [comment]
Not really, at least I haven't setup anything specifically. I just installed the plugin and use it with my homehub (apple tv) that's it.

**Comment by artomal** [comment]
Has it been fixed?

**Comment by schliemann** [comment]
@artomal Should be fixed by the client library.
