### ISSUE TITLE
[Bug]: Door Lock shows in Homekit but unlocking and locking does not work

### ISSUE THREAD

**Issue by Relixae** [samemory/homebridge-eufy-security#251]
### Describe the solution you'd like

Homebridge says that the Open/Close tripper is not implemented for the smart lock. It would be greatly appreciated if this could be added.

**Comment by jaredallard** [comment]
Running into the same issue here. Happy to provide any info needed

**Comment by jaredallard** [comment]
@samemory Should I open a new issue or will you re-open (sorry to ping!)

**Comment by schliemann** [comment]
@jaredallard What model is it?

**Comment by Relixae** [comment]
Happy to re-open. Just not sure how

**Comment by schliemann** [comment]
It might very well be an issue with the client library not supporting the model.

**Comment by jaredallard** [comment]
Model: T8510111 (https://smile.amazon.com/gp/product/B0869MGCR4)

This is connected with a wifi bridge (https://smile.amazon.com/gp/product/B08LPJ15LM) (can't find the model :( )

**Comment by schliemann** [comment]
@jaredallard I would suggest that you create an issue in bropats github repo

https://github.com/bropat/eufy-security-client

**Comment by jaredallard** [comment]
@schliemann Seems like it might be supported? https://github.com/bropat/eufy-security-client/issues/89#issuecomment-1003828917

Unsure, will make an issue there if you want still. Sorry for the late replies my Github notifications are a mess

**Comment by jaredallard** [comment]
Created issue w/ module https://github.com/bropat/eufy-security-client/issues/110

**Comment by lenoxys** [comment]
Hello,

Still 1.5.0. We will have a look when the version will change and if the release note is mentioning it.

**Comment by jaredallard** [comment]
So bropat says it doesn't look like it's being triggered. Any ideas here?
