### ISSUE TITLE
[Bug]: Eufy Homebase 2 not available any more.

### ISSUE THREAD

**Issue by Dominik-1980** [samemory/homebridge-eufy-security#263]
### What happened?

A bug happened!

Since the newer versions of the plugin the Homebase 2 is not available any more in homebridge.
Rollback doesn’t work as well. Homebase 2 is gone.

### Device Type

Station (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian

**Comment by lenoxys** [comment]
Is it possible to share your devices to me ?

**Comment by C4ptainMeow** [comment]
So i found that it will work, when you have shared youre devices with an guest Account and give them adminrights. Only then the Homebase appears in Homebridge. So maybe its just something that eufy changed

**Comment by Dominik-1980** [comment]
> So i found that it will work, when you have shared youre devices with an guest Account and give them adminrights. Only then the Homebase appears in Homebridge. So maybe its just something that eufy changed 

Great!! You're right!
The guest account now needs admin rights to share the homebase.

Thank you very much!
