### ISSUE TITLE
[Bug]: All added Eufy devices disappear in Home app if Homebridge is down for some time

### ISSUE THREAD

**Issue by njuart** [samemory/homebridge-eufy-security#264]
### What happened?

Hi, so issue is following. I had a power outage for a half of a day, so my Raspberry was down, when it went up again I've noticed that all my added Eufy devices were gone from Home app. After some time and a couple of restarts they were added again by themselves, but as new devices, meaning I've lost all my automations and had to rename them again. I've decided to check, maybe it's a sort of a one-time issue, so I've powered off my Raspberry again, this time intentionally, waited for a couple of hours, and voila it happened again, same stuff, besides that it is related only to Eufy plugin, all my other 12 plugins didn't show this behaviour. Anyway it can be fixed? It's a bit annoying to create automations everytime it happens. Thx in advance!

### Device Type

Station (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Docker

### Relevant log output

```shell
Could not retrieve logs unfortunately.
```

**Comment by breather74** [comment]
I've got the exact same issue as this. Very frustrating as I have a lot of automation linked with the eufy devices hence them resetting makes me have to rename, regroup and re program every device. Desperately looking for a fix to this. The only bad link in my smart home.

**Comment by lenoxys** [comment]
Hey,

Eufy did change when you set guest rights instead of admin. You need to change the rights of the eufy account to admin.

Regards,
Aurelien

**Comment by njuart** [comment]
But my guest account, for example, was set to admin rights since the beginning. Still I have this issue.

**Comment by breather74** [comment]
Same mine has also been set to admin rights from the start

**Comment by njuart** [comment]
Happened to me again just right now. So frustrating. I've updated to Homebridge 1.38, it restarted, after restart I saw this

![image](https://user-images.githubusercontent.com/21228802/142951350-e394a17e-8730-4105-b64b-e2b9def6d17e.jpeg)

And then this

![image](https://user-images.githubusercontent.com/21228802/142951446-f00b8dac-3237-47a8-a8a7-0ac8a8e0a141.jpeg)

I've opened Home app and all my Eufy devices disappeared, so all automations related to them also.

**Comment by njuart** [comment]
Basically every server restart or even HB restart, it happens. Unfortunately it makes plugin almost unusable for me, as I might do a couple of restarts during a day, I thought it somehow related to child bridge, but it's not, it happens without child bridge as well. @lenoxys Any ideas? Thx in advance

**Comment by breather74** [comment]
Personally for me this issue only happens if the eufy HomeBase is down during the starting up of homebridge. Otherwise starting/ restarting of homebridge works fine. Nonetheless this is still a hassle and a solution would be very nice. I wonder if everyone with this plugin has this issue 🤔

**Comment by njuart** [comment]
Now after issue happened again, plugin doesn't find any device at all.

**Comment by gielk** [comment]
> Now after issue happened again, plugin doesn't find any device at all.

I'm currently having the exact same problem. I'm waiting for them to come back but every time the message that no devices were found.

**Comment by njuart** [comment]
> > Now after issue happened again, plugin doesn't find any device at all.
> 
> 
> 
> I'm currently having the exact same problem. I'm waiting for them to come back but every time the message that no devices were found.
> 
> 
> 
> [24/11/2021, 17:19:56] [Homebridge UI] [homebridge-eufy-security] [1.0.4] DEBUG: Response: 
> 
> 
> 
> [24/11/2021, 17:19:56] [Homebridge UI] [homebridge-eufy-security] [1.0.4] ERROR: Status return code not 200 { status: 204, statusText: 'No Content' }

Yup, I see exactly the same in debug logs. Deleting plugin config doesn't help, uninstalling plugin completely doesn't help either.

**Comment by schliemann** [comment]
This is the issue in the client library.

https://github.com/bropat/eufy-security-client/issues/67

**Comment by schliemann** [comment]
If you need a quickfix you would have to update the client library manually.

**Comment by gielk** [comment]
> If you need a quickfix you would have to update the client library manually.

Can u explain how to do this or where can I find a how to?

**Comment by schliemann** [comment]
Update the packages.config file to use version 1.4.0 of eufy-security-client.

**Comment by schliemann** [comment]
The run npm install

**Comment by ppernet** [comment]
Same here. During last days, Eufy device reappeared after few server restart but now, nothing to do, no eufy devices in homekit app.
Hope it will be fixed soon because most of us have lot of automation including Eufy devices...

**Comment by breather74** [comment]
Incredibly frustrating, on restart of hoobs all devices have vanished and cannot be found despite the homebase being on the whole time. (In the past the devices would only reset if HomeBase was off during boot which was still shitty but not as bad as it is now). Hoping the devs can fix this soon.

**Comment by loganfuller** [comment]
I'm also having this issue. Can we not have a config setting to never remove cached devices?

**Comment by breather74** [comment]
I hope the plugin devs are seeing this, I think this needs to be top priority to really make this plugin full proof

**Comment by fenninculus** [comment]
For me this issue was resolved in the latest patch.

**Comment by schliemann** [comment]
> I'm also having this issue. Can we not have a config setting to never remove cached devices?

Wouldn't help. If the client library doesn't find the device then commands can't be sent any way.

**Comment by loganfuller** [comment]
> > I'm also having this issue. Can we not have a config setting to never remove cached devices?
> 
> Wouldn't help. If the client library doesn't find the device then commands can't be sent anyway.

I don't follow. The issue is in removing cached devices because of an ephemeral connection issue. While the library wouldn't be able to find the device, it would in the future once the temporary issue clears up.

**Comment by schliemann** [comment]
> > > I'm also having this issue. Can we not have a config setting to never remove cached devices?
> > 
> > 
> > Wouldn't help. If the client library doesn't find the device then commands can't be sent anyway.
> 
> I don't follow. The issue is in removing cached devices because of an ephemeral connection issue. While the library wouldn't be able to find the device, it would in the future once the temporary issue clears up.

Ah. Now I understand. It might be possible.

**Comment by schliemann** [comment]
I have asked in the homebridge discord if we can determine when a cached device was added. Then a config element could be added specifying how many days we would like to keep inactive devices.

**Comment by schliemann** [comment]
![699CD397-85AF-40D3-A371-44FB20C681FC](https://user-images.githubusercontent.com/10818044/147950476-08233ed1-9cc2-4e20-b0bc-5fc230432c11.jpeg)

**Comment by lenoxys** [comment]
I used to implement a clean task when device is more link to the station.

https://github.com/samemory/homebridge-eufy-security/blob/master/src/platform.ts#L304-L313

Isn't it enough ?

**Comment by schliemann** [comment]
@lenoxys Yeah. Maybe the easiest fix would be a boolean in the config that determines if the user wants accessories cleaned on startup.

**Comment by NorthernMan54** [comment]
@schliemann In my Tasmota plugin I have a setting that remove's / cleans up not responding devices after a set period of time.  I defaulted it to 24 hours just to avoid these type of issues.  I just set a nodejs for timeout for each accessory on startup, and if status hasn't been received / updated before the timeout is invoked, remove it.  It also resets the timeout with each status update.

As my setup got hacked by this, do you need help in configuring this ?

**Comment by schliemann** [comment]
I think it is a relatively small fix. But I have used all my spare time on the local stream snapshot.

**Comment by loganfuller** [comment]
Can we re-open this? With this issue, I have to completely rebuild my eufy automations at least once a week due to intermittent connection issues..

**Comment by loganfuller** [comment]
Still an issue.

**Comment by lenoxys** [comment]
You will be able to disable this behavior within the settings.

**Comment by Bwade095** [comment]
Did this get fixed? I’m still having this issue
