### ISSUE TITLE
Where to fill in the 2FA code

### ISSUE THREAD

**Issue by molderiekerink** [samemory/homebridge-eufy-security#267]
### What happened?

I want to put my Eufy doorcam to Homekit. In de configuration it says something about the 2FA autentication.... My Eufy account has 2FA, but where can I fill it in the hoobs configuration? 

### Device Type

Doorbell (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v12 (Supported)

### Operating System

Mac OS X

**Comment by lenoxys** [comment]
Hello

When doing the wizard under settings (version 1.0.x). This wizard is not available on HOOBS.
