### ISSUE TITLE
[Bug]: Security status doesn't change via home app. 

### ISSUE THREAD

**Issue by gintonic4all** [samemory/homebridge-eufy-security#269]
### What happened?

Approx one day after (re)starting homebridge  switching the security status in the home app doesn't lead to a change in the eufy app. The only thing I see is that the home app tries "activating"... restarting the home app (or after a while) --> old status of the security switch is displayed again. In addition, switching the status of security in the eufy app doesn't lead to a change in the home app. 

Restarting homebridge --> everything seems fine again.

My setup: 
iOS 15.1
Apple TV 4K + 6 homepod mini 
Homebridge 1.3.6
Node.js 16.13.0
NPM 8.1.0
Homebridge Eufy Security 1.0.4

Eufy Solo Cam E40.

Thanks in advance for your help and for this nice plug-in. 

### Device Type

other (UnSupported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian

### Relevant log output

```shell
[11/17/2021, 8:10:08 AM] [EufySecurity-1.0.4] DEBUG: Garten SET StationGuardMode: 1
```

**Comment by schliemann** [comment]
Need more info. For example logging of the problem.

**Comment by schliemann** [comment]
No response regarding logging. I don't experience this issue.

**Comment by gintonic4all** [comment]
is okay now with the new version. thanks.

**Comment by lenoxys** [comment]
thanks for your feedback
