### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by n33do2** [samemory/homebridge-eufy-security#272]
### What happened?

No Video in Home App. 
two errors :
Failed to fetch snapshot.
FFmpeg exited with code: null and signal: SIGABRT (Unexpected) XXXXXXXX

Running Homebridge on MacOS 10.13.6

### Device Type

Doorbell (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Mac OS X

**Comment by schliemann** [comment]
Duplicate of https://github.com/samemory/homebridge-eufy-security/issues/295
