### ISSUE TITLE
[Bug]: Battery doorbell stream does not work

### ISSUE THREAD

**Issue by cpvbruno** [samemory/homebridge-eufy-security#274]
### What happened?

Everything besides video stream works on my eufy 1080p battery doorbell, any work in progress to fix that? I’m attaching some images that may help:

![057F9A22-2C5C-4D89-8459-41C02BE551AB](https://user-images.githubusercontent.com/5808343/142780472-93f2d0cb-df53-49ca-a5cb-ecef25f51a9d.png)
![C869365E-7F8A-4EC2-BE0A-AB1BA2869383](https://user-images.githubusercontent.com/5808343/142780473-8acae243-d3f5-42a3-8037-b31169293aa1.png)

### Device Type

Doorbell (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian

**Comment by cpvbruno** [comment]
Yes, and suddenly it started working. I’ll close the issue for now and reopen if it stops

**Comment by cpvbruno** [comment]
After a while not using the camera, it starts not working anymore again 

![Uploading 3EE26DBF-3EF2-4F8F-B6F3-4D9050954BF1.png…]()

**Comment by toosweet** [comment]
Battery and wired doorbell not streaming on the latest version . Installed the beta version, now both cameras are working fine.

**Comment by eRWN** [comment]
Hello,

I wonder if this can help :
https://github.com/samemory/homebridge-eufy-security/issues/284#issuecomment-981137804
(I don't know how to do it to test)

**Comment by schliemann** [comment]
Duplicate of https://github.com/samemory/homebridge-eufy-security/issues/295
