### ISSUE TITLE
[Bug]: Enabled & Motion Switches disapearing after restart

### ISSUE THREAD

**Issue by SimBro2708** [samemory/homebridge-eufy-security#275]
### What happened?

First appeared a few days ago.
Everytime I restart hombridge the two switches get randomly removed.
The only work arround for me currently is to start over the setup, after that the switches reapear most of the time.
But are of course reset to the default status and I would have to implement them in my automations again.

Tested it with a Guest (Admin) Account and with the main one -> all have the same outcome.

### Device Type

Indoor Camera (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Raspbian

**Comment by SimBro2708** [comment]
> Did you check this [Common Issues](https://github.com/samemory/homebridge-eufy-security/wiki/Common-Issues) pages ?

Yes, but no solution mentioned.

**Comment by schliemann** [comment]
Might have been caused by the 204 error where devices were sometimes not found.
