### ISSUE TITLE
[Bug]: Beta doorbell streaming is perfect but…

### ISSUE THREAD

**Issue by cpvbruno** [samemory/homebridge-eufy-security#276]
### What happened?

Since the stable version was not working for me, I tried the 1.1.1beta2 and the streaming works like a charm, the only issue is when I leave the streaming it breaks homebridge and it has to restart:

![15434D0D-1480-4AEE-8184-1CD9BCDC5E0E](https://user-images.githubusercontent.com/5808343/142937661-c8faa743-5181-49e8-ab54-2c412d4e9f72.png)

### Device Type

Doorbell (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian

**Comment by tojorocha** [comment]
Same here

**Comment by schliemann** [comment]
Duplicate of https://github.com/samemory/homebridge-eufy-security/issues/262
