### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Klunk80** [samemory/homebridge-eufy-security#277]
### What happened?

A bug happened! Wired Doorbell 2k (T8200). On setting up the config and saving followed by a restart my doorbell shows up and works perfectly until the next time homebridge is restarted then the doorbell disappears from Homekit. To make it appear again i have to go into the plugin settings and press save and restart. All my details in the config never disappear and just require the save and restart each time to get it back.

### Device Type

Doorbell (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Raspbian

**Comment by tojorocha** [comment]
Same here

**Comment by schliemann** [comment]
Could this be related to the issue regarding discovering devices error in november? Is the issue still there on V1.0.6+?

**Comment by Klunk80** [comment]
The issue was resolved with the next update V1.0.6.
