### ISSUE TITLE
Snapshot Image not updating

### ISSUE THREAD

**Issue by jasonwfrancis1** [samemory/homebridge-eufy-security#28]
When opening the camera in the home app, when the snapshot should refresh before opening the camera, it does not update like my other cameras. and in the logs i see this:

13/06/2021, 12:04:44 [Front Door] Snapshot request handler provided empty image buffer!

This is for a Eufy Doorbell

**Comment by jasonwfrancis1** [comment]
I also have these errors when restarting home bridge:

13/06/2021, 12:36:36 [HOOBS 1CBA@HomeKit Camera Active] The write handler for the characteristic 'HomeKit Camera Active' on the accessory 'Front Door' didn't respond at all!. Please check that you properly call the callback!
13/06/2021, 12:36:36 [HOOBS 1CBA@Event Snapshots Active] The write handler for the characteristic 'Event Snapshots Active' on the accessory 'Front Door' didn't respond at all!. Please check that you properly call the callback!

**Comment by jasonwfrancis1** [comment]
{"name":"eufyLog","hostname":"hoobs","pid":15475,"level":50,"msg":"Error: Error: read ETIMEDOUT\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {\n  errno: -110,\n  code: 'ETIMEDOUT',\n  syscall: 'read'\n}","time":"2021-06-13T11:39:45.236Z","v":0}

**Comment by mmz06** [comment]
Same issue for me:
`[La Sonnette] Snapshot request handler provided empty image buffer!
{"name":"eufyLog","hostname":"Plex4","pid":8343,"level":30,"msg":"Livestream of camera T8210P00204439AB started","time":"2021-06-15T08:28:08.170Z","v":0}`

**Comment by Kneudel** [comment]
Same Issue here with the doorbell.

I'm not sure if the doorbell supports it by default.

**Comment by lenoxys** [comment]
It should be fixed now ?

**Comment by Kneudel** [comment]
Yes it is.

**Comment by lenoxys** [comment]
Thanks for your feedback !
