### ISSUE TITLE
[Bug]: Eufy security not working after Hoobs updated to 4.1.15

### ISSUE THREAD

**Issue by xixihahajeff** [samemory/homebridge-eufy-security#283]
### What happened?

Eufy security not working. Devices are not showing up under accessories. Will probably need an update after Hoobs updated to version to 4.1.15.

### Device Type

Contact Sensor (Supported)

### Plugin Version

v0.2.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Raspbian

### Relevant log output

```shell
eufysecuritybridge stopping
25/11/2021, 4:49:10 PMEufy Security Bridge starting
25/11/2021, 4:49:22 PMEufy Security BridgeLoaded plugin 'homebridge-eufy-security'
25/11/2021, 4:49:22 PMEufy Security BridgeLoading 1 platforms...
25/11/2021, 4:49:22 PMEufy Security BridgeEufySecurityFinished initializing Eufy Security Platform
25/11/2021, 4:49:23 PMEufy Security BridgeBridge is running on port 51866.
25/11/2021, 4:49:28 PMEufy Security BridgeEufySecurityWARNINGPush Closed!
```

**Comment by Loatty** [comment]
I am also running into this problem

**Comment by schliemann** [comment]
Push service can fail for many reasons. We need some more logs.
