### ISSUE TITLE
T8202 support

### ISSUE THREAD

**Issue by sfguyfor20** [samemory/homebridge-eufy-security#285]
### Describe the solution you'd like

Is it possible to add the T8202 doorbell as a supported device?

**Comment by schliemann** [comment]
As far as I can read on Bropats repo the 8202 is not in his list of supported devices. Please make an inquiry on his issue tab. He might need to temporarily have access to your doorbell to succeed.

https://bropat.github.io/eufy-security-client/#/supported_devices
