### ISSUE TITLE
Not receiving doorbell notifications

### ISSUE THREAD

**Issue by jasonwfrancis1** [samemory/homebridge-eufy-security#30]
I am currently not receiving any doorbell notifications, all of the notifications in the accessory are enabled.

**Comment by andyrooo82** [comment]
Same for me. I can live stream ok but not receiving any notifications at all (iPhone, Apple Watch or Apple TV) on the eufy app notifications are enabled but I've disabled notifications from the Eufy app because I want them from the Home app.

**Comment by PeterAlexander75** [comment]
Notifications took a while to kick in for me. I stopped getting them and now they’re back.

**Comment by andyrooo82** [comment]
> Notifications took a while to kick in for me. I stopped getting them and now they’re back.

Interesting, I’ll wait a bit and see if they start coming through. Do you get anything in the logs when they do come in?

**Comment by jasonwfrancis1** [comment]
I’ve not managed to get any notification. There is a line in the logs about push notifications but nothing happens.

**Comment by PeterAlexander75** [comment]
It was weird. Went in and out several times. No notifications. Then left on the bike for a ride (hello from the pub garden) and walked by the camera and got a HomeKit notification of motion, but no eufy one. I seem to be having issues getting eufy native notifications, although the Homebase does ring.

**Comment by andyrooo82** [comment]
@PeterAlexander75 enjoy the pub garden!!

I get eufy notifications on iPad (enable is here but not on my iPhone) but nothing from Home app.
nothing get written to homebridge logs either

**Comment by farisbangsar** [comment]
same here. i cant get any doorbell ringing notifications or homepod chime. i've tried reinstalling it and enabling all notifications. 
was really hoping i could get the doorbell notifications on the apple tv

**Comment by andyrooo82** [comment]
I get Home app notifications if I change the Homebase status but not receiving any notifications from doorbell (motion or ring)

**Comment by PeterAlexander75** [comment]
My one notifications seems to have been Ann aberration. Same. I am getting no notifications from HomeKit or Eufy. Wondering is somehow I’ve messed up my eufy settings, although everything’s appears in order.

**Comment by andyrooo82** [comment]
> My one notifications seems to have been Ann aberration. Same. I am getting no notifications from HomeKit or Eufy. Wondering is somehow I’ve messed up my eufy settings, although everything’s appears in order. 

You've not got locked out of your account have you?

**Comment by PeterAlexander75** [comment]
Nope. All good.

**Comment by PeterAlexander75** [comment]
Update: uninstalled and reinstalled the eufy app and all good again. They’ve recently gone to v3, so I’d suggest updating it, then uninstalling and reinstalling as necessary. I also took the opportunity to add 2FA on my main account.

**Comment by andyrooo82** [comment]
> Update: uninstalled and reinstalled the eufy app and all good again. They’ve recently gone to v3, so I’d suggest updating it, then uninstalling and reinstalling as necessary. I also took the opportunity to add 2FA on my main account. 

Will give it a whirl and see if I get the same results. Did you have to uninstall and reinstall the plugin or just the eufy app?

**Comment by mmz06** [comment]
No notification in Homekit for doorbell 2K (T8210), for me neither, even if video works from it.
The amount of generated logs is quite high, as I own 4 cams + 1 doorbell, so it's hard to tell which one is relevant.
This one is the only one looking unclear to me:
`[6/15/2021, 10:33:48 AM] [homebridge-eufy-security] This plugin generated a warning from the characteristic 'Programmable Switch Event': Characteristic not in required or optional characteristic section for service CameraOperatingMode. Adding anyway.. See https://git.io/JtMGR for more info.`

**Comment by lenoxys** [comment]
this is fixed in #41
