### ISSUE TITLE
[Bug]: Pan/Tilt Camera doesn't show stream 

### ISSUE THREAD

**Issue by hoaxlayer** [samemory/homebridge-eufy-security#300]
### What happened?

After installing and configuring the plugin using ADMIN guest credentials, Homebridge shows the attached log error. No stream is visible, but a "home security" accessory is added in Homekit.
Toggling the "Livestream from Camera device" has no visible effect.

Some additional details:

-Using the Homebridge docker image to run it.
-Using 64-bit Raspbian

Please let me know if I can provide more useful info.

### Device Type

Indoor Camera (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian

### Relevant log output

```shell
[EufySecurity] Device looks station but it's not could imply some errors Type: 31
```

**Comment by eulisef** [comment]
just curious: why would you need homebridge for the pan/tilt camera? it has native homekit support.
i have three of them and i actually added them to the exclusions of this plugin so it doesn't interfere with native homekit

**Comment by Mike92115** [comment]
@eulisef 

For me I bring my 2K P&T in using HomeBridge, they were in my Home before but I had to remove them for a problem I was having and now they will add back but will not stream and the only option is to wipe and recreate my home and that I am not willing to do as I would have to re-add everything and re-set up all my scenes and automations.

> just curious: why would you need homebridge for the pan/tilt camera? it has native homekit support.
> i have three of them and i actually added them to the exclusions of this plugin so it doesn't interfere with native homekit

**Comment by Haglerd** [comment]
> just curious: why would you need homebridge for the pan/tilt camera? it has native homekit support. i have three of them and i actually added them to the exclusions of this plugin so it doesn't interfere with native homekit

I have three cameras at another house that isn't homekit compatible. I'd like to pull those into my homekit setup. So I've added them and have the same issue. Just another use case for you

**Comment by schliemann** [comment]
Please try with latest version.

**Comment by stef1949** [comment]
> just curious: why would you need homebridge for the pan/tilt camera? it has native HomeKit support. I have three of them and I actually added them to the exclusions of this plugin so it doesn't interfere with native homekit

Having 2k  Pan/Tilt support is useful to me as I don't have a HomeKit hub. This means I can have my Eufy cam in HomeKit and still retain essential features like recording, object based detection etc

**Comment by Haglerd** [comment]
> > just curious: why would you need homebridge for the pan/tilt camera? it has native HomeKit support. I have three of them and I actually added them to the exclusions of this plugin so it doesn't interfere with native homekit
> 
> Having 2k Pan/Tilt support is useful to me as I don't have a HomeKit hub. This means I can have my Eufy cam in HomeKit and still retain essential features like recording, object based detection, zones etc

That is genius, didn't think about that. If this plugin ever gets up to par, I might actually go that route!

**Comment by fullphat** [comment]
Same here: I have three 2Ks and I use one of them as a doorbell cam via HomeBridge and the homebridge-ffmpeg plugin.  Works a treat and it means I get 2K streaming and recording as well as the Eufy features which HomeKit would otherwise disable.

Apart from the lack of HKSV, it's pretty much the best of both worlds.

**Comment by hoaxlayer** [comment]
> Please try with latest version.

Already tried with the latest version. The problem persists.

**Comment by schliemann** [comment]
@hoaxlayer Please provide logs for your bug. Preferably with enabledetailedlogging set to 2.

**Comment by adamxfort** [comment]
Same issue, here is the debuglog

**Comment by adamxfort** [comment]
Same as above, I just see the camera as a security toggle but not as a camera in homekit. I have the Livestream from Camera device enabled in the plugin config.

**Comment by lenoxys** [comment]
As per your feedback I'm closing this one. Please open another issue for the ffmpeg
