### ISSUE TITLE
[enhancement]:  Option to remove "Security" mapping features. 

### ISSUE THREAD

**Issue by Haglerd** [samemory/homebridge-eufy-security#302]
### Describe the solution you'd like

The functionality to, "Change how each mode in the HomeKit security system is mapped to the modes in the Eufy App" would be better if you had a way to ignore it all together. I have no idea what that is or what it's asking. I don't want it to sync with anything involving my security system. An "off" or "ignore" or "do nothing" option would be nice in this instance. 

Also, some better documentation around what that is and what it's actually doing would help people make the best choice given the options available.

**Comment by schliemann** [comment]
Don't they have default values if unassigned?

**Comment by Haglerd** [comment]
They do, but that doesn’t change anything in regard to this request. It defaults to “home”.

**Comment by schliemann** [comment]
https://github.com/samemory/homebridge-eufy-security/blob/e86fa7983f715b7a94dbadb9fea50341bc994b9e/src/accessories/StationAccessory.ts#L144-148

**Comment by schliemann** [comment]
What would you want home to default to if not "home"?

**Comment by Haglerd** [comment]
“ would be better if you had a way to ignore it all together. I have no idea what that is or what it's asking. I don't want it to sync with anything involving my security system. An "off" or "ignore" or "do nothing" option would be nice”

**Comment by schliemann** [comment]
It is one of the main functionalities of the plugin. But you can ignorer stations through the config. So that is what you could try.
