### ISSUE TITLE
[enhancement]: Add support for automation based on doorbell button/sound

### ISSUE THREAD

**Issue by Rubl80** [samemory/homebridge-eufy-security#303]
Would like to see a device/action in HomeKit for my Eufy 2K doorbell, based on when a user click on the doorbell an activate the doorbell sound.

Eg. so when a user hits the doorbell button (sound), an automation based on that action can begin in Homekit.

For me I would use this automation to lock my door, when I press the doorbell button on my 2K doorbell.

Hope it can be done, and thx for a useful plugin.

**Comment by schliemann** [comment]
Which homekit device should the doorbell press be? A switch?

**Comment by Rubl80** [comment]
Guess it should be a switch, yes.

**Comment by Rubl80** [comment]
Or perhaps better a doorbell. And inside there should be an automation action called "when button is pressed".

**Comment by schliemann** [comment]
@Rubl80 Pretty sure the homekit doorbell device does not support this. But I will look.

**Comment by Rubl80** [comment]
If not possible a switch can also do the job

**Comment by schliemann** [comment]
This can apparently be achieved in 3rd party apps like eve (free). Probably also Home+ 5.

**Comment by Rubl80** [comment]
You are right sir :-) thank you very much @schliemann 🥇 and merry Christmas
