### ISSUE TITLE
[Bug]: device not showing after installation

### ISSUE THREAD

**Issue by xixihahajeff** [samemory/homebridge-eufy-security#305]
### What happened?

Devices not appearing after software upgrade.

### Device Type

Contact Sensor (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian

### Relevant log output

```shell
26/12/2021, 9:21:58 AMEufy Security Bridge starting
26/12/2021, 9:22:12 AMEufy Security BridgeLoaded plugin 'homebridge-eufy-security'
26/12/2021, 9:22:12 AMEufy Security BridgeLoading 1 platforms...
26/12/2021, 9:22:12 AMEufy Security BridgeEufySecurityFinished initializing Eufy Security Platform
26/12/2021, 9:22:13 AMEufy Security BridgeBridge is running on port 51876.
26/12/2021, 9:22:15 AMEufy Security BridgeEufySecurityERRORNot connected can't continue!
```

**Comment by xixihahajeff** [comment]
Yes, i did.
Uninstalled and reinstalled a couple of times. Problem persists.

**Comment by schliemann** [comment]
Your error is that the client library can't connect.

https://github.com/samemory/homebridge-eufy-security/blob/e86fa7983f715b7a94dbadb9fea50341bc994b9e/src/platform.ts#L147

Can you add verbose logging?

**Comment by xixihahajeff** [comment]
Apologies, what does verbose logging mean? How I do that in my iOS devices?

**Comment by schliemann** [comment]
@xixihahajeff You set it on your on the device running the plugin through homebridge.

**Comment by xixihahajeff** [comment]
I have tried all 3 modes for detailed logging (normal, debug, insane). Is that what you meant about verbose logging? Unfortunately, devices are still not showing up.

**Comment by xixihahajeff** [comment]
The log is as follows:

/12/2021, 11:41:48 PMEufy Security Bridge starting
26/12/2021, 11:41:59 PMEufy Security BridgeLoaded plugin 'homebridge-eufy-security'
26/12/2021, 11:41:59 PMEufy Security BridgeLoading 1 platforms...
26/12/2021, 11:41:59 PMEufy Security BridgeEufySecurityFinished initializing Eufy Security Platform
26/12/2021, 11:41:59 PMEufy Security BridgeBridge is running on port 51876.
26/12/2021, 11:42:01 PMEufy Security BridgeEufySecurityERRORNot connected can't continue!
26/12/2021, 11:42:25 PMEufy Security BridgeConfiguration change
26/12/2021, 11:42:25 PMeufysecuritybridge stopping
26/12/2021, 11:42:31 PMEufy Security Bridge starting
26/12/2021, 11:42:42 PMEufy Security BridgeLoaded plugin 'homebridge-eufy-security'
26/12/2021, 11:42:42 PMEufy Security BridgeLoading 1 platforms...
26/12/2021, 11:42:43 PMEufy Security BridgeBridge is running on port 51876.
26/12/2021, 11:43:55 PMeufysecuritybridge stopping
26/12/2021, 11:44:01 PMEufy Security Bridge starting
26/12/2021, 11:44:12 PMEufy Security BridgeLoaded plugin 'homebridge-eufy-security'
26/12/2021, 11:44:12 PMEufy Security BridgeLoading 1 platforms...
26/12/2021, 11:44:12 PMEufy Security BridgeBridge is running on port 51876.

**Comment by xixihahajeff** [comment]
Thank you for the time to respond.
I have resolved the problem by creating a new Eufy guest account. 
Cheers.
