### ISSUE TITLE
[enhancement]: Push alarm status back to Homekit

### ISSUE THREAD

**Issue by terrorhai** [samemory/homebridge-eufy-security#306]
### Describe the solution you'd like

I use the Indoor Pan & Tilt Camera (I think it's called P24 now) and use it in Homekit mode. Alarm is possible to activate/deactivate in Homekit and will trigger a device alarm, if set to on. But unlike my Aqara Homebase (which has an alarm mode too) Homekit won't recognise the alarm from the camera and I get no Information in Homekit. Is this a known problem or do we need to investigate further?
Thx in advance!

**Comment by schliemann** [comment]
The pan and tilt doesn't use the alarm system of the station as I remember. I am unsure how bropat supports alarm settings for non homebase driven security.

**Comment by schliemann** [comment]
@terrorhai 

But I suggest you ask him in the eufy-security-client github.
