### ISSUE TITLE
[Bug]: hkOff not Used

### ISSUE THREAD

**Issue by jonwestfall** [samemory/homebridge-eufy-security#309]
### What happened?

I'm using the configuration below. However when I toggle to "Off" in HomeKit, it sets to 63 (the default), not 6.

        {
            "platform": "EufySecurity",
            "username": "EMAIL",
            "password": "PASSWORD",
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 6,
            "enableDetailedLogging": 1,
            "ignoreStations": [],
            "ignoreDevices": []
        }

With that configuration, setting to "Off" in HomeKit shows the following in the log:

[12/28/2021, 9:38:23 PM] [EufySecurity-1.0.8] DEBUG: Homebase SET StationGuardMode: 63
[12/28/2021, 9:38:24 PM] [EufySecurity-1.0.8] DEBUG: Homebase ON SecuritySystemCurrentState: 63
[12/28/2021, 9:38:24 PM] [EufySecurity-1.0.8] DEBUG: Homebase ON SecurityGuardMode: 63

### Device Type

Station (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Docker (UnSupported)

**Comment by schliemann** [comment]
Please re-test. Works on my end.

**Comment by jonwestfall** [comment]
Still is setting to 63 and not 6. I tried setting hkOff to 3 for testing, and can verify that it did set it to "Night" mode when I set it to Off.  Is there anything else I can try to troubleshoot?

**Comment by schliemann** [comment]
What version are you on?

**Comment by lenoxys** [comment]
this is only available only on beta

**Comment by jonwestfall** [comment]
Can confirm that it only works in Beta. Upgraded from stable to beta, and works as expected.

**Comment by lenoxys** [comment]
thanks for your feedback we will merge beta into stable soon
