### ISSUE TITLE
Doorbell camera not showing live footage

### ISSUE THREAD

**Issue by jasonwfrancis1** [samemory/homebridge-eufy-security#31]
When the camera does load a stream it is not showing live footage. Currently the stream on my phone always loads a motion event that occured at 12:15, it is currently 12:29.

**Comment by jasonwfrancis1** [comment]
13/06/2021, 12:36:36 [HOOBS 1CBA@HomeKit Camera Active] The write handler for the characteristic 'HomeKit Camera Active' on the accessory 'Front Door' didn't respond at all!. Please check that you properly call the callback!
13/06/2021, 12:36:36 [HOOBS 1CBA@Event Snapshots Active] The write handler for the characteristic 'Event Snapshots Active' on the accessory 'Front Door' didn't respond at all!. Please check that you properly call the callback!

**Comment by jasonwfrancis1** [comment]
{"name":"eufyLog","hostname":"hoobs","pid":15475,"level":50,"msg":"Error: Error: read ETIMEDOUT\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {\n  errno: -110,\n  code: 'ETIMEDOUT',\n  syscall: 'read'\n}","time":"2021-06-13T11:39:45.236Z","v":0}

**Comment by samemory** [comment]
Hi @jasonwfrancis1, I just started a new [discussion ](https://github.com/samemory/homebridge-eufy-security/discussions/32) to help diagnose the doorbell. Can you add a comment with your current info and problems?

**Comment by schliemann** [comment]
Please test again with the newest version of the plugin.

**Comment by schliemann** [comment]
@jasonwfrancis1 Please re-test.
