### ISSUE TITLE
[Bug]: Found 0 stations - Found 0 devices

### ISSUE THREAD

**Issue by khj24** [samemory/homebridge-eufy-security#310]
### What happened?

Trying to add this plugin to my Homebridge. It seems like it authenticates correctly with the newly created guest/family user with admin rights, but it finds 0 stations and 0 devices. 

If I login to https://mysecurity.eufylife.com/ with the same credentials as used in this plugin, it shows the doorbell.

Help! Why won't the plugin find the doorbell?

Other notes:
I have other homebridge plugins running, like Philips Hue which works like a charm.

I have also tried another Eufy security plugin by birkir, it finds the Uefy battery doorbell, but that plugin seems to have other issues.

### Device Type

Doorbell (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Docker (UnSupported)

### Relevant log output

```shell
[12/29/2021, 11:52:26 AM] [EufySecurity] Initializing EufySecurity platform...
[12/29/2021, 11:52:26 AM] [EufySecurity-1.0.8] INFO:  Eufy Security Plugin: enableDetailedLogging on
[12/29/2021, 11:52:26 AM] [EufySecurity-1.0.8] INFO:  Finished initializing Eufy Security Platform
[12/29/2021, 11:52:26 AM] [EufySecurity-1.0.8] DEBUG: discoveringDevices
[12/29/2021, 11:52:26 AM] [EufySecurity-1.0.8] DEBUG: EufyClient connected true
[12/29/2021, 11:52:26 AM] [EufySecurity-1.0.8] DEBUG: PollingInterval: 30
[12/29/2021, 11:52:26 AM] [EufySecurity-1.0.8] DEBUG: Refresh data from cloud and schedule next refresh.
[12/29/2021, 11:52:27 AM] [EufySecurity-1.0.8] DEBUG: Found 0 stations.
[12/29/2021, 11:52:27 AM] [EufySecurity-1.0.8] DEBUG: Found 0 devices.
```

**Comment by schliemann** [comment]
Which devices do you have?

**Comment by khj24** [comment]
> Which devices do you have?

I have the HomeBase 2 and T8210 Wireless Battery Doorbell.

**Comment by schliemann** [comment]
Have you disabled 2FA?

**Comment by khj24** [comment]
Yes, didn't change a thing 👎

**Comment by khj24** [comment]
Do the plugin determine which cloud to use by the login credentials or is it "hardcoded" to use the US cloud? Since I live in EU, GDPR rules and all, I most likely have 0 devices in the US cloud? Just a thought of mine..

**Comment by schliemann** [comment]
Our plugin hardcodes the country to US. I live in the EU. And I don't have problems discovering devices.

**Comment by khj24** [comment]
Maybe Eufy changed procedure because of GDPR? Anyway that I can check if my devices are discoverable by the US cloud? Or a way to change the plugin to connect to EU cloud?

**Comment by schliemann** [comment]
You can try to change the platform.js file on your homebridge.

**Comment by khj24** [comment]
It works! I've changed the country code to DK and suddenly the devices showes up :-)

**Comment by schliemann** [comment]
@lenoxys 

Great. We should probably have this as a pr with country through the config.

**Comment by lenoxys** [comment]
> @lenoxys 
> 
> 
> 
> Great. We should probably have this as a pr with country through the config.

Ok

**Comment by Mikez20** [comment]
> It works! I've changed the country code to DK and suddenly the devices showes up :-)

Could you share how you changed the country code

**Comment by schliemann** [comment]
In the platform.js file. It is not configurable in 1.0.8 or beta.

**Comment by schliemann** [comment]
I asked Bropat if it actually makes a difference

https://github.com/bropat/eufy-security-client/issues/92

**Comment by Mikez20** [comment]
> I asked Bropat if it actually makes a difference
> 
> [bropat/eufy-security-client#92](https://github.com/bropat/eufy-security-client/issues/92)

Check, thnx. I seem to have the same problem that Homebridge doesn't discover any device in the Homebridge Eufy Security plugin. Any idea?

**Comment by schliemann** [comment]
You could try and set the country code to your country in the platform.js file.

**Comment by Mikez20** [comment]
Yes, but I am new to the Homebridge community and have no idea how to do that.

**Comment by fullphat** [comment]
If you launch a Terminal session and navigate to where the Eufy plugin is installed, you can edit the platform.js file.  Try this:

`nano platform.js`

Navigate to line 95 or thereabouts and change the US in this line to your country code:

`country: 'US',`

To quit nano press CTRL+X, type "Y" and hit enter.

**Comment by Mikez20** [comment]
Thnx for your advice, but could you give a hint where I can find the Eufy plugin? I have been browsing the directory's, but can't find anything that looks like the Eufy plugin. The nano platform.js command works because it starts a editor, but no code is displayed.

**Comment by fullphat** [comment]
Yes, it can be hard to find!

Mine is in /use/local/lib/node_modules

To find it, do "where HomeBridge", navigate to that folder, then do "ls -l" and look for the HomeBridge entry, which will probably be a link to another location.  Navigate there an you should be in the right place.

Post back here if you get stuck.

**Comment by lenoxys** [comment]
can you try the latest beta? I've added the ability to select the country within the settings menu.

**Comment by Mikez20** [comment]
> can you try the latest beta? I've added the ability to select the country within the settings menu.

Check. Just loaded the beta and changed the country code. Eufy doorbell cam still doesn't show up.

**Comment by schliemann** [comment]
> > can you try the latest beta? I've added the ability to select the country within the settings menu.
> 
> Check. Just loaded the beta and changed the country code. Eufy doorbell cam still doesn't show up.

And you set the country code?

**Comment by Mikez20** [comment]
> Yes, it can be hard to find!
> 
> Mine is in `/usr/local/lib/node_modules/`
> 
> To find the plugin folder on your system, do:
> 
> `where HomeBridge`
> 
> navigate to that folder, then do:
> 
> `ls -l`
> 
> and look for the `HomeBridge` entry, which will probably be a link to another location. Navigate there and you should be in the right place.
> 
> Post back here if you get stuck.

Thnx. Yes, that is the place where my plugins are. But now nano platform.js doesn't show any code:

pi@homebridge:/usr/local/lib/node_modules $ ls -l
total 32
drwxr-xr-x 4 root root 4096 Dec  1 19:08 corepack
drwxr-xr-x 3 root root 4096 Dec 12 09:50 @homebridge
drwxr-xr-x 5 root root 4096 Dec 31 14:47 homebridge
drwxr-xr-x 5 root root 4096 Dec 31 13:59 homebridge-config-ui-x
drwxr-xr-x 6 root root 4096 Jan  3 14:40 homebridge-eufy-security
drwxr-xr-x 3 root root 4096 Jan  1 18:24 homebridge-http-curtain
drwxr-xr-x 4 root root 4096 Dec 31 14:21 homebridge-nest
drwxr-xr-x 7 root root 4096 Dec 12 09:48 npm
pi@homebridge:/usr/local/lib/node_modules $ nano platform.js
pi@homebridge:/usr/local/lib/node_modules $ 

What am I missing?

**Comment by Mikez20** [comment]
> > > can you try the latest beta? I've added the ability to select the country within the settings menu.
> > 
> > 
> > Check. Just loaded the beta and changed the country code. Eufy doorbell cam still doesn't show up.
> 
> And you set the country code?

Yep. Absolutely and it was accepted.

**Comment by schliemann** [comment]
> 

You should navigate into homebridge-eufy-security

cd homebridge-eufy-security

**Comment by schliemann** [comment]
> > Yes, it can be hard to find!
> > Mine is in `/usr/local/lib/node_modules/`
> > To find the plugin folder on your system, do:
> > `where HomeBridge`
> > navigate to that folder, then do:
> > `ls -l`
> > and look for the `HomeBridge` entry, which will probably be a link to another location. Navigate there and you should be in the right place.
> > Post back here if you get stuck.
> 
> Thnx. Yes, that is the place where my plugins are. But now nano platform.js doesn't show any code:
> 
> pi@homebridge:/usr/local/lib/node_modules $ ls -l total 32 drwxr-xr-x 4 root root 4096 Dec 1 19:08 corepack drwxr-xr-x 3 root root 4096 Dec 12 09:50 @homebridge drwxr-xr-x 5 root root 4096 Dec 31 14:47 homebridge drwxr-xr-x 5 root root 4096 Dec 31 13:59 homebridge-config-ui-x drwxr-xr-x 6 root root 4096 Jan 3 14:40 homebridge-eufy-security drwxr-xr-x 3 root root 4096 Jan 1 18:24 homebridge-http-curtain drwxr-xr-x 4 root root 4096 Dec 31 14:21 homebridge-nest drwxr-xr-x 7 root root 4096 Dec 12 09:48 npm pi@homebridge:/usr/local/lib/node_modules $ nano platform.js pi@homebridge:/usr/local/lib/node_modules $
> 
> What am I missing?

You should navigate into homebridge-eufy-security

cd homebridge-eufy-security

**Comment by Mikez20** [comment]
> 

Yep. Thats what I thought. So I tried that, but still no code shows up when I do nano platform.js

**Comment by Mikez20** [comment]
> > > > can you try the latest beta? I've added the ability to select the country within the settings menu.
> > > 
> > > 
> > > Check. Just loaded the beta and changed the country code. Eufy doorbell cam still doesn't show up.
> > 
> > 
> > And you set the country code?
> 
> Yep. Absolutely and it was accepted.

Hhhmmmm, just checked the startup log and country still says US. So I afraid it works in the UI but is still not set right in the code.

**Comment by fullphat** [comment]
> > 
> 
> 
> 
> Yep. Thats what I thought. So I tried that, but still no code shows up when I do nano platform.js

Once you're in that folder, navigate to "dist" - it should be in there.

**Comment by lenoxys** [comment]
> > > 
> > 
> > 
> > Yep. Thats what I thought. So I tried that, but still no code shows up when I do nano platform.js
> 
> Once you're in that folder, navigate to "dist" - it should be in there.

I've removed the static value from the beta so it's based on the config now

**Comment by lenoxys** [comment]
> > can you try the latest beta? I've added the ability to select the country within the settings menu.
> 
> Check. Just loaded the beta and changed the country code. Eufy doorbell cam still doesn't show up.

Can you send me yours full logs ? eufy-plugin@secugrator.com

**Comment by Mikez20** [comment]
> > > can you try the latest beta? I've added the ability to select the country within the settings menu.
> > 
> > 
> > Check. Just loaded the beta and changed the country code. Eufy doorbell cam still doesn't show up.
> 
> Can you do the wizard again and send me yours full logs ? [eufy-plugin@secugrator.com](mailto:eufy-plugin@secugrator.com)

Just send you the logfile.

**Comment by Mikez20** [comment]
> 

Yep, thats it. There it is. But now I can't change the country setting because I have no permission. Is there a solution for that?

**Comment by lenoxys** [comment]
> Yep, thats it. There it is. But now I can't change the country setting because I have no permission. Is there a solution for that?

can you clear the cache of your browser for me it's working?
which browser are you using ?

**Comment by lenoxys** [comment]
> Yep, thats it. There it is. But now I can't change the country setting because I have no permission. Is there a solution for that?

looks like browser issue : works on chrome but not on safari

**Comment by Mikez20** [comment]
Sorry, just tried chrome but I keep getting the warning that platform.js is unwritable. I can find the country setting in the code and I can overwrite it, but I can't save it.

**Comment by fullphat** [comment]
Try:

`sudo nano platform.js`

I'm surprised you'd need root permissions, but it's worth a try.

**Comment by Mikez20** [comment]
Aha, that was it. Now I could change the code and set country to NL. Unfortunately Homebridge is still not seeing my Eufy doorbell. After restarting Homebridge this is what the log says:

[04/01/2022, 16:55:07] [homebridge-eufy-security] Country set: NL

So it looks like that is oke now.

**Comment by schliemann** [comment]
> Could try "DK" - that seemed to work for someone else on here.
> 
> However, I'm in the U.K. and I've never changed my country code so I'm not sure this is the cause of your issue.

I live in DK and having US as country has always worked.

**Comment by lenoxys** [comment]
there is something wrong with your install, we shouldn't edit file using sudo not safe at all.

**Comment by lenoxys** [comment]
> > Could try "DK" - that seemed to work for someone else on here.
> > However, I'm in the U.K. and I've never changed my country code so I'm not sure this is the cause of your issue.
> 
> I live in DK and having US as country has always worked.

Sometimes to see devices shared by other during troubleshooting I had to change the country but it's a matter of being part of Americas, Europe, Middle-east, Africa, Japan, APAC. Dunno when it's needed and when it's not.

**Comment by Mikez20** [comment]
I'll try DK and see what happens.

**Comment by Mikez20** [comment]
No luck with the DK setting. I've been looking at the log file myself and it looks like somehow underwater there is still the US setting. Enclosed a piece of the log after I changed country setting in the code to NL (line 46). Immediately after restarting Homebridge the log says that country is US and there are no devices found (line 2 and on). Thats weird, right?

[homebridge.log.txt](https://github.com/samemory/homebridge-eufy-security/files/7811277/homebridge.log.txt)

**Comment by lenoxys** [comment]
> No luck with the DK setting. I've been looking at the log file myself and it looks like somehow underwater there is still the US setting. Enclosed a piece of the log after I changed country setting in the code to NL (line 46). Immediately after restarting Homebridge the log says that country is US and there are no devices found (line 2 and on). Thats weird, right?
> 
> [homebridge.log.txt](https://github.com/samemory/homebridge-eufy-security/files/7811277/homebridge.log.txt)

can you clear the cache of your browser ? Looks like the js script is the old one.

**Comment by Mikez20** [comment]
Hhhmmm, clearing the cache solved a lot of problems with de Nest plugin and after restarting homebridge all log entry's say NL. So it seems you where right, there was something hanging in the cache. I do see a new log entry popup. 15 min. after restarting homebridge I now get the message "Push Closed!" (in orange colour). I never seen that before. During startup I see a INFO log entry that states "Push notification connection successfully established". I don't know how important this function is. 

Next to that homebridge-eufy-security is still not learning any devices.

**Comment by Mikez20** [comment]
I saw in earlier posts that 2FA might have something to do with not seeing devices. So I activated 2FA, but no result. Does anybody have an other idea?

**Comment by schliemann** [comment]
@Mikez20 please try and set enabledetailedlogging to 2 and provide the complete log.

**Comment by Mikez20** [comment]
@schliemann, First of all thnx for your patience and sticking with me in my surge for the problem. I think I managed to get the log you asked for. Let me know if you can read the file and what your findings are.

[homebridge.log 09012022.txt](https://github.com/samemory/homebridge-eufy-security/files/7835981/homebridge.log.09012022.txt)

**Comment by schliemann** [comment]
@Mikez20 It's difficult to say. We don't quite know why some peoples installations have problems finding devices.

**Comment by Mikez20** [comment]
> @Mikez20 It's difficult to say. We don't quite know why some peoples installations have problems finding devices.

Check. So I assume you don't see any strange entries in the logfile? Maybe a total power down and reboot of the Raspberry PI or a reinstall of Homebridge will help. That is something I didn't try yet.

**Comment by cracyfloyd** [comment]
> US

Hi all. Iam life in DE. So it doesnt work at all after i changed my password.  the adapter shows no devices. but what ive found out is, that on all my other devices like iphone, ipad comes after that i changed my password one time a captcha that i must fill out. maybe this is the problem. before i changed my password all worked.   Grrrrrr..... if i try another country code comes an unauthorized message in the log.... The same problem is in IOBroker too and its new...

**Comment by schliemann** [comment]
@cracyfloyd Have you created a separate guest account with admin rights?

**Comment by cracyfloyd** [comment]
> @cracyfloyd Have you created a separate guest account with admin rights?

No i dont do it. i use the main account..

**Comment by schliemann** [comment]
You shouldn't. Guest account with admin rights is necessary.

**Comment by cracyfloyd** [comment]
Ok. i have do and it runs now in IOBroker. THNX. But not in Homebridge. I receive follow errors.:[15/01/2022, 14:01:41] [homebridge-eufy-security] Not connected can't continue!
[15/01/2022, 14:02:14] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /request-otp
[15/01/2022, 14:02:14] [Homebridge UI] [homebridge-eufy-security] [1.1.1-beta.14] INFO:  country: DE
[15/01/2022, 14:02:14] [Homebridge UI] [homebridge-eufy-security] [1.1.1-beta.14] INFO:  Authentication properties changed, invalidate saved cloud token.
[15/01/2022, 14:02:15] [Homebridge UI] [homebridge-eufy-security] [1.1.1-beta.14] INFO:  Wrong username and/or password
[15/01/2022, 14:02:43] [Homebridge UI] Changes to config.json saved.
[15/01/2022, 14:02:44] [Homebridge UI] [homebridge-eufy-security] Terminating child process...
[15/01/2022, 14:02:44] [Homebridge UI] [homebridge-eufy-security] Child process ended


and i am sure thats the right password..

**Comment by schliemann** [comment]
Try and clear your cache in homebridge.

**Comment by cracyfloyd** [comment]
I have restored now a backup. Now it works. Thx first. But it is realy complicated. And i dont understand some why and why and why..
But many thnx ...

**Comment by schliemann** [comment]
@cracyfloyd What does "restored a backup" mean?

**Comment by cracyfloyd** [comment]
> @cracyfloyd What does "restored a backup" mean?

Before i tested something, i have made a backup with the status, before playing with homebridge. And this backup i have restored. i dont know exactly what i have do and try  before i contact you, i have  try so much to get it to run.

**Comment by schliemann** [comment]
Ok. Just glad it works now.
