### ISSUE TITLE
[enhancement]: WIFI DOOR LOCK WIFI BRIDGE

### ISSUE THREAD

**Issue by mshaka7x** [samemory/homebridge-eufy-security#314]
### Describe the solution you'd like

Hi. Thanks for this service. I am attempting to use my Eufy wifi door locks in homebridge. I see the door locks and the wifi bridges in homebridge but I can't control them. They are showing as unlocked. How can I control these locks in my Home app using homebridge?

**Comment by mshaka7x** [comment]
Yes I see nothing on that link in reference to door locks
Thank you,
Shaka

**Comment by mshaka7x** [comment]
> Did you check this [Road Map](https://github.com/samemory/homebridge-eufy-security/projects/4) pages ?

**Comment by schliemann** [comment]
Duplicate of https://github.com/samemory/homebridge-eufy-security/issues/281
