### ISSUE TITLE
[Bug]: no video issues

### ISSUE THREAD

**Issue by singas77** [samemory/homebridge-eufy-security#318]
### What happened?

[1/1/2022, 4:37:00 PM] [EufySecurity] Starting video stream: 1280 x 720, 30 fps, 299 kbps (AAC-eld) Front Doorbell
[1/1/2022, 4:37:03 PM] [EufySecurity] Getting the first frames took 5.709 seconds. Front Doorbell
[1/1/2022, 4:37:05 PM] [EufySecurity] Getting the first frames took 5.039 seconds. Front Doorbell
[1/1/2022, 4:37:06 PM] [EufySecurity] Stopped video stream. Front Doorbell
[1/1/2022, 4:37:27 PM] [EufySecurity] Stopped video stream. Front Doorbell
[1/1/2022, 4:37:28 PM] [EufySecurity] Starting video stream: 1920 x 1080, 30 fps, 802 kbps (AAC-eld) Front Doorbell
[1/1/2022, 4:37:36 PM] [EufySecurity] Stopped video stream. Front Doorbell
[1/1/2022, 4:37:55 PM] [EufySecurity] Starting video stream: 1280 x 720, 30 fps, 299 kbps (AAC-eld) Front Doorbell
[1/1/2022, 4:37:56 PM] [EufySecurity] Stopped video stream. Front Doorbell

### Device Type

Doorbell (Supported)

### Plugin Version

v0.2.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

other (UnSupported)

### Operating System

Mac OS X 11+ (Supported)

### Relevant log output

```shell
[1/1/2022, 4:37:00 PM] [EufySecurity] Starting video stream: 1280 x 720, 30 fps, 299 kbps (AAC-eld) Front Doorbell
[1/1/2022, 4:37:03 PM] [EufySecurity] Getting the first frames took 5.709 seconds. Front Doorbell
[1/1/2022, 4:37:05 PM] [EufySecurity] Getting the first frames took 5.039 seconds. Front Doorbell
[1/1/2022, 4:37:06 PM] [EufySecurity] Stopped video stream. Front Doorbell
[1/1/2022, 4:37:27 PM] [EufySecurity] Stopped video stream. Front Doorbell
[1/1/2022, 4:37:28 PM] [EufySecurity] Starting video stream: 1920 x 1080, 30 fps, 802 kbps (AAC-eld) Front Doorbell
[1/1/2022, 4:37:36 PM] [EufySecurity] Stopped video stream. Front Doorbell
[1/1/2022, 4:37:55 PM] [EufySecurity] Starting video stream: 1280 x 720, 30 fps, 299 kbps (AAC-eld) Front Doorbell
[1/1/2022, 4:37:56 PM] [EufySecurity] Stopped video stream. Front Doorbell
```

**Comment by singas77** [comment]
that's correct even installed ffmpeg in home bridge and macOS

**Comment by schliemann** [comment]
And the ffmpeg binary is in the ffmpeg-for-homebridge folder?

**Comment by singas77** [comment]
I believe so 
I have folder in ~/.homebridge for FFmpeg

**Comment by singas77** [comment]
[1/1/2022, 7:28:12 PM] [EufySecurity] Starting video stream: 1280 x 720, 30 fps, 299 kbps (AAC-eld) Front Doorbell
[1/1/2022, 7:28:12 PM] [EufySecurity] Stopped video stream. Front Doorbell

**Comment by schliemann** [comment]
What version are you using?

**Comment by singas77** [comment]
I’m using the latest update homebridge plugin and from ffmpeg.org I grabbed the latest also

**Comment by singas77** [comment]
Has anyone run this with out installing ffmpeg ?

**Comment by fullphat** [comment]
> Has anyone run this with out installing ffmpeg ? 

Yes.  I was going to install ffmpeg, but macOS complained about it not being trusted so I reverted to the version that ships with the plugin.  I had the change the video codec to "copy" and then it worked fine for me.

**Comment by singas77** [comment]
I’ll check that out cheers

**Comment by singas77** [comment]
> > Has anyone run this with out installing ffmpeg ?
> 
> Yes. I was going to install ffmpeg, but macOS complained about it not being trusted so I reverted to the version that ships with the plugin. I had to change the video codec to "copy" and then it worked fine for me.

further instruction please

**Comment by singas77** [comment]
I can not get this working at all 👎 


<img width="1115" alt="Screen Shot 2022-01-04 at 13 20 23" src="https://user-images.githubusercontent.com/76757004/148012995-ba9618c2-f627-4f01-833b-e9bf167ca4da.png">

**Comment by singas77** [comment]
tried ffmpeg reinstall tried the codec = copy nothing working for me macOS home bridge

**Comment by schliemann** [comment]
I have installed the ffmpeg plugin. Will send the installation command later when at a pc.

**Comment by schliemann** [comment]
Please also provide your logs.

**Comment by singas77** [comment]
I won't have any logs now done full uninstall / delete of all associated home bridge and reinstall 
funny thing when full uninstall everything stayed in HomeKit app Eufy_Homebase and camera

**Comment by schliemann** [comment]
Ok. So you don't need any help?

**Comment by singas77** [comment]
oh I need some help I would love this to work

**Comment by singas77** [comment]
> Ok. So you don't need any help?

<img width="1161" alt="Screen Shot 2022-01-04 at 15 24 07" src="https://user-images.githubusercontent.com/76757004/148023633-967981e7-90cb-4a2e-a46c-4705ea7d1c10.png">

**Comment by singas77** [comment]
\

> Ok. So you don't need any help?

[homebridge.log.txt](https://github.com/samemory/homebridge-eufy-security/files/7805997/homebridge.log.txt)

**Comment by schliemann** [comment]
Can you set enableDetailedLogging to 2?

**Comment by singas77** [comment]
[homebridge.log.txt](https://github.com/samemory/homebridge-eufy-security/files/7806143/homebridge.log.txt)

**Comment by schliemann** [comment]
Also. I could only get ffmpeg to install the binary by running npm install --unsafe-perm ffmpeg-for-homebridge in the plugin folder.

**Comment by singas77** [comment]
I used home-brew 
brew install ffmpeg

**Comment by singas77** [comment]
> Also. I could only get ffmpeg to install the binary by running npm install --unsafe-perm ffmpeg-for-homebridge in the plugin folder.

so you have doorbell video stream working?

**Comment by schliemann** [comment]
You can try this https://github.com/samemory/homebridge-eufy-security/issues/313#issuecomment-1002976535

**Comment by singas77** [comment]
![Uploading Screen Shot 2022-01-04 at 15.24.07.png…]()

**Comment by singas77** [comment]
> You can try this [#313 (comment)](https://github.com/samemory/homebridge-eufy-security/issues/313#issuecomment-1002976535)
I have done that also

**Comment by singas77** [comment]
<img width="1161" alt="Screen Shot 2022-01-04 at 15 24 07" src="https://user-images.githubusercontent.com/76757004/148027616-8640f61e-3513-4cb8-bd36-628514f5af76.png">

**Comment by singas77** [comment]
<img width="1115" alt="148012995-ba9618c2-f627-4f01-833b-e9bf167ca4da" src="https://user-images.githubusercontent.com/76757004/148027711-e04870f4-70a8-4e30-a69c-f05beff5ffd1.png">

**Comment by schliemann** [comment]
The plugin uses ffmpeg-for-homebridge. Pretty sure you will experience issues if you use vanilla ffmpeg.

**Comment by singas77** [comment]
> You can try this [#313 (comment)](https://github.com/samemory/homebridge-eufy-security/issues/313#issuecomment-1002976535)
> I have done that also

can you please confirm if it is ffmpeg issue

**Comment by singas77** [comment]
> The plugin uses ffmpeg-for-homebridge. Pretty sure you will experience issues if you use vanilla ffmpeg.

so it is ffmpeg trouble;es

**Comment by singas77** [comment]
[Uploading homebridge.log-2.txt…]()

**Comment by schliemann** [comment]
@singas77 Can't read your last log.

**Comment by singas77** [comment]
[homebridge.log-2.txt](https://github.com/samemory/homebridge-eufy-security/files/7806339/homebridge.log-2.txt)

**Comment by schliemann** [comment]
I think that's the log you have attached a couple of times before.

**Comment by singas77** [comment]
what you want another

**Comment by singas77** [comment]
> I think that's the log you have attached a couple of times before.

there's 2 one is more than the first can you see any issues thou

**Comment by singas77** [comment]
> I think that's the log you have attached a couple of times before.

try this debug mode 2 
[homebridge.log-3.txt](https://github.com/samemory/homebridge-eufy-security/files/7806999/homebridge.log-3.txt)

**Comment by schliemann** [comment]
Very odd that there is no error log when the streaming crashes.

**Comment by singas77** [comment]
> Very odd that there is no error log when the streaming crashes.

It's god dam anoyying got any advice

**Comment by schliemann** [comment]
Are you on 1.0.8 or beta?

**Comment by singas77** [comment]
v1.0.8  and HB v1.3.9 nom v8 node.js v16 macos monterey

**Comment by singas77** [comment]
> The plugin uses ffmpeg-for-homebridge. Pretty sure you will experience issues if you use vanilla ffmpeg.

Is that the actual ffmpeg-for-homebridge I don't have that installed what's the config

**Comment by singas77** [comment]
Like the hb plug in or ffmpeg codec

**Comment by lenoxys** [comment]
can you test on beta ? https://github.com/samemory/homebridge-eufy-security/wiki/Beta-Version

**Comment by singas77** [comment]
> can you test on beta ? https://github.com/samemory/homebridge-eufy-security/wiki/Beta-Version

![Uploading Screen Shot 2022-01-04 at 23.21.00.png…]()

**Comment by singas77** [comment]
> can you test on beta ? https://github.com/samemory/homebridge-eufy-security/wiki/Beta-Version

[Uploading homebridge.log-4.txt…]()

**Comment by singas77** [comment]
[homebridge.log-4.txt](https://github.com/samemory/homebridge-eufy-security/files/7808608/homebridge.log-4.txt)

**Comment by singas77** [comment]
![Uploading Screen Shot 2022-01-04 at 23.21.00.png…]()

**Comment by singas77** [comment]
<img width="1193" alt="Screen Shot 2022-01-04 at 23 21 00" src="https://user-images.githubusercontent.com/76757004/148083912-59b8f760-031e-41e9-986b-69eadd728038.png">

**Comment by lenoxys** [comment]
can you provide access admin guest access to that account ? So I can confirm if it's related to your env or it's an issue with the plugin : eufy-plugin-test@secugrator.com

**Comment by singas77** [comment]
> can you provide access admin guest access to that account ? So I can confirm if it's related to your env or it's an issue with the plugin : [eufy-plugin-test@secugrator.com](mailto:eufy-plugin-test@secugrator.com)

any further info

**Comment by lenoxys** [comment]
Hum I did test but I wasn't able to make it work I do see device but when starting stream it doesn't work. I wasn't able to make it work on beta since HB need to be into the same network than the station or Eufy devices. 

You can remove my access and change your password.

**Comment by lenoxys** [comment]
Let us finish the 1.1.0 and will come back to you after that. Sorry to make you wait.

**Comment by singas77** [comment]
> Let us finish the 1.1.0 and will come back to you after that. Sorry to make you wait.

Thanks for your assist

**Comment by singas77** [comment]
> Let us finish the 1.1.0 and will come back to you after that. Sorry to make you wait.

I have news 
I've setup homebridge on a raspberry P4 instead of using mu iMac now and with HB v1.4.0b4 and homebridge-eufy-security v1.1.1-b13 I now have working live streaming and audio 👍🏿
