### ISSUE TITLE
[enhancement]: Keypad motion sensor and battery "switch" enhancements

### ISSUE THREAD

**Issue by Geek-MD** [samemory/homebridge-eufy-security#319]
### Describe the solution you'd like

Keypad has a built in motion sensor, I think it would be nice to add that sensor functionality.

Second, I can't find it useful to show battery level as a "switch". Other plugins like homebridge-eveatmo (https://github.com/skrollme/homebridge-eveatmo#readme) shows battery level as a percentage. Maybe you can look there how to implement it.

Thanks in advance

**Comment by schliemann** [comment]
1. The client library doesn't support keypad motion detected at the moment.
2. The client library only supports isBatteryLow(). So we can't provide a number.
You are welcome to create an issue here:

https://github.com/bropat/eufy-security-client/issues

![Uploading 0EF16580-115B-4A63-A8A7-6A21BB4BFB1D.png…]()

**Comment by Geek-MD** [comment]
Thanks a lot for your answer, done what you suggested

https://github.com/bropat/eufy-security-client/issues/93

**Comment by schliemann** [comment]
Let's keep this issue open for now then. Bropat is quite busy however and might not prioritize these changes. But lets see.

**Comment by schliemann** [comment]
Closing this after reading Bropats response.
