### ISSUE TITLE
[enhancement]: Add a config value to remove some buttons

### ISSUE THREAD

**Issue by sverspecht** [samemory/homebridge-eufy-security#320]
### Describe the solution you'd like

Hello,

Every night I ask to Siri to shut down every device in my house.

Unfortunately, doing this I also shut down my doorbell camera and motion! (I've missed some delivery with this :D)

Can it be possible to let us add a specific value to disable those buttons?

Regards,

Sébastien

<img width="836" alt="Capture d’écran 2022-01-03 à 01 27 47" src="https://user-images.githubusercontent.com/21987415/147893221-5a8a5dcb-dd07-4ec4-8d1d-db42ae92b748.png">

**Comment by lenoxys** [comment]
like the idea, I've put it on my todo list

**Comment by schliemann** [comment]
I think it is fine to do this. But I guess you could achieve the same by making an automation and just not include this.

Personally implemented the button to disable/enable cameras to protect my privacy.

**Comment by schliemann** [comment]
Do you have discord? Or another app. Sometimes easier to chat than github issues.

**Comment by Dulox24** [comment]
Would be a very nice option! I have the same thing, and a wife who just wants to click all to off xD So I would rather love to hide the switches!

**Comment by lenoxys** [comment]
done on latest beta. please check

**Comment by sverspecht** [comment]
Merci Aurélien ;)

Unfortunately, it doesn't work for me. I've updated my homebridge & node.js but still same behavior.
In my logs, I've a message saying that my hardware isn't compatible and then variables are ignored. 
I'll try to send a capture of this message.

**Comment by lenoxys** [comment]
You need to clean your browser cache then I've leave a note when disabling the button you need to clear accessory cache on the homebridge settings. Don't do the all but single one and select the camera. You need to do it again per camera.

**Comment by schliemann** [comment]
I can confirm that setting enableButton and motionButton to false removes the two switches.

**Comment by sverspecht** [comment]
Oups.. Sorry I've forget to confirm it to you.
Switches are correctly removed now. Thank you :)
