### ISSUE TITLE
[Bug]: Beta: error when exiting live stream

### ISSUE THREAD

**Issue by steverae68** [samemory/homebridge-eufy-security#325]
### What happened?

A bug happened!

when exiting live stream get this error in logs

### Device Type

Doorbell (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[09/01/2022.
curityl
Stopping session
id:
53946f0d-28be-4£7c-9e9f-15
975a019323
[09/01/2022
18:01:181
[EufySe
curity] Doorbell Eufy
Station
stopped the stream.
Stopping s
tream.
[09/01/2022, 18:01:181
[EufySe
curity]
Stopping session with
id: 53946£0d-28be-4f7c-9e9f-15
975a019323
[09/01/2022,
18:01:181 [EufySe
curityl
Doorbell Stopped
video
stream.
[09/01/2022,
18:01:181
[EufySe
curity] Doorbell Error
occurre
d
I closing socket: Error [ERR
S
OCKET GRAM NOT RUNNING]: Not
running
[09/01/2022,
18:01:181 [Eufyse
curity] Doorbell Stopped video
stream
[09/01/2022,
18:01:181 [EufySe
curity] Doorbell
audio [error]
unix:. /4.sock: No such file
O
I
directory
```

**Comment by steverae68** [comment]
The above bug does not appear to have any other effects on homebridge, this stays running fine and I can go back into live stream again without issue.
This is running on latest beta which is a huge improvement with local access for live stream

I have donated several times to this plugin, keep up the fantastic work

**Comment by schliemann** [comment]
This will be fixed in one of the other livestream issues. The livestream might be re-written a bit to also solve issue with permissions to current directory. I'm closing this one.
