### ISSUE TITLE
[Bug]: All Devices Exposed to HomeKit

### ISSUE THREAD

**Issue by tristanjmayer** [samemory/homebridge-eufy-security#331]
### What happened?

I’ve got several cameras in my account and in the advance area of the plug-in I have put in the devices to ignore but they are still being exposed to HomeKit

### Device Type

Station (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

**Comment by schliemann** [comment]
Can you show me your ignoreList?

**Comment by tristanjmayer** [comment]
> Can you show me your ignoreList?

{
    "bridge": {
        "name": "Homebridge ED23",
        "username": "",
        "port": 51090,
        "pin": ""
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "platform": "EufySecurity",
            "username": "",
            "password": "!",
            "enableCamera": true,
            "pollingIntervalMinutes": 3,
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 63,
            "enableDetailedLogging": 0,
            "ignoreStations": [
                "Cameras"
            ],
            "ignoreDevices": [
                "Driveway",
                "Backyard"
            ]
        }
    ]
}

**Comment by schliemann** [comment]
You need to write the serial number of the cameras.

**Comment by tristanjmayer** [comment]
> You need to write the serial number of the cameras.

That worked straight away, thank you so much! Maybe that could be added into the configuration page.
