### ISSUE TITLE
[Bug]: [EufySecurity] Not connected can't continue!

### ISSUE THREAD

**Issue by PaTri16** [samemory/homebridge-eufy-security#334]
### What happened?

I Installed the Plugin on Homebridge and do the Configuration. The message is ".... [EufySecurity] Not connected can't continue!". No Camera in HomeKit. Can someone help?

### Device Type

Indoor Camera (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v12 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
".... [EufySecurity] Not connected can't continue!"
```

**Comment by schliemann** [comment]
Can you set enabledetailedlogging to 2 and try again?

**Comment by Arejay03** [comment]
Same issue. Changed to 2 as suggested and solved the error, but locks are still not visible. 

Very noob to this, is there another step I've overlooked?

**Comment by lenoxys** [comment]
Could you test on latest beta .19 ?

**Comment by Arejay03** [comment]
Not sure how go about that, are there instructions anywhere?

**Comment by lenoxys** [comment]
> Not sure how go about that, are there instructions anywhere?

On GitHub wiki you have beta section
