### ISSUE TITLE
[Bug]:  WARNING:Doorbell fetchSnapshot: No Snapshot found

### ISSUE THREAD

**Issue by smelly3443** [samemory/homebridge-eufy-security#335]
### What happened?

When homekit tries to connect or update the snapshot, I get this warning error and the cam doesn't respond

### Device Type

Doorbell (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

other (UnSupported)

### NodeJS Version

other (UnSupported)

### Operating System

Mac OS X 11+ (Supported)

### Relevant log output

```shell
1/16/2022, 1:30:27 AM Eufy DoorBell Bridge eufydoorbellbridge stopping
1/16/2022, 1:30:32 AM Eufy DoorBell Bridge Eufy DoorBell Bridge starting
1/16/2022, 1:30:44 AM Eufy DoorBell Bridge Loaded plugin 'homebridge-eufy-security'
1/16/2022, 1:30:44 AM Eufy DoorBell Bridge [ DEBUG ] Registering platform 'homebridge-eufy-security.EufySecurity'
1/16/2022, 1:30:44 AM Eufy DoorBell Bridge Loading 1 platforms...
1/16/2022, 1:30:44 AM Eufy DoorBell Bridge EufySecurity Finished initializing Eufy Security Platform
1/16/2022, 1:30:44 AM Eufy DoorBell Bridge Bridge is running on port 51846.
1/16/2022, 1:31:01 AM Eufy DoorBell Bridge EufySecurity Restoring existing accessory from cache: eufy HomeBase2
1/16/2022, 1:31:01 AM Eufy DoorBell Bridge EufySecurity Restoring existing accessory from cache: Doorbell
1/16/2022, 1:31:02 AM Eufy DoorBell Bridge EufySecurity [ WARNING ] Push Closed!
1/16/2022, 1:31:48 AM Eufy DoorBell Bridge EufySecurity [ WARNING ] Doorbell fetchSnapshot: No Snapshot found
```

**Comment by schliemann** [comment]
Can you set enabledetailedlogging to 2 and try again?

**Comment by smelly3443** [comment]
1/16/2022, 1:30:44 AMEufy DoorBell BridgeLoaded plugin 'homebridge-eufy-security'
1/16/2022, 1:30:44 AMEufy DoorBell BridgeLoading 1 platforms...
1/16/2022, 1:30:44 AMEufy DoorBell BridgeEufySecurityFinished initializing Eufy Security Platform
1/16/2022, 1:30:44 AMEufy DoorBell BridgeBridge is running on port 51846.
1/16/2022, 1:31:01 AMEufy DoorBell BridgeEufySecurityRestoring existing accessory from cache: eufy HomeBase2
1/16/2022, 1:31:01 AMEufy DoorBell BridgeEufySecurityRestoring existing accessory from cache: Doorbell
1/16/2022, 1:31:02 AMEufy DoorBell BridgeEufySecurityWARNINGPush Closed!
1/16/2022, 1:31:48 AMEufy DoorBell BridgeEufySecurityWARNINGDoorbell fetchSnapshot: No Snapshot found
1/16/2022, 1:33:27 AMEufy DoorBell BridgeEufySecurityWARNINGDoorbell fetchSnapshot: No Snapshot found
1/16/2022, 1:33:32 AMEufy DoorBell BridgeERROR[Eufy DoorBell Bridge 72BD@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Doorbell' was slow to respond!
1/16/2022, 1:33:34 AMEufy DoorBell BridgeEufySecurityStarting video stream: 1280 x 720, 30 fps, 299 kbps (AAC-eld) Doorbell
1/16/2022, 1:33:59 AMEufy DoorBell BridgeEufySecurityStopped video stream. Doorbell
1/16/2022, 1:34:17 AMEufy DoorBell BridgeEufySecurityWARNINGDoorbell fetchSnapshot: No Snapshot found
1/16/2022, 1:34:21 AMEufy DoorBell BridgeEufySecurityStarting video stream: 1920 x 1080, 30 fps, 802 kbps (AAC-eld) Doorbell
1/16/2022, 1:35:00 AMEufy DoorBell BridgeEufySecurityStopped video stream. Doorbell
1/16/2022, 1:35:02 AMEufy DoorBell BridgeEufySecurityStarting video stream: 1920 x 1080, 30 fps, 802 kbps (AAC-eld) Doorbell
1/16/2022, 1:35:32 AMEufy DoorBell BridgeEufySecurityStopped video stream. Doorbell
1/16/2022, 1:35:33 AMEufy DoorBell BridgeEufySecurityStarting video stream: 1920 x 1080, 30 fps, 802 kbps (AAC-eld) Doorbell
1/16/2022, 1:36:03 AMEufy DoorBell BridgeEufySecurityStopped video stream. Doorbell
1/16/2022, 1:36:05 AMEufy DoorBell BridgeEufySecurityStarting video stream: 1920 x 1080, 30 fps, 802 kbps (AAC-eld) Doorbell
1/16/2022, 1:36:12 AMEufy DoorBell BridgeEufySecurityWARNINGGetting the first frames took 6.584 seconds. Doorbell
1/16/2022, 1:40:32 AMEufy DoorBell BridgeEufySecurityERRORFFmpeg exited with code: 0 and signal: null (Error) Doorbell
1/16/2022, 1:40:32 AMEufy DoorBell BridgeEufySecurityStopped video stream. Doorbell
1/16/2022, 1:41:00 AMEufy DoorBell BridgeEufySecurityStarting video stream: 1920 x 1080, 30 fps, 802 kbps (AAC-eld) Doorbell
1/16/2022, 1:42:16 AMEufy DoorBell BridgeEufySecurityStopped video stream. Doorbell
1/16/2022, 1:55:39 AMEufy DoorBell BridgeEufySecurityWARNINGDoorbell fetchSnapshot: No Snapshot found
1/16/2022, 10:04:25 AMEufy DoorBell BridgeEufySecurityStarting video stream: 320 x 240, 15 fps, 68 kbps (AAC-eld) Doorbell
1/16/2022, 10:04:33 AMEufy DoorBell BridgeEufySecurityWARNINGGetting the first frames took 8.051 seconds. Doorbell
1/16/2022, 10:04:54 AMEufy DoorBell BridgeEufySecurityWARNINGDoorbell fetchSnapshot: No Snapshot found
1/16/2022, 10:04:55 AMEufy DoorBell BridgeEufySecurityStopped video stream. Doorbell
1/16/2022, 10:05:37 AMEufy DoorBell BridgeEufySecurityWARNINGDoorbell fetchSnapshot: No Snapshot found
1/16/2022, 11:46:12 AMEufy DoorBell BridgeEufySecurityStarting video stream: 1280 x 720, 30 fps, 299 kbps (AAC-eld) Doorbell
1/16/2022, 11:46:42 AMEufy DoorBell BridgeEufySecurityStopped video stream. Doorbell
1/16/2022, 11:46:50 AMEufy DoorBell BridgeEufySecurityStarting video stream: 1280 x 720, 30 fps, 299 kbps (AAC-eld) Doorbell
1/16/2022, 11:46:57 AMEufy DoorBell BridgeEufySecurityWARNINGGetting the first frames took 7.278 seconds. Doorbell
1/16/2022, 11:47:34 AMEufy DoorBell BridgeEufySecurityStopped video stream. Doorbell
1/16/2022, 11:47:40 AMEufy DoorBell BridgeEufySecurityWARNINGDoorbell fetchSnapshot: No Snapshot found
1/16/2022, 1:17:56 PMEufy DoorBell BridgeBridge change
1/16/2022, 1:18:15 PMEufy DoorBell BridgeLoaded plugin 'homebridge-eufy-security'
1/16/2022, 1:18:16 PMEufy DoorBell BridgeLoading 1 platforms...
1/16/2022, 1:18:16 PMEufy DoorBell BridgeEufySecurityFinished initializing Eufy Security Platform
1/16/2022, 1:18:16 PMEufy DoorBell BridgeBridge is running on port 51846.
1/16/2022, 1:18:34 PMEufy DoorBell BridgeEufySecurityRestoring existing accessory from cache: eufy HomeBase2
1/16/2022, 1:18:34 PMEufy DoorBell BridgeEufySecurityRestoring existing accessory from cache: Doorbell
1/16/2022, 1:20:41 PMEufy DoorBell BridgeConfiguration change
1/16/2022, 1:20:59 PMEufy DoorBell BridgeLoaded plugin 'homebridge-eufy-security'
1/16/2022, 1:20:59 PMEufy DoorBell BridgeLoading 1 platforms...
1/16/2022, 1:21:00 PMEufy DoorBell BridgeBridge is running on port 51846.
1/16/2022, 1:24:53 PMEufy DoorBell BridgeERROR[Eufy DoorBell Bridge 72BD@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Doorbell' was slow to respond!
1/16/2022, 1:29:03 PMEufy DoorBell BridgeERROR[Eufy DoorBell Bridge 72BD@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Doorbell' was slow to respond!
1/16/2022, 1:30:21 PMEufy DoorBell BridgeERROR[Eufy DoorBell Bridge 72BD@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Doorbell' was slow to respond!
1/16/2022, 1:44:12 PMEufy DoorBell BridgeERROR[Eufy DoorBell Bridge 72BD@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Doorbell' was slow to respond!
