### ISSUE TITLE
Wrong password message (with correct password) [Bug]: 

### ISSUE THREAD

**Issue by StaX91** [samemory/homebridge-eufy-security#336]
### What happened?

A bug happened!

### Device Type

Doorbell (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Docker (UnSupported)

### Relevant log output

```shell
Doorbell used to work fine. Fews ago the screenshots stopped updating but i read this was an issue on the side of Eufy. But a few days ago the camera stopped working at all in HomeKit (works fine in Eufy app). 
I restarted HomeBridge and saw in the log that no connection to Eufy could be made. I tried to renew the settings but it keeps saying: Wrong username or password. Which I did not change. Changed the password and got the same message with the new one...
I litterally copy and paste the password which is says is incorrect and I CAN login with that password within the Eufy app and on the website.

It is however a GuestAccount (with all the rights), could that be the problem? I read somewhere over here that this is recommended. I do not want to use my main account with the risk of getting banned by Eufy... 

Please help!
```

**Comment by StaX91** [comment]
[1/21/2022, 7:27:57 PM] [Homebridge UI] [homebridge-eufy-security] [1.0.8] DEBUG: Response: {
  code: 100032,
  msg: 'Failed to request.',
  
  Piece of the log. I guess Eufy added an captch image as an additional security layer and you can't buypass this with the API?
  I tried with two factor off, same (incorrect) message that the username or password is wrong.

**Comment by schliemann** [comment]
Try and delete cached accessories in homebridge.

**Comment by StaX91** [comment]
> Try and delete cached accessories in homebridge.

Did not solve it :(

**Comment by schliemann** [comment]
Try another guest account and disable 2FA.

**Comment by StaX91** [comment]
This worked... Strangly enough. Fixed for now..

**Comment by schliemann** [comment]
Which part?

**Comment by StaX91** [comment]
I deleted old guest account, made a new one with another mail adres and disabled 2FA. Now it works...

**Comment by StaX91** [comment]
Thanks for quick replies!

**Comment by schliemann** [comment]
You're welcome. Glad it worked.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
