### ISSUE TITLE
[Bug]: Login failure - wrong username or password 

### ISSUE THREAD

**Issue by pelu89** [samemory/homebridge-eufy-security#338]
### What happened?

Hey, first time I installed the plug-in I had a typo in the security code that I got via email. After that I tried to restart the login process but the plug-in always rejects my credentials. I uninstalled the plug-in, changed my password. Nothing makes the plug-in accept my credentials. Any idea what the problem could be? 

### Device Type

Indoor Camera (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

**Comment by pelu89** [comment]
Yeah couldn't find that problem there

**Comment by schliemann** [comment]
Try and delete the guest and create it again.

**Comment by pelu89** [comment]
Already did. No changes.
Am 21. Jan. 2022, 22:44 +0100 schrieb schliemann ***@***.***>:

**Comment by schliemann** [comment]
Can you delete the cached accessories

**Comment by pelu89** [comment]
I hope I understand you correctly but I was not able to install any accessories through the plug-in.
Am 21. Jan. 2022, 22:47 +0100 schrieb schliemann ***@***.***>:

**Comment by dewoert** [comment]
I have same sort of problem with guest account.
In debug i now see : 
`[Homebridge UI] [homebridge-eufy-security] [1.0.8] DEBUG: Load previous login_hash: eb0081163ddb223ea32478cba06321ca`
`[Homebridge UI] [homebridge-eufy-security] [1.0.8] INFO:  Authentication properties changed, invalidate saved cloud token.`
`[Homebridge UI] [homebridge-eufy-security] [1.0.8] DEBUG: Authenticate and get an access token { token: null, tokenExpiration: null }`
`[Homebridge UI] [homebridge-eufy-security] [1.0.8] DEBUG: Response: {
  code: 100032,
  msg: 'Failed to request.',
  data: {
    captcha_id: '66467ce1-14eb-4db9-86b5-1f82533be513',
    item: 'data:image/png;base64.....................................................etc`
and:
`[Homebridge UI] [homebridge-eufy-security] [1.0.8] DEBUG: Captcha verification received {
  captchaId: '66467ce1-14eb-4db9-86b5-1f82533be513',
  item: 'data:image/png;base64,.................................. etc`
There's no cached accesories to deleted
Created a complete new account, same errors
Looks like an issue with Captcha ?

**Comment by jredondox** [comment]
i have the same issue :(

**Comment by dewoert** [comment]
> I have same sort of problem with guest account. In debug i now see : `[Homebridge UI] [homebridge-eufy-security] [1.0.8] DEBUG: Load previous login_hash: eb0081163ddb223ea32478cba06321ca` `[Homebridge UI] [homebridge-eufy-security] [1.0.8] INFO: Authentication properties changed, invalidate saved cloud token.` `[Homebridge UI] [homebridge-eufy-security] [1.0.8] DEBUG: Authenticate and get an access token { token: null, tokenExpiration: null }` `[Homebridge UI] [homebridge-eufy-security] [1.0.8] DEBUG: Response: { code: 100032, msg: 'Failed to request.', data: { captcha_id: '66467ce1-14eb-4db9-86b5-1f82533be513', item: 'data:image/png;base64.....................................................etc` and: `[Homebridge UI] [homebridge-eufy-security] [1.0.8] DEBUG: Captcha verification received { captchaId: '66467ce1-14eb-4db9-86b5-1f82533be513', item: 'data:image/png;base64,.................................. etc` There's no cached accesories to deleted Created a complete new account, same errors Looks like an issue with Captcha ?

Problem with the account seems to be resolved.
Can login now, without Captcha errors. 
Logged in on App and validated the Captcha, logged out again.
Next morning errors seems to have gone..

**Comment by schliemann** [comment]
@dewoert Try and delete cached for the plugin.

**Comment by dewoert** [comment]
Login is NO problem here anymore. After succesvol login from phone-App, the login is working now.
Biggest problem now is https://github.com/samemory/homebridge-eufy-security/issues/340 :(

**Comment by jredondox** [comment]
Mine is fixed as well… now we just need support for the new Wi-Fi lock :)

**Comment by schliemann** [comment]
Ok. So this is basically closed. Since the wifi lock and no devices are seperate issues?
