### ISSUE TITLE
[Bug]: No stations or devices found.

### ISSUE THREAD

**Issue by dewoert** [samemory/homebridge-eufy-security#340]
### What happened?

Received the Eufy Wireless Doorbell with Homebase 2
All is working fine in the App, so now i want it to show up in HomeBridge.
Shared my devices (Doorbell and HomeBase 2) to another account, and verfified that is show up in the App with that account.
(Devices shared with advanced options)
Installed the Plugin v1.0.8 in HomeBridge, account seems to work (now), but all i'm getting is:
`No devices found.`
`No stations found.`
Tried it with default setting for language and also with the language (NL) i used when installing the app on my phone.
Also installed the v1.1.1-beta. 14 - beta Plugin. Same result.
First tested in on my default HomeBridge, running in Synology.
Now also tested with same results on other HomeBridge running on Raspbian GNU/Linux Buster (10)

### Device Type

Doorbell (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[1/26/2022, 3:06:43 PM] [EufySecurity-1.1.1-beta.14] DEBUG: PollingInterval: 10
[1/26/2022, 3:06:43 PM] [EufySecurity-1.1.1-beta.14] DEBUG: Refresh data from cloud and schedule next refresh.
[1/26/2022, 3:06:43 PM] [EufySecurity-1.1.1-beta.14] DEBUG: Request: {
  method: 'post',
  endpoint: 'v1/app/get_hub_list',
  baseUrl: 'https://security-app.eufylife.com',
  token: '6330fbbd2fd8508cb39bdaefedf8f51df759bcafe7f3228d',
  data: {
    device_sn: '',
    num: 1000,
    orderby: '',
    page: 0,
    station_sn: '',
    time_zone: 3600000,
    transaction: '1643206003565'
  },
  headers: {
    app_version: 'v3.3.1_1058',
    os_type: 'android',
    os_version: '30',
    phone_model: 'EUFYCLIENT',
    country: 'NL',
    language: 'en',
    openudid: '659a16a256283427',
    uid: '',
    net_type: 'wifi',
    mnc: '02',
    mcc: '262',
    sn: '77768cde7778',
    Model_type: 'PHONE',
    timezone: 'GMT+01:00',
    'Cache-Control': 'no-cache',
    'X-Auth-Token': '6330fbbd2fd8508cb39bdaefedf8f51df759bcafe7f3228d'
  }
}
[1/26/2022, 3:06:43 PM] [EufySecurity-1.1.1-beta.14] DEBUG: Request: {
  method: 'post',
  endpoint: 'v1/app/get_hub_list',
  baseUrl: 'https://security-app.eufylife.com',
  token: '6330fbbd2fd8508cb39bdaefedf8f51df759bcafe7f3228d',
  data: {
    device_sn: '',
    num: 1000,
    orderby: '',
    page: 0,
    station_sn: '',
    time_zone: 3600000,
    transaction: '1643206003675'
  },
  headers: {
    app_version: 'v3.3.1_1058',
    os_type: 'android',
    os_version: '30',
    phone_model: 'EUFYCLIENT',
    country: 'NL',
    language: 'en',
    openudid: '659a16a256283427',
    uid: '',
    net_type: 'wifi',
    mnc: '02',
    mcc: '262',
    sn: '77768cde7778',
    Model_type: 'PHONE',
    timezone: 'GMT+01:00',
    'Cache-Control': 'no-cache',
    'X-Auth-Token': '6330fbbd2fd8508cb39bdaefedf8f51df759bcafe7f3228d'
  }
}
[1/26/2022, 3:06:44 PM] [EufySecurity-1.1.1-beta.14] DEBUG: Stations - Response: { code: 0, msg: 'Succeed.', data: null }
[1/26/2022, 3:06:44 PM] [EufySecurity-1.1.1-beta.14] INFO:  No stations found.
[1/26/2022, 3:06:44 PM] [EufySecurity-1.1.1-beta.14] DEBUG: Request: {
  method: 'post',
  endpoint: 'v1/app/get_devs_list',
  baseUrl: 'https://security-app.eufylife.com',
  token: '6330fbbd2fd8508cb39bdaefedf8f51df759bcafe7f3228d',
  data: {
    device_sn: '',
    num: 1000,
    orderby: '',
    page: 0,
    station_sn: '',
    time_zone: 3600000,
    transaction: '1643206004052'
  },
  headers: {
    app_version: 'v3.3.1_1058',
    os_type: 'android',
    os_version: '30',
    phone_model: 'EUFYCLIENT',
    country: 'NL',
    language: 'en',
    openudid: '659a16a256283427',
    uid: '',
    net_type: 'wifi',
    mnc: '02',
    mcc: '262',
    sn: '77768cde7778',
    Model_type: 'PHONE',
    timezone: 'GMT+01:00',
    'Cache-Control': 'no-cache',
    'X-Auth-Token': '6330fbbd2fd8508cb39bdaefedf8f51df759bcafe7f3228d'
  }
}
[1/26/2022, 3:06:44 PM] [EufySecurity-1.1.1-beta.14] DEBUG: Stations - Response: { code: 0, msg: 'Succeed.', data: null }
[1/26/2022, 3:06:44 PM] [EufySecurity-1.1.1-beta.14] INFO:  No stations found.
[1/26/2022, 3:06:44 PM] [EufySecurity-1.1.1-beta.14] DEBUG: Request: {
  method: 'post',
  endpoint: 'v1/app/get_devs_list',
  baseUrl: 'https://security-app.eufylife.com',
  token: '6330fbbd2fd8508cb39bdaefedf8f51df759bcafe7f3228d',
  data: {
    device_sn: '',
    num: 1000,
    orderby: '',
    page: 0,
    station_sn: '',
    time_zone: 3600000,
    transaction: '1643206004075'
  },
  headers: {
    app_version: 'v3.3.1_1058',
    os_type: 'android',
    os_version: '30',
    phone_model: 'EUFYCLIENT',
    country: 'NL',
    language: 'en',
    openudid: '659a16a256283427',
    uid: '',
    net_type: 'wifi',
    mnc: '02',
    mcc: '262',
    sn: '77768cde7778',
    Model_type: 'PHONE',
    timezone: 'GMT+01:00',
    'Cache-Control': 'no-cache',
    'X-Auth-Token': '6330fbbd2fd8508cb39bdaefedf8f51df759bcafe7f3228d'
  }
}
[1/26/2022, 3:06:44 PM] [EufySecurity-1.1.1-beta.14] DEBUG: Devices - Response: { code: 0, msg: 'Succeed.', data: null }
[1/26/2022, 3:06:44 PM] [EufySecurity-1.1.1-beta.14] INFO:  No devices found.
[1/26/2022, 3:06:44 PM] [EufySecurity-1.1.1-beta.14] DEBUG: Devices - Response: { code: 0, msg: 'Succeed.', data: null }
[1/26/2022, 3:06:44 PM] [EufySecurity-1.1.1-beta.14] INFO:  No devices found.
[1/26/2022, 3:06:44 PM] [EufySecurity-1.1.1-beta.14] DEBUG: Sending heartbeat... 3
[1/26/2022, 3:06:44 PM] [EufySecurity-1.1.1-beta.14] DEBUG: heartbeatPingRequest { last_stream_id_received: 3 }
[1/26/2022, 3:06:44 PM] [EufySecurity-1.1.1-beta.14] DEBUG: Heartbeat acknowledge { tag: 1, object: { lastStreamIdReceived: 3 } }
```

**Comment by schliemann** [comment]
Could you try and make an issue in the eufy security client github for bropat? We are seeing a lot of these where no stations are found.

**Comment by schliemann** [comment]
@dewoert What region is your account in?

**Comment by dewoert** [comment]
Account region is set to NL

**Comment by schliemann** [comment]
@dewoert Is this log produced with enableDetailedLogging to 2?

**Comment by dewoert** [comment]
> @dewoert Is this log produced with enableDetailedLogging to 2?

I think it was set to 2, not really sure.
Removed the Plugin because of this problem.
Saw that bropat has a fix now for this same problem (https://github.com/bropat/eufy-security-ws/issues/74)

**Comment by schliemann** [comment]
@dewoert The work around from Bropat until next release is here:

https://github.com/bropat/eufy-security-ws/issues/74#issuecomment-1024619656

On iOS it might be difficult to control the version. But on Android it is do-able.

**Comment by dewoert** [comment]
Tried a bit with Android, but no succes.
Bropat relased a newer version, and on my Homeassistant intergration it's working now.
https://github.com/bropat/eufy-security-ws/releases/tag/0.8.0
Does this homebridge plugin need an update now also ?

**Comment by schliemann** [comment]
Yeah. Haven't had the time to test the new version. Will try and push a new beta tonight.

**Comment by schliemann** [comment]
@dewoert I can see that @lenoxys updated the package. Please re-test.

**Comment by dewoert** [comment]
On my test-homebridge it's working now ! Thanks.

On my "normal"-homebridge I'm getting error with the Captcha :(
`[2/6/2022, 2:21:58 PM] [EufySecurity-1.1.1-beta.18] DEBUG: Captcha verification received {
  captchaId: '73a8c1d2-d35a-4aea-937a-131b93f8771c',
  item: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFUAAAAr`
Had that problem some time ago also.. Account is same as on my test-homebridge.
Don't really understand the reason

**Comment by dewoert** [comment]
homebridge-eufy-security v1.1.1-beta.18 is connecting now.
Created a new account, shared devices, and configured the Plugin to run with that new account.
So far so good
(Problem with FFmpeg, but that is allready mentioned in other issues)

**Comment by schliemann** [comment]
@dewoert So it finds devices now?

**Comment by dewoert** [comment]
Yes !!

**Comment by schliemann** [comment]
@dewoert Which ffmpeg do you have?

**Comment by dewoert** [comment]
For me it is fine to close this bug reports.
Devices are found now with the v1.1.1-beta.18 
Will play a bit more with the video setting, and perhaps create a seperate bug report about that.
