### ISSUE TITLE
[Bug]: HK stuck on Arming

### ISSUE THREAD

**Issue by deus117** [samemory/homebridge-eufy-security#342]
### What happened?

When using schedules via the Eufy app the security system in HomeKit get’s stuck on arming whenever the eufy schedule changes the security mode.

### Device Type

Station (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Ubuntu 18.04+ (Supported)

**Comment by schliemann** [comment]
@deus117 Pretty sure I saw the same when I had a schedule enabled. Can you provide the logs and set enableDetailedLogging to 2?

**Comment by lenoxys** [comment]
Hello yeah I saw that too.

**Comment by fullphat** [comment]
The PR I submitted will hopefully fix this.

**Comment by coryforman** [comment]
This happens when you have the mode set to geofencing. I’ve worked around this by setting it to home or away in Eufy app, adding dummy switches Homebridge plug-in and using HomeKit’s location to arm/disarm based on location.

**Comment by schliemann** [comment]
Schedules works poorly with homekit. And as @coryforman writes it's probably the same with geofencing.
