### ISSUE TITLE
[Bug]: [EufySecurity] FFmpeg exited with code: 1 and signal: null (Error)

### ISSUE THREAD

**Issue by permaMonk** [samemory/homebridge-eufy-security#344]
### What happened?

[EufySecurity] Starting video stream: 1280 x 720, 30 fps, 299 kbps (AAC-eld) cam_name
[EufySecurity] FFmpeg exited with code: 1 and signal: null (Error) cam_name
[EufySecurity] Stopped video stream. cam_name

### Device Type

Indoor Camera (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Windows 10+ (Supported)

### Relevant log output

```shell
I see allways an old screen picture from 2 weeks ago.

After I restart the cam I see a short time the eufy logo, the screen picture is updating to the actual time and
date and after 30 seconds falling back to this old picture.

Everything is ok in the eufy app selv. Cant see any picture or video in VLC. But at the time of setting up
the plugin, I was able to. I haven't changed anything since then. Read the "Common Issues page"?
Before using the command "sudo npm i ffmpeg-for-homebridge -g" what does it make?

--

Node.js: 16.13.2
HB: 1.4.0
Homebridge Eufy Security: 1.0.8
Win: 11

Config
{
    "platform": "EufySecurity",
    "username": "xxx@xxx.xxx",
    "password": "yyy,
    "enableCamera": true,
    "pollingIntervalMinutes": 10,
    "hkHome": 1,
    "hkAway": 0,
    "hkNight": 3,
    "hkOff": 63,
    "enableDetailedLogging": 0,
    "ignoreStations": [
        ""
    ],
    "ignoreDevices": [
        ""
    ]
}
```

**Comment by schliemann** [comment]
@permaMonk That is unfortunately how the plugin works currently. The beta can provide a real snapshot. However currently the beta also only supports 30 seconds of streaming.

**Comment by permaMonk** [comment]
OK, understood. Thanks again for this clear description of the current situation and the outlook for the coming version. You had already explained that in several posts before, but I hadn't understood it yet.  Sorry for the repeated request.

**Comment by schliemann** [comment]
@permaMonk No problem :)
