### ISSUE TITLE
[Bug]: Wrong username or password

### ISSUE THREAD

**Issue by MartinJRS** [samemory/homebridge-eufy-security#346]
### What happened?

Wrong username or password is prompted when trying to get started with the plugin. I am 100% sure to enter the correct login data.

### Device Type

Station (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.3.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

[30/01/2022, 21:30:52] [EufySecurity] Initializing EufySecurity platform...
[1/30/2022, 9:30:52 PM] [EufySecurity-1.0.8] INFO:  Eufy Security Plugin: enableDetailedLogging on
[1/30/2022, 9:30:52 PM] [EufySecurity-1.0.8] INFO:  Finished initializing Eufy Security Platform
[1/30/2022, 9:30:54 PM] [EufySecurity-1.0.8] DEBUG: EufyClient connected false
[1/30/2022, 9:30:54 PM] [EufySecurity-1.0.8] ERROR: Not connected can't continue!

**Comment by MartinJRS** [comment]
I have just tested to re-login on my iPad and iPhone. After typing my login data, I am now prompted to enter a verification-key that is shown ... is that new? Is that maybe the reason why the plugin's login fails?

**Comment by fullphat** [comment]
Most likely, yes.  You're better off creating a new account, signing in to the Eufy app with it and passing any Captcha verification.  Then sign out and use the credentials for the plugin.  If you can, disable 2FA for this account as well.

Note that this account will need to be an admin one, but you can choose to share as many devices as you want (I only share one of my Eufy devices).

Post back if you still have issues.

**Comment by MartinJRS** [comment]
Alright, many thanks. I did everything as described.

[31/01/2022, 00:24:00] [EufySecurity] Initializing EufySecurity platform...
[1/31/2022, 12:24:01 AM] [EufySecurity-1.0.8] INFO:  Eufy Security Plugin: enableDetailedLogging on
[1/31/2022, 12:24:01 AM] [EufySecurity-1.0.8] INFO:  Finished initializing Eufy Security Platform
[1/31/2022, 12:24:01 AM] [EufySecurity-1.0.8] DEBUG: discoveringDevices
[1/31/2022, 12:24:01 AM] [EufySecurity-1.0.8] DEBUG: EufyClient connected true
[1/31/2022, 12:24:01 AM] [EufySecurity-1.0.8] DEBUG: PollingInterval: 30
[1/31/2022, 12:24:01 AM] [EufySecurity-1.0.8] DEBUG: Refresh data from cloud and schedule next refresh.
[1/31/2022, 12:24:02 AM] [EufySecurity-1.0.8] DEBUG: Found 0 stations.
[1/31/2022, 12:24:02 AM] [EufySecurity-1.0.8] DEBUG: Found 0 devices.
[1/31/2022, 12:24:03 AM] [EufySecurity-1.0.8] WARN:  Push Closed!
[1/31/2022, 12:24:03 AM] [EufySecurity-1.0.8] DEBUG: Push Connected!

After this seem to be fine ... none of my devices are shown in the Homebridge device overview. Am I missing something?

**Comment by schliemann** [comment]
@MartinJRS The problem with no found devices is unfortunately not resolved currently. And we don't know why this happen. Previously I thought it had something to do with the country setting. But I'm not that confident anymore.

**Comment by MartinJRS** [comment]
Thanks for responding. So, this is also new for you and might be related to the latest updates on Eufy's side?
There is nothing wrong with my settings?     
   {
            "platform": "EufySecurity",
            "username": "*****@*****.***",
            "password": "********************",
            "country": "DE",
            "ignoreStations": [
                ""
            ],
            "ignoreDevices": [
                "T8113N**********",
                "T8113N**********",
                "T8113N**********"
            ],
            "enableCamera": true,
            "pollingIntervalMinutes": 5,
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 63,
            "enableDetailedLogging": 0
        }

**Comment by schliemann** [comment]
@MartinJRS Could you try and set enableDetailedLogging to 2 and share your log?

**Comment by MartinJRS** [comment]
Yes ... changed it. Where to find the specific Log you need?

**Comment by MartinJRS** [comment]
[1/31/2022, 9:17:17 AM] [EufySecurity-1.0.8] DEBUG: Login response: GCM -> logged in -> waiting for push messages...
[1/31/2022, 9:17:17 AM] [EufySecurity-1.0.8] DEBUG: Request: {
  method: 'post',
  endpoint: 'v1/apppush/register_push_token',
  baseUrl: 'https://security-app.eufylife.com',
  token: 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc',
  data: {
    is_notification_enable: true,
    token: 'cC4GINaX42IfMGvr6lfAqE:APA91bH9LC464ruEBuFyQz1qrnJN2vVZw83YxoXm0plOV2a4ljXZrxhVsWUx7YYEAAoHv1uaiC0dkAo_KHlxfFexMZdXxPQInbe9o0yL35kJhWWPG7o1xMOhPs2EuqMXPVrBEfHQ7Obk',
    transaction: '1643617037298'
  },
  headers: {
    app_version: 'v3.3.1_1058',
    os_type: 'android',
    os_version: '30',
    phone_model: 'EUFYCLIENT',
    country: 'US',
    language: 'en',
    openudid: '8af97f955998961f',
    uid: '',
    net_type: 'wifi',
    mnc: '02',
    mcc: '262',
    sn: '9ff0d333f2bc',
    Model_type: 'PHONE',
    timezone: 'GMT+01:00',
    'Cache-Control': 'no-cache',
    'X-Auth-Token': 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc'
  }
}
[1/31/2022, 9:17:17 AM] [EufySecurity-1.0.8] DEBUG: IqStanza: Not implemented {
  tag: 7,
  object: { type: 'SET', id: '', extension: { id: 12, data: <Buffer > } }
}
[1/31/2022, 9:17:17 AM] [EufySecurity-1.0.8] DEBUG: Response: { code: 0, msg: 'Succeed.' }
[1/31/2022, 9:17:17 AM] [EufySecurity-1.0.8] DEBUG: Push token registered successfully
[1/31/2022, 9:17:17 AM] [EufySecurity-1.0.8] DEBUG: Request: {
  method: 'post',
  endpoint: 'v1/app/review/app_push_check',
  baseUrl: 'https://security-app.eufylife.com',
  token: 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc',
  data: { app_type: 'eufySecurity', transaction: '1643617037554' },
  headers: {
    app_version: 'v3.3.1_1058',
    os_type: 'android',
    os_version: '30',
    phone_model: 'EUFYCLIENT',
    country: 'US',
    language: 'en',
    openudid: '8af97f955998961f',
    uid: '',
    net_type: 'wifi',
    mnc: '02',
    mcc: '262',
    sn: '9ff0d333f2bc',
    Model_type: 'PHONE',
    timezone: 'GMT+01:00',
    'Cache-Control': 'no-cache',
    'X-Auth-Token': 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc'
  }
}
[1/31/2022, 9:17:17 AM] [EufySecurity-1.0.8] DEBUG: Response: {
  code: 0,
  msg: 'Succeed.',
  data: { app_type: 'eufySecurity', pushable: true, reviewable: false }
}
[1/31/2022, 9:17:17 AM] [EufySecurity-1.0.8] DEBUG: Push token OK
[1/31/2022, 9:17:17 AM] [EufySecurity-1.0.8] INFO:  Push notification connection successfully established
[1/31/2022, 9:17:17 AM] [EufySecurity-1.0.8] DEBUG: Push Connected!

**Comment by schliemann** [comment]
Could you try and change the country in the platform.js file to DE. The beta lets you specify a country, but the 1.0.8 does not currently.

https://github.com/samemory/homebridge-eufy-security/blob/7584d96b4a9a21baa260f8ec96342d5d7e83d939/src/platform.ts#L67

**Comment by MartinJRS** [comment]
Uhm, sure ... but I am not certain of how to do that ... is there an easy way to tell?

**Comment by MartinJRS** [comment]
I mean, I do not know where to find the platform.js file and if I have to install the beta ... and if so, how to. Sorry, I am pretty new to all this.

**Comment by schliemann** [comment]
@MartinJRS No need to apologize. It is not trivial.

What are you running homebridge on?

**Comment by MartinJRS** [comment]
Thanks for helping. I run it on a Raspberry Pi 400 ...

**Comment by fullphat** [comment]
> I mean, I do not know where to find the platform.js file and if I have to install the beta ... and if so, how to. Sorry, I am pretty new to all this.

I'm new to all this as well. 😊 To install the beta, assuming you're running the HomeBridge-UI plugin, login to the HomeBridge portal on your RPi and find the Eufy Security plugin in the plugins page.  Click "install previous version" and pick the beta from the list that appears (it'll be near the top).

To find the right folder, in a terminal session enter:

`where HomeBridge`

Navigate to the folder that appears and then do:

`ls -l`

look for the HomeBridge entry and navigate to where the symlink points to.

**Comment by MartinJRS** [comment]
Okay, thank you guys for being so helping. I have now established homebridge-eufy-security v1.1.1-beta.15 ... Still not finding devices. Here is the log:

[31/01/2022, 10:47:11] [EufySecurity] Initializing EufySecurity platform...
[1/31/2022, 10:47:11 AM] [EufySecurity-1.1.1-beta.15] INFO:  enableDetailedLogging on
[1/31/2022, 10:47:11 AM] [EufySecurity-1.1.1-beta.15] INFO:  Country set: DE
[1/31/2022, 10:47:11 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Load previous login_hash: 89ed5d8294434b04e7d96a7cdd149b2a
[1/31/2022, 10:47:11 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Load previous api_base: https://security-app.eufylife.com
[1/31/2022, 10:47:11 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Load previous token: {
  token: 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc',
  tokenExpiration: 1646176474000
}
[1/31/2022, 10:47:11 AM] [EufySecurity-1.1.1-beta.15] INFO:  Finished initializing Eufy Security Platform
[1/31/2022, 10:47:11 AM] [EufySecurity-1.1.1-beta.15] DEBUG: discoveringDevices
[1/31/2022, 10:47:11 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Authenticate and get an access token {
  token: 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc',
  tokenExpiration: 2022-03-01T23:14:34.000Z
}
[1/31/2022, 10:47:11 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Request: {
  method: 'get',
  endpoint: 'v1/app/trust_device/list',
  baseUrl: 'https://security-app.eufylife.com',
  token: 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc',
  data: undefined,
  headers: {
    app_version: 'v3.3.1_1058',
    os_type: 'android',
    os_version: '30',
    phone_model: 'EUFYCLIENT',
    country: 'DE',
    language: 'en',
    openudid: '8af97f955998961f',
    uid: '',
    net_type: 'wifi',
    mnc: '02',
    mcc: '262',
    sn: '9ff0d333f2bc',
    Model_type: 'PHONE',
    timezone: 'GMT+01:00',
    'Cache-Control': 'no-cache',
    'X-Auth-Token': 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc'
  }
}
[1/31/2022, 10:47:11 AM] [EufySecurity-1.1.1-beta.15] DEBUG: EufyClient connected true
[1/31/2022, 10:47:11 AM] [EufySecurity-1.1.1-beta.15] DEBUG: PollingInterval: 5
[1/31/2022, 10:47:11 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Refresh data from cloud and schedule next refresh.
[1/31/2022, 10:47:11 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Request: {
  method: 'post',
  endpoint: 'v1/app/get_hub_list',
  baseUrl: 'https://security-app.eufylife.com',
  token: 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc',
  data: {
    device_sn: '',
    num: 1000,
    orderby: '',
    page: 0,
    station_sn: '',
    time_zone: 3600000,
    transaction: '1643622431701'
  },
  headers: {
    app_version: 'v3.3.1_1058',
    os_type: 'android',
    os_version: '30',
    phone_model: 'EUFYCLIENT',
    country: 'DE',
    language: 'en',
    openudid: '8af97f955998961f',
    uid: '',
    net_type: 'wifi',
    mnc: '02',
    mcc: '262',
    sn: '9ff0d333f2bc',
    Model_type: 'PHONE',
    timezone: 'GMT+01:00',
    'Cache-Control': 'no-cache',
    'X-Auth-Token': 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc'
  }
}
[1/31/2022, 10:47:13 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Stations - Response: { code: 0, msg: 'Succeed.', data: null }
[1/31/2022, 10:47:13 AM] [EufySecurity-1.1.1-beta.15] INFO:  No stations found.
[1/31/2022, 10:47:13 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Request: {
  method: 'post',
  endpoint: 'v1/app/get_devs_list',
  baseUrl: 'https://security-app.eufylife.com',
  token: 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc',
  data: {
    device_sn: '',
    num: 1000,
    orderby: '',
    page: 0,
    station_sn: '',
    time_zone: 3600000,
    transaction: '1643622433197'
  },
  headers: {
    app_version: 'v3.3.1_1058',
    os_type: 'android',
    os_version: '30',
    phone_model: 'EUFYCLIENT',
    country: 'DE',
    language: 'en',
    openudid: '8af97f955998961f',
    uid: '',
    net_type: 'wifi',
    mnc: '02',
    mcc: '262',
    sn: '9ff0d333f2bc',
    Model_type: 'PHONE',
    timezone: 'GMT+01:00',
    'Cache-Control': 'no-cache',
    'X-Auth-Token': 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc'
  }
}
[1/31/2022, 10:47:13 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Response: { code: 0, msg: 'ok', data: { list: [] } }
[1/31/2022, 10:47:13 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Save cloud token and token expiration {
  token: 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc',
  tokenExpiration: 2022-03-01T23:14:34.000Z
}
[1/31/2022, 10:47:13 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Login with previous push credentials... {
  fidResponse: {
    name: 'projects/348804314802/installations/cC4GINaX42IfMGvr6lfAqE',
    fid: 'cC4GINaX42IfMGvr6lfAqE',
    refreshToken: '2_qLbFbwfc1tAcwCeTSl6wnoO7P1-M70i487XrR26TuCgrKf_x3IumhQkMTfZy83Og',
    authToken: {
      token: 'eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6IjE6MzQ4ODA0MzE0ODAyOmFuZHJvaWQ6NDQwYTY3NzNiMzYyMGRhNyIsImV4cCI6MTY0Mzc0NzE0OCwiZmlkIjoiY0M0R0lOYVg0MklmTUd2cjZsZkFxRSIsInByb2plY3ROdW1iZXIiOjM0ODgwNDMxNDgwMn0.AB2LPV8wRAIgCi0MBzkCwwt1fSbie-xTPODYjZxmwg1S_sROggpkTjACIH7AZ8xB2FpO4vLNKxx7d8QDkLa5bNh_P4o-pHnkk_fQ',
      expiresIn: '604800s',
      expiresAt: 1643747148418
    }
  },
  checkinResponse: {
    statsOk: true,
    timeMs: '1643622248088',
    androidId: '3491654698573025758',
    securityToken: '7121842446197837050',
    versionInfo: 'I_5zR4CI-o4ZQEb1aBJ6XhwC41L46hc',
    deviceDataVersionInfo: 'ABFEt1VA3Wyo90NnSq7WPtH7VD1PlEz0oQvH5pGlmMV6QuobfbACj9dZNvijpyPIGogflcNvAnxw2-r4ND11YSTjPvG01XObq6y2svwFOsPiMVFgDzz_PlWf7rodMft1mahSMFqyL8P1vlcqhy6zcv8PCj9oMBmmkdjQIRXf3YjCSQQ4DKFRVtiI2a_JXdwgVX44HQH497IK1LHAY7gOX9RmA_SncCcxIKikUUcfP5TzY6Za1Kf0YXVqrogvAmdjX_gpRqa3ZGnQSrsb1jw7PQq9FNOwLgp5rrwdany1k5JYySFRp5bFTBARO-jkX51M06jcDy19SxLu8cePPpYlrSbt4Sn4nZTQqH_8NWU11wufQBW8zxOEEZg'
  },
  gcmResponse: {
    token: 'cC4GINaX42IfMGvr6lfAqE:APA91bHBsWc1LB5ToYhZENaBXB4687rKQQzYVw8HyrW4G7Ti0M8hMmx14Mz7lOrAO22okfksDCMGEKvMjSifOKgxK92q4kQ9H40ERnwkjojBsU0uzCLwQhViFZrGmGwlvQ4g6nZHiqh7'
  }
}
[1/31/2022, 10:47:13 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Request: {
  method: 'post',
  endpoint: 'v1/app/get_hub_list',
  baseUrl: 'https://security-app.eufylife.com',
  token: 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc',
  data: {
    device_sn: '',
    num: 1000,
    orderby: '',
    page: 0,
    station_sn: '',
    time_zone: 3600000,
    transaction: '1643622433218'
  },
  headers: {
    app_version: 'v3.3.1_1058',
    os_type: 'android',
    os_version: '30',
    phone_model: 'EUFYCLIENT',
    country: 'DE',
    language: 'en',
    openudid: '8af97f955998961f',
    uid: '',
    net_type: 'wifi',
    mnc: '02',
    mcc: '262',
    sn: '9ff0d333f2bc',
    Model_type: 'PHONE',
    timezone: 'GMT+01:00',
    'Cache-Control': 'no-cache',
    'X-Auth-Token': 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc'
  }
}
[1/31/2022, 10:47:13 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Devices - Response: { code: 0, msg: 'Succeed.', data: null }
[1/31/2022, 10:47:13 AM] [EufySecurity-1.1.1-beta.15] INFO:  No devices found.
[1/31/2022, 10:47:13 AM] [EufySecurity-1.1.1-beta.15] DEBUG: CameraMaxLivestreamDuration: 30
[1/31/2022, 10:47:13 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Found 0 stations.
[1/31/2022, 10:47:13 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Found 0 devices.
[1/31/2022, 10:47:13 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Stations - Response: { code: 0, msg: 'Succeed.', data: null }
[1/31/2022, 10:47:13 AM] [EufySecurity-1.1.1-beta.15] INFO:  No stations found.
[1/31/2022, 10:47:13 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Request: {
  method: 'post',
  endpoint: 'v1/app/get_devs_list',
  baseUrl: 'https://security-app.eufylife.com',
  token: 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc',
  data: {
    device_sn: '',
    num: 1000,
    orderby: '',
    page: 0,
    station_sn: '',
    time_zone: 3600000,
    transaction: '1643622433386'
  },
  headers: {
    app_version: 'v3.3.1_1058',
    os_type: 'android',
    os_version: '30',
    phone_model: 'EUFYCLIENT',
    country: 'DE',
    language: 'en',
    openudid: '8af97f955998961f',
    uid: '',
    net_type: 'wifi',
    mnc: '02',
    mcc: '262',
    sn: '9ff0d333f2bc',
    Model_type: 'PHONE',
    timezone: 'GMT+01:00',
    'Cache-Control': 'no-cache',
    'X-Auth-Token': 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc'
  }
}
[1/31/2022, 10:47:13 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Devices - Response: { code: 0, msg: 'Succeed.', data: null }
[1/31/2022, 10:47:13 AM] [EufySecurity-1.1.1-beta.15] INFO:  No devices found.
[1/31/2022, 10:47:14 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Login response: GCM -> logged in -> waiting for push messages...
[1/31/2022, 10:47:14 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Request: {
  method: 'post',
  endpoint: 'v1/apppush/register_push_token',
  baseUrl: 'https://security-app.eufylife.com',
  token: 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc',
  data: {
    is_notification_enable: true,
    token: 'cC4GINaX42IfMGvr6lfAqE:APA91bECZ9UPP5ynCW9scNCtGQxGMu-SqurnyQNEfWo3j00yGg8jugHwi5hSNlOrkZk1blu1Fa8wjYdiypTZbG85hFdDTUCFPw8BaE2vfNisvlMIkjIoLgkUqB47Y0t-hpPfA0RR0nNE',
    transaction: '1643622434174'
  },
  headers: {
    app_version: 'v3.3.1_1058',
    os_type: 'android',
    os_version: '30',
    phone_model: 'EUFYCLIENT',
    country: 'DE',
    language: 'en',
    openudid: '8af97f955998961f',
    uid: '',
    net_type: 'wifi',
    mnc: '02',
    mcc: '262',
    sn: '9ff0d333f2bc',
    Model_type: 'PHONE',
    timezone: 'GMT+01:00',
    'Cache-Control': 'no-cache',
    'X-Auth-Token': 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc'
  }
}
[1/31/2022, 10:47:14 AM] [EufySecurity-1.1.1-beta.15] DEBUG: IqStanza: Not implemented {
  tag: 7,
  object: { type: 'SET', id: '', extension: { id: 12, data: <Buffer > } }
}
[1/31/2022, 10:47:14 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Response: { code: 0, msg: 'Succeed.' }
[1/31/2022, 10:47:14 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Push token registered successfully
[1/31/2022, 10:47:14 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Request: {
  method: 'post',
  endpoint: 'v1/app/review/app_push_check',
  baseUrl: 'https://security-app.eufylife.com',
  token: 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc',
  data: { app_type: 'eufySecurity', transaction: '1643622434325' },
  headers: {
    app_version: 'v3.3.1_1058',
    os_type: 'android',
    os_version: '30',
    phone_model: 'EUFYCLIENT',
    country: 'DE',
    language: 'en',
    openudid: '8af97f955998961f',
    uid: '',
    net_type: 'wifi',
    mnc: '02',
    mcc: '262',
    sn: '9ff0d333f2bc',
    Model_type: 'PHONE',
    timezone: 'GMT+01:00',
    'Cache-Control': 'no-cache',
    'X-Auth-Token': 'eebb936a8f3e77bb673c45aab1579b95081224a84aa43fbc'
  }
}
[1/31/2022, 10:47:14 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Response: { code: 0, msg: 'Succeed.' }
[1/31/2022, 10:47:14 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Push token OK
[1/31/2022, 10:47:14 AM] [EufySecurity-1.1.1-beta.15] INFO:  Push notification connection successfully established
[1/31/2022, 10:47:14 AM] [EufySecurity-1.1.1-beta.15] DEBUG: Push Connected!

**Comment by MartinJRS** [comment]
I hope there is no sensitive data included 😂

**Comment by schliemann** [comment]
@MartinJRS 

You can remove the log again.

**Comment by MartinJRS** [comment]
Thanks

**Comment by schliemann** [comment]
@MartinJRS

I think it is concerning that we are seeing this amount of people having this issue. Would you help and create an issue on the [eufy-security-client](https://github.com/bropat/eufy-security-client/issues) github? You would need to supply your log to Bropat. Maybe then we can get to the bottom of these problems.

**Comment by schliemann** [comment]
@MartinJRS

Before doing that however please check out bropats reply here:

https://github.com/bropat/eufy-security-client/issues/91

**Comment by MartinJRS** [comment]
Yeah, I am pretty sure all this is indeed due to Eufy's latest updated and changes ... frankly starting to hate that company.

Very much appreciate your help and your good work

**Comment by MartinJRS** [comment]
So, is there a chance for it to be working again any time soon?

**Comment by schliemann** [comment]
@MartinJRS My guess would be a release pretty soon. But I don't know his plans.

**Comment by schliemann** [comment]
Bropat wrote it will be fixed in the next version.

**Comment by MartinJRS** [comment]
Alright, thanks many times ... very much appreciated.

**Comment by schliemann** [comment]
@MartinJRS 

The work around from Bropat until next release is here:

bropat/eufy-security-ws#74 (comment)

On iOS it might be difficult to control the version. But on Android it is do-able.

**Comment by schliemann** [comment]
@MartinJRS I can see that @lenoxys updated the package. Please re-test.

**Comment by MartinJRS** [comment]
Okay, thanks. Using homebridge-eufy-security v1.1.1-beta.18 ... still not working for me.

**Comment by schliemann** [comment]
@MartinJRS Odd. Some of the other people with this issue reported that it got solved. Can you try and delete the cache?

**Comment by MartinJRS** [comment]
Morning and thanks for replying. I have now deleted the Eufy devices from cache, restarted the server, uninstalled and re-installed the plugin (homebridge-eufy-security v1.1.1-beta.18) ... but still, there are no devices.

            "platform": "EufySecurity",
            "username": "name@domain.xx",
            "password": "xxxxxx-xxxxxx-xxxxxx",
            "country": "DE",
            "ignoreStations": [
                ""
            ],
            "ignoreDevices": [
                "T8113Nxxxxxxxxx1",
                "T8113Nxxxxxxxxx2",
                "T8113Nxxxxxxxxx3"
            ],
            "enableCamera": false,
            "pollingIntervalMinutes": 30,
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 63,
            "enableDetailedLogging": 0,
            "CameraMaxLivestreamDuration": 30

[07/02/2022, 08:11:36] [EufySecurity] Initializing EufySecurity platform...
[07/02/2022, 08:11:36] [EufySecurity] Country set: DE
[07/02/2022, 08:11:36] [EufySecurity] Finished initializing Eufy Security Platform
[07/02/2022, 08:11:39] [EufySecurity] Push Closed!

What am I doing wrong?

**Comment by schliemann** [comment]
Which devices are you ignoring?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MartinJRS** [comment]
It's 3 eufyCam 2C

**Comment by schliemann** [comment]
Which devices do you have besides the three eufy cams?

**Comment by schliemann** [comment]
Bropat released a new version. Might make a new beta build tonight.

**Comment by lenoxys** [comment]
please have a look on the latest beta (>=.19)

**Comment by lenoxys** [comment]
Can you clear your browser cache ? If not working could you uninstall and reinstall the plug-in with a reboot between them

**Comment by MartinJRS** [comment]
Have done all these steps with the result that now I cannot even login to Eufy inside the plugin.

![Bildschirmfoto 2022-02-10 um 12 52 53](https://user-images.githubusercontent.com/97555159/153404668-10e521ba-80b9-44d9-9ddf-7aa255e13bb4.png)

**Comment by aididhaiqal** [comment]
Hi @lenoxys, I'm not sure if this is related but the Country selector doesn't work now. Even if I select other country, it still sending US country code. Manually changing in code to my country does appear to help me login again

**Comment by r33ce15** [comment]
> Have done all these steps with the result that now I cannot even login to Eufy inside the plugin.
> 
> 
> 
> ![Bildschirmfoto 2022-02-10 um 12 52 53](https://user-images.githubusercontent.com/97555159/153405012-f536e613-b67f-4ad5-87f3-1e73e60a1d62.jpg)
> 
> 
> 
> 

I had same issue! today my doorbell freaked out couldn't get back into account through homebridge despite login still working online so made new account updated to latest beta and now receive this error too and can't get back in

**Comment by MartinJRS** [comment]
Anything new?

**Comment by r33ce15** [comment]
I have reinstalled this plugin today and picked up beta 19 and I am now logged in and all working again I saw the eufy security app has been updated so errors we saw few days ago could be linked

**Comment by MartinJRS** [comment]
Can't confirm ... still same error here

**Comment by lenoxys** [comment]
I'm referring to this reset wizard : [Reset](https://github.com/samemory/homebridge-eufy-security/wiki/Basic-Troubleshooting#reset--clear)

Be sure to validate by clicking on Reset Everything

**Comment by lenoxys** [comment]
make sure to clear your browser cache

**Comment by MartinJRS** [comment]
Thank you so much ... now all is up and running. Sorry for me not figuring it out by myself. Your support is awesome and you guys are doing a great job.
