### ISSUE TITLE
Support for Eufy security camera solo s40

### ISSUE THREAD

**Issue by dznbyaj** [samemory/homebridge-eufy-security#348]
### Describe the solution you'd like

I didn’t see the Eufy security camera solo S40 as a supported plugin. Would love to see support for this one if possible. Thanks!

**Comment by schliemann** [comment]
@dznbyaj Have you tested it?

**Comment by paqpaqpaq** [comment]
it somewhat works...
hit&miss
But no light settings

Also arming works, disarming doesn't

**Comment by dznbyaj** [comment]
Thank you both. Makes sense. I was presuming an updated list of supported devices.
