### ISSUE TITLE
[Bug]: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Dulox24** [samemory/homebridge-eufy-security#349]
### What happened?

I tried to add my Eufy Homebase + Doorbell to this plugin.
When I login with a guest account (or original account) I don't see any devices. Not in the latest version and not in the Beta version (Country is set to "NL").

debug in the beta version shows:

[2/7/2022, 10:14:11 PM] [EufySecurity-1.1.1-beta.18] DEBUG: discoveringDevices
Exception in PromiseRejectCallback:
/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/build/http/api.js:224
        return types_1.AuthResult.OK;

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/build/http/api.js:440
            switch (await this.authenticate()) {
                               ^

RangeError: Maximum call stack size exceeded

Anything I could to to see my devices ?
Homebridge version v1.4.0

### Device Type

Doorbell (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

other (UnSupported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[2/7/2022, 10:14:11 PM] [EufySecurity-1.1.1-beta.18] INFO:  enableDetailedLogging on
[2/7/2022, 10:14:11 PM] [EufySecurity-1.1.1-beta.18] INFO:  Country set: NL
[2/7/2022, 10:14:11 PM] [EufySecurity-1.1.1-beta.18] INFO:  Finished initializing Eufy Security Platform
[2/7/2022, 10:14:11 PM] [EufySecurity-1.1.1-beta.18] DEBUG: discoveringDevices
Exception in PromiseRejectCallback:
/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/build/http/api.js:224
        return types_1.AuthResult.OK;

RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
/usr/local/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/build/http/api.js:440
            switch (await this.authenticate()) {
                               ^

RangeError: Maximum call stack size exceeded
```

**Comment by schliemann** [comment]
Unsure. Seems to originate from the client library.
