### ISSUE TITLE
Plugin doesn't work. It shows "no station found" and "no devices found" in the log...

### ISSUE THREAD

**Issue by Dominik-1980** [samemory/homebridge-eufy-security#35]
**Describe The Bug:**

Plugin loads, adding 6 accessories, and then it shows "no stations found" and "no devices found"

**To Reproduce:**

Just install, type in username and password. Activate logs.

**Expected behavior:**

Showing Homebase and 2 cameras in HomeKit

**Logs:**

```
{"name":"eufyLog","hostname":"homeserver","pid":3243,"level":30,"msg":"No stations found.","time":"2021-06-14T13:53:50.353Z","v":0}
{"name":"eufyLog","hostname":"homeserver","pid":3243,"level":30,"msg":"No devices found.","time":"2021-06-14T13:53:50.714Z","v":0}
{"name":"eufyLog","hostname":"homeserver","pid":3243,"level":30,"msg":"No stations found.","time":"2021-06-14T13:54:51.093Z","v":0}
{"name":"eufyLog","hostname":"homeserver","pid":3243,"level":30,"msg":"No devices found.","time":"2021-06-14T13:54:51.452Z","v":0}
{"name":"eufyLog","hostname":"homeserver","pid":3243,"level":30,"msg":"No stations found.","time":"2021-06-14T13:55:51.841Z","v":0}
{"name":"eufyLog","hostname":"homeserver","pid":3243,"level":30,"msg":"No devices found.","time":"2021-06-14T13:55:52.179Z","v":0}
```

**Environment:**

* **Plugin Version**: 0.2.0
* **Homebridge Version**: 1.3.4
* **Node.js Version**: 14.17.0
* **NPM Version**: 6.14.13
* **Operating System**: Raspbian

I have created a new account as a guest and shared it with my main account. 2FA is disabled.
But I still have the cameras in HomeKit natively. 
I just want to use this plugin to trigger my Homebase modes because the geofencing of the official Eufy-App doesn't work.

The other question is, if my homebridge eufy Account is just as a guest, can the plugin trigger the Homebase modes?

And when is Night triggered? Is there any time I can adjust?

**Comment by andyrooo82** [comment]
After you created the guest account, did you log into this account of the eufy app? if not I found this worked for me. So if you haven't, log out of your main account, log in with your guest account, then log back out again and see if that works.

**Comment by PeterAlexander75** [comment]
I don’t think guest accounts can change the Homebase mode unless you grant them full admin access.

**Comment by andyrooo82** [comment]
I'm logged in using a guest account and I can change the Homebase mod
