### ISSUE TITLE
[enhancement]: Unbridged Mode?

### ISSUE THREAD

**Issue by sheparddw** [samemory/homebridge-eufy-security#353]
### Describe the solution you'd like

Is there support for unbridge mode for cameras/doorbells? My performance is pretty slow and the logs recommend switching to unbridge mode but I did not see this anywhere in the docs. Is this already a feature? If so, where do I set the unbridge flag in the config? 

Thanks for your great work on this plugin!

**Comment by sheparddw** [comment]
The log with the recommendation:
```
[EufySecurity] Fetching snapshot took 29. 474 seconds.
It is highly recommended you switch to unbridge mode. The request has timed out and the snapshot has not been refreshed in HomeKit. Doorbell
```

**Comment by schliemann** [comment]
Are you using the beta?

**Comment by sheparddw** [comment]
Yeah, I do not expect perfect performance or anything as it is beta, just was curious if there was a way to go unbridged.

**Comment by schliemann** [comment]
The beta is the only release that can produce a screenshot and not an old event picture.

**Comment by sheparddw** [comment]
Yeah, that was why I installed the beta. The p2p part is great about it. If there is already a way to unbridge a doorbell on it though, let me know. 🙂

**Comment by paqpaqpaq** [comment]
> Yeah, that was why I installed the beta. The p2p part is great about it. If there is already a way to unbridge a doorbell on it though, let me know. 🙂

You can tick bridge settings at the plugin settings (in UIX), and set it as a child bridge otherwise?

**Comment by sheparddw** [comment]
Yeah, that did seem to help. Good alternative if unbridged mode not supported.

**Comment by lenoxys** [comment]
this is now per camera with the latest beta

**Comment by sheparddw** [comment]
Nice!
