### ISSUE TITLE
[enhancement]: T8520 Lock Support

### ISSUE THREAD

**Issue by ashercaulfield** [samemory/homebridge-eufy-security#354]
### Describe the solution you'd like

T8520 WiFi Lock support would be the best. Thanks.

**Comment by kunwarsethi** [comment]
I would like this as well, bropat just updated the source code to work with the T8520 on February 5th so the team is most likely working on the update for the homebridge version to include it. https://github.com/bropat/eufy-security-client/releases

In the meantime I manually updated the source code (on my RasPi 3 b+ Homebridge) to Bropats 1.6.6 and I'm able to see when the lock is open / closed instantly and I get notifications, but there is still no trigger implementation.

Do it at your own risk if you want for now, I'm not sure if this is the correct way as I'm still learning (if it doesn't work you can always reinstall the plugin) -
In the homebridge terminal - 

1. cd /usr/local/lib/node_modules/homebridge-eufy-security/
2. sudo nano package.json
3. Go down to "dependencies": and change the "eufy-security-client" version to "~1.6.6"
4. Ctrl + X, Y, and then press Enter
5. Sudo npm install
6. Restart homebridge

**Comment by schliemann** [comment]
@ashercaulfield, @kunwarsethi 

The beta is running the latest client library from bropat. Please attach log if something is not working with the lock.

**Comment by kunwarsethi** [comment]
Getting '[EufySecurity] Front Door Open/Close trigger is not implemented' . I believe it's being implemented into the next beta via pull #364
