### ISSUE TITLE
[enhancement]: support for new 2K doorbell dual 

### ISSUE THREAD

**Issue by venables1** [samemory/homebridge-eufy-security#358]
### Describe the solution you'd like

Add support in the plug-in to recognise and allow eufy 2K doorbell dual as currently it does not recognise it and comes back with type 91

**Comment by venables1** [comment]
Yes couldn’t see it on there

**Comment by karesake** [comment]
Wrong plugin. Post your request here:
https://github.com/bropat/eufy-security-client

**Comment by venables1** [comment]
Hi thank you for letting me know I have since added this due to the plug-in you suggested.

Yeah I am aware you would have to have two camera feeds in HomeKit but thank you for your help.

Much appreciated
