### ISSUE TITLE
Please update Changelog documentation

### ISSUE THREAD

**Issue by qthatswho** [samemory/homebridge-eufy-security#359]
### What happened?

Request: Please update Changelog documentation with latest releases info.

On the home page, there is a link to the Changelog: https://github.com/samemory/homebridge-eufy-security/blob/master/CHANGELOG.md
The info in this file has not been updated since 1.0.4 (27/10/2021). Current release appears to be 1.0.8.

(specifically, I'm looking to confirm whether bropat's latest library is included in 1.0.8)

Thanks!

### Device Type

other (UnSupported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Mac OS X 11+ (Supported)

**Comment by stef1949** [comment]
Yeah lol i check Issues tab to see what changes have been made skjdaksldjs

**Comment by qthatswho** [comment]
Sure, but that doesn't _easily_ summarize which changes were included in which release (unless you know what revisions are associated with each "release version").

**Comment by karesake** [comment]
Oh man ...

**Comment by lenoxys** [comment]
I will keep version track within the commit but can't keep it for the beta on change log. But for main release we will :)

**Comment by qthatswho** [comment]
Thanks @lenoxys, main version only is fine. I was confused when I last installed the mainline version in Homebridge UI because it posted the older release notes (for 1.0.4 I think) when I had just finished installing 1.0.8, which is where this request came from. Much appreciated!
