### ISSUE TITLE
[Bug]: No response from the motion sensor ( Battery Doorbell)

### ISSUE THREAD

**Issue by ChristianPorsche** [samemory/homebridge-eufy-security#360]
### What happened?

Hi, 

I installed everything correctly, the motionsensor of the doorbell says that it is ready. However, it won't change its state ones someone walks in front or rings the bell. However, I get a message form the Eufy app that there is motion. 

What can I check more?

And apart from that, it takes something a long time to load the livestream. I get this warning (the name of my doorbell is 'Deurbel':

'Fetching snapshot took 23.607 seconds. It is highly recommended you switch to unbridge mode. The request has timed out and the snapshot has not been refreshed in HomeKit. Deurbel'
or
'Deurbel Failed to fetch snapshot.'

 It works 99% of the time good ones someone rings, I get within 3 seconds a notification from Home that someone is ringing, the livestream starts almost instant after long pressing the message. 

### Device Type

Doorbell (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

**Comment by ChristianPorsche** [comment]
I am running it as a child bridge. I checked the common issues

**Comment by karesake** [comment]
Beta Installieren. 1.0.8 nutzt einen alten Client. Die Beta den neuesten.

**Comment by karesake** [comment]
The problem also exists with other cameras. First of all, however, I would like to see the stream work smoothly and quickly - on all devices such as iPhone, iPad, AppleTV and Watch. Then I go to the sensors so that movements are also displayed on the ATV.

Maybe someone else already has a solution or currently has some time to deal with it?

**Comment by lenoxys** [comment]
Motion event triggers only when you enabled motion trigger on the alarm mode. If you didn't we won't see anything.
