### ISSUE TITLE
[Bug]: No devices found

### ISSUE THREAD

**Issue by csoprano** [samemory/homebridge-eufy-security#361]
### What happened?

I can't see any devices after entering my credentials. 
Can you help me? I have the HomeBase2 with 2 Eufy 2C cameras.
Thanks

![image](https://user-images.githubusercontent.com/83416371/157028389-826247d8-50e0-4f82-9b98-127192baf76b.png)

### Device Type

Indoor Camera (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v12 (Supported)

### Operating System

Raspbian 10+ (Supported)

**Comment by schliemann** [comment]
@csoprano Have you entered the correct country code that corresponds with your Eufy app?

**Comment by handy80** [comment]
Hi @schliemann same here with my installation. Entered "DE" as country like Germany (in the Eufy App). I did not enable 2FA, just a plain strong PW. Any Idea what could be the reason not showing (eufy wired doorbell 2K (T8200) in my case))

`{
            "platform": "EufySecurity",
            "username": "my email adress for the user for this eufy plugin",
            "password": "this is a password",
            "ignoreStations": [],
            "ignoreDevices": [],
            "enableCamera": true,
            "pollingIntervalMinutes": 30,
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 63,
            "enableDetailedLogging": 0,
            "country": "DE"
        }`

**Comment by schliemann** [comment]
@handy80 can you try to delete your browser cache and the plugin cache?

**Comment by handy80** [comment]
Hi @schliemann I can delete my local browser cache. and delete the plugin cache works in the homebridge settings? like on my following screenshot (sorry for the german terms)
<img width="1715" alt="image" src="https://user-images.githubusercontent.com/16490823/157518873-20a7a236-421f-4f5f-b39f-231c8ec7ce7e.png">

**Comment by schliemann** [comment]
Yeah. Please do both.

**Comment by handy80** [comment]
@schliemann still the same, deleted cache, delete plugin cache (caused some mess in homekit app now; device2room assignment) but eufy still don't show in the HB devices list. So I tried the config of the plugin again, but still no devices  shown/found
<img width="789" alt="image" src="https://user-images.githubusercontent.com/16490823/157522281-a6820240-a9a7-41bc-9248-6b436ccf93ae.png">

**Comment by karesake** [comment]
Es kann auch sein, dass du von Eufy gebannt wurdest. Also entweder in 24 Stunden noch einmal versuchen oder kurz einen zweiten Eufy Account anlegen und in der eufy App diesen einladen. 

_____

You may also have been banned by Eufy. So either try again in 24 hours or briefly create a second Eufy account and invite it in the eufy app.

**Comment by handy80** [comment]
@karesake kann ich das bannen eindeutig irgendwo testen?

**Comment by karesake** [comment]
Nicht wirklich. Da das anmelden in der Eufy App immer klappt. Aber über die API dann nicht … Versuch Dich mal hier anzumelden 

https://mysecurity.eufylife.com/

PS: Wenn Du nur die Doorbell hast, kannst Du den Haken bei „Enable Camera“ entfernen.

**Comment by handy80** [comment]
die Anmeldung hat auf der Seite funktioniert. Dieser Account ist bereits der zweit Account, den ich nur für die NUtzung mit dem Plugin angelegt habe. Der Account hat die Doorbell von Hauptaccount freigegeben bekommen. Der Plugin-Account hat erweiterte Berechtigungen auf der Geräte-Freigabe.
Noch eine Idee jetzt?

**Comment by handy80** [comment]
heute morgen sieht es weiterhin nicht gut aus
`[3/10/2022, 10:16:36 AM] [EufySecurity-1.0.8] DEBUG: Found 0 stations.

[3/10/2022, 10:16:36 AM] [EufySecurity-1.0.8] DEBUG: Found 0 devices.

[3/10/2022, 10:16:39 AM] [EufySecurity-1.0.8] DEBUG: Push Connected!`

**Comment by karesake** [comment]
Beta installieren. 
1.0.8 nutzt einen alten Eufy-Client.

**Comment by handy80** [comment]
ok, probier ich gern. wo finde ich die Beta (habe unter releases hier nichts gefunden) und wie installiere ich die idealerweise unter der homebridge ui?

**Comment by karesake** [comment]
Einfach im UI unter Plugins auf das Zahnrad ‚/Schraubenschlüssel und „install previews Version“

**Comment by handy80** [comment]
habe deinstalliert und dann die Version 1.1.1 installiert. Beim Setup Wizard User/PW eingegeben und beim Klick auf Next kommt schon eine Fehlermeldung "response is undefined" :-(

**Comment by handy80** [comment]
@karesake any update or other ideas? I would test also new beta if available. is there any issues known running HB on a synology using docker image?

**Comment by josh-blake** [comment]
The same thing happened to me - without any change in config or updates from HB etc. It looks like the devices just disappeared with the recent Eufy internal upgrades. It breaks when you have multiple accounts tied to the same home - have a look under your authorized users page on the app - you'll probably need to create a new authorised user for Eufy. To confirm this is the problem, disable 2FA in the app and try using your primary login credentials and you should see your devices again. Then add a newly created authorised user.

**Comment by handy80** [comment]
@josh-blake thanks for that. I did use my primary account now after having (just to be sure) logged off this user from all devices where I installed and used the eufy app. it worked. later I will create a new additional user to try if multi account still works. thanks a lot

**Comment by josh-blake** [comment]
I *think* the breakdown is how authentication is occurring between Eufy servers and the plugin, cause I can still log in via the Eufy app with my secondary logins. I have 2FA disabled however I am still prompted with a Captcha on login. In my setup, I have two Child Instances of EufySecurity on HomeBridge that control the same Eufy Devices and I specify the credentials in the config.json file. I cannot use the main Homebridge Eufy Security login screen (and thus cannot negotiate the captcha) as it only authenticates for one of the instances and removes the second one from the config.json file. I need two instances; one to expose my Wireless Doorbell to HomeKit / Apple, and the second to expose the same to Home Assistant (the Homebridge implementation is far superior to the implementations on Home Assistant, and allows the video feed to work etc).

**Comment by handy80** [comment]
@josh-blake I worked as a software consultant/implementer and I've seen user account set ups for customers in complex senarios and even apple is still sloppy in managing user accounts and all applications settings managed especially when it comes to applications and os updates. So all that glitters is not gold, if you ask me. maybe eufy is not that different there. Plus, I don't understand why there "normal" security cams are homekit certified and integrated but the doorbells are not.

**Comment by OskarLebuda** [comment]
Same issue here :(
I tried to connect my account where I have a Indoor Cam 2k. There are no devices :( 
I tried to share the device for other account and still nothing :(
Can someone help me with configuration?

**Comment by schliemann** [comment]
@OskarLebuda Have you tried creating a new account for the plugin?

**Comment by OskarLebuda** [comment]
@schliemann  Actually not. But why should I create new account. It means that my cloud storage has gone.

**Comment by schliemann** [comment]
@OskarLebuda A new guest account. Not a new main account.

**Comment by OskarLebuda** [comment]
I share the camera to the other admin account. Let me try to gues-account.

**Comment by OskarLebuda** [comment]
still same;
```
[3/12/2022, 5:10:38 PM] [EufySecurity-1.0.8] DEBUG: Found 0 stations.
[3/12/2022, 5:10:38 PM] [EufySecurity-1.0.8] DEBUG: Found 0 devices.
[3/12/2022, 5:10:39 PM] [EufySecurity-1.0.8] DEBUG: Push Connected!
```

But in my app i see the camera already:
![Screenshot_2022-03-12-17-11-25-964_com oceanwing battery cam](https://user-images.githubusercontent.com/10373127/158025685-a7a8fa7d-ce09-4dc3-ad02-fc422eba7d5f.jpg)

**Comment by OskarLebuda** [comment]
@schliemann

**Comment by schliemann** [comment]
@OskarLebuda And you have set the correct country?

**Comment by OskarLebuda** [comment]
@schliemann yes
```json
{
    "platform": "EufySecurity",
    "username": "***",
    "password": "***",
    "ignoreStations": [
        ""
    ],
    "ignoreDevices": [
        ""
    ],
    "enableCamera": true,
    "pollingIntervalMinutes": 30,
    "hkHome": 1,
    "hkAway": 0,
    "hkNight": 3,
    "hkOff": 63,
    "enableDetailedLogging": 0,
    "country": "PL"
}
```

**Comment by OskarLebuda** [comment]
any solution? @schliemann

**Comment by OskarLebuda** [comment]
I think I found the solution.
First of all I've install the `1.0.6` version. Configure it, then I've switch into beta `1.1.1-beta31` version and configure. The camera starts working properly.

Let me know if some had same problem :)

**Comment by sedonapup** [comment]
I see this same issue with my account. In Homebridge, my main eufy account shows all my devices in Homebridge Eufy Security table, but my guest(admin) account shows no devices. Meanwhile I can view all the devices in the eufy app from my guest account no problem. I have a US account and properly selected that each time. Is it possible there is something about these devices being shared rather than accessing through the main account? Also, does it matter if the guest account has been set up using share home or share devices?

**Comment by lenoxys** [comment]
please use beta

**Comment by ziggitipop** [comment]
> @csoprano Have you entered the correct country code that corresponds with your Eufy app?

How can I find the list of country codes? I’m in the UAE but I don’t know what the corresponding code for the country is (app only shows +971 which is the phone code)

**Comment by schliemann** [comment]
> > @csoprano Have you entered the correct country code that corresponds with your Eufy app?
> 
> How can I find the list of country codes? I’m in the UAE but I don’t know what the corresponding code for the country is (app only shows +971 which is the phone code)

AE

https://en.m.wikipedia.org/wiki/ISO_3166-1
