### ISSUE TITLE
Can you give more ways for donating?

### ISSUE THREAD

**Issue by MartinJRS** [samemory/homebridge-eufy-security#366]
### Describe the solution you'd like

Hi, I would like to support your project, can you add the "Donate" option, so that I can donate via PayPal?

![Bildschirmfoto 2022-03-14 um 12 07 34](https://user-images.githubusercontent.com/97555159/158161176-15f370a2-cdc6-4949-99a9-f8f947cb9666.png)

**Comment by MartinJRS** [comment]
Yes

**Comment by lenoxys** [comment]
Thanks for your support

Hum not sure how to make it fair since we're 3 peoples to work on it. If you want to donate please do for Homebridge dev team.
