### ISSUE TITLE
[Bug]: DONT UPDATE YOUR HOMEBASE (!!!!!)

### ISSUE THREAD

**Issue by karesake** [samemory/homebridge-eufy-security#371]
### What happened?

Don't Update your HomeBase to the newest 3.1.7.2!

I breaks everything! Stream no longer works...

Let's see what can be done there.

### Device Type

Station (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Mac OS X 11+ (Supported)

**Comment by lenoxys** [comment]
Hey should be @bropat put in the loop, no ?

**Comment by schliemann** [comment]
@karesake Which homebase model do you have?

**Comment by schliemann** [comment]
My homebase 2 on version 2.1.8.8.h is up to date and I don't have any issues.

**Comment by karesake** [comment]
<a href="https://ibb.co/sbk202N"><img src="https://i.ibb.co/sbk202N/38-FC27-BE-BD66-4-D36-9-B61-C637-B7-BB9964.png" alt="38-FC27-BE-BD66-4-D36-9-B61-C637-B7-BB9964" border="0"></a>

**Comment by schliemann** [comment]
Odd that your system version is so far ahead of mine while the subsystem version is identical.

**Comment by schliemann** [comment]
My homebase 2 was last updated on the 16th of february

![8DA3A173-E3B4-45E7-8047-F5D925412D7A](https://user-images.githubusercontent.com/10818044/160188311-956079e3-dba2-4953-8b0c-ddff56716cbc.png)

**Comment by karesake** [comment]
Works again. @schliemann  you can close it.

**Comment by schliemann** [comment]
@karesake What was the issue?

**Comment by saltysmith1** [comment]
Sorry to hijack this post, my 2 Homebase's have updated to 3.1.7.2H and now nothing is working is this just me or anyone having any issues, @karesake how did you  fix this you mentioned it works again.
