### ISSUE TITLE
No devices found, only in UI

### ISSUE THREAD

**Issue by bezibaerchen** [samemory/homebridge-eufy-security#374]
### What happened?

Dear all,

with using Beta I managed to get further with using this plugin. However, I now run into following issue:

In UI I see:

![image](https://user-images.githubusercontent.com/26967080/160840081-749324b3-774b-44da-b854-6b63495b623b.png)

Logfiles unfortunately says:

> [3/30/2022, 2:51:09 PM] [EufySecurity-1.1.1-beta.38] DEBUG: EufyClient connected true
> [3/30/2022, 2:51:09 PM] [EufySecurity-1.1.1-beta.38] DEBUG: PollingInterval: 30
> [3/30/2022, 2:51:09 PM] [EufySecurity-1.1.1-beta.38] DEBUG: Refresh data from cloud and schedule next refresh.
> [3/30/2022, 2:51:09 PM] [EufySecurity-1.1.1-beta.38] DEBUG: CameraMaxLivestreamDuration: 30
> [3/30/2022, 2:51:09 PM] [EufySecurity-1.1.1-beta.38] DEBUG: Found 0 stations.
> [3/30/2022, 2:51:09 PM] [EufySecurity-1.1.1-beta.38] DEBUG: Found 0 devices.

### Device Type

Doorbell (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Raspbian 10+ (Supported)

**Comment by bezibaerchen** [comment]
As found in Common issues I ignored the base and only kept doorbell - no change

**Comment by lenoxys** [comment]
Could you try the latest beta version ? We' ve introduce huge change just on the .38 with lot of bugs sorry. It may requires some beta version before having something stable.

Sorry!

**Comment by karesake** [comment]
Beta 40 … 

![Uploading 37D02838-2210-42D6-9370-1A463A01E88C.jpeg…]()

**Comment by bezibaerchen** [comment]
Went to beta.40, result still same:

> [3/31/2022, 8:41:42 AM] [EufySecurity-1.1.1-beta.40] DEBUG: EufyClient connected true
> [3/31/2022, 8:41:42 AM] [EufySecurity-1.1.1-beta.40] DEBUG: PollingInterval: 30
> [3/31/2022, 8:41:42 AM] [EufySecurity-1.1.1-beta.40] DEBUG: Refresh data from cloud and schedule next refresh.
> [3/31/2022, 8:41:42 AM] [EufySecurity-1.1.1-beta.40] DEBUG: CameraMaxLivestreamDuration: 30
> [3/31/2022, 8:41:42 AM] [EufySecurity-1.1.1-beta.40] DEBUG: Found 0 stations.
> [3/31/2022, 8:41:42 AM] [EufySecurity-1.1.1-beta.40] DEBUG: Found 0 devices.

**Comment by bezibaerchen** [comment]
Also seeing same error as @karesake

**Comment by bezibaerchen** [comment]
So change is that I now don't see devices in UI either...

**Comment by lenoxys** [comment]
Please refresh your browser cache

**Comment by bezibaerchen** [comment]
> Please refresh your browser cache

Same unfortunately

**Comment by bezibaerchen** [comment]
![image](https://user-images.githubusercontent.com/26967080/160999358-8ca271fd-7799-4216-8916-43cfc5305716.png)

This happens with a browser that never accessed Homebridge UI

**Comment by lenoxys** [comment]
> Beta 40 … no devices found 
> 
> 
> 
> <a href="https://ibb.co/jTLzcjb"><img src="https://i.ibb.co/jTLzcjb/261828-C4-9458-47-A7-B70-D-EC826-CA790-A0.jpg" alt="261828-C4-9458-47-A7-B70-D-EC826-CA790-A0" border="0"></a>
> 
> 

@karesake  Please use #375 was working before

**Comment by lenoxys** [comment]
Which eufy devices do you have on your setup ?

**Comment by bezibaerchen** [comment]
doorbeel and 2 outdoor cameras. Looking at the doorcam only. From what I see config isn't written at all, will try to set manually.

**Comment by bezibaerchen** [comment]
Some more insights:

> [3/31/2022, 9:38:24 AM] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /init
> [3/31/2022, 9:38:26 AM] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /auth
> [3/31/2022, 9:38:26 AM] [Homebridge UI] [homebridge-eufy-security] [1.1.1-beta.40] INFO:  config: {"language":"en","persistentDir":"/var/lib/homebridge/eufysecurity","p2pConnectionSetup":0,"pollingIntervalMinutes":10,"eventDurationSeconds":10,"acceptInvitations":true,"username":"<username>","password":"<password>","country":"DE"}
> [3/31/2022, 9:38:26 AM] [Homebridge UI] [homebridge-eufy-security] [1.1.1-beta.40] INFO:  country: DE
> [3/31/2022, 9:38:28 AM] [Homebridge UI] [homebridge-eufy-security] [1.1.1-beta.40] INFO:  AuthResult.OK
> [3/31/2022, 9:38:28 AM] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /refreshData
> [3/31/2022, 9:38:32 AM] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /getStations
> [3/31/2022, 9:38:32 AM] [Homebridge UI] [homebridge-eufy-security] [1.1.1-beta.40] ERROR: error: undefined
> [3/31/2022, 9:38:32 AM] [Homebridge UI] [homebridge-eufy-security] [1.1.1-beta.40] INFO:  Push notification connection successfully established

**Comment by bezibaerchen** [comment]
I was digging around in logfile and maybe stumbled over something:

> {"name":"[EufySecurity-1.1.1-beta.40]","hostname":"debobpi001","pid":29569,"level":30,"msg":"Retry to register/login for push notification in 50 seconds...","time":"2022-03-31T06:55:34.791Z","v":0}
> {"name":"[EufySecurity-1.1.1-beta.40]","hostname":"debobpi001","pid":29569,"level":30,"msg":"Retry to register/login for push notification","time":"2022-03-31T06:56:24.792Z","v":0}
> {"name":"[EufySecurity-1.1.1-beta.40]","hostname":"debobpi001","pid":29569,"level":20,"msg":"Create new push credentials...","time":"2022-03-31T06:56:24.793Z","v":0}
> {"name":"[EufySecurity-1.1.1-beta.40]","hostname":"debobpi001","pid":29569,"level":50,"msg":"registerFid - Error: RequestError: connect ECONNREFUSED 127.0.0.1:443\n    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-eufy-security/node_modules/got/dist/source/core/index.js:962:111)\n    at Object.onceWrapper (node:events:646:26)\n    at ClientRequest.emit (node:events:538:35)\n    at ClientRequest.origin.emit (/usr/lib/node_modules/homebridge-eufy-security/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at TLSSocket.socketErrorListener (node:_http_client:442:9)\n    at TLSSocket.emit (node:events:526:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {\n  code: 'ECONNREFUSED',\n  timings: {\n    start: 1648709791912,\n    socket: 1648709791912,\n    lookup: 1648709791913,\n    connect: undefined,\n    secureConnect: undefined,\n    upload: undefined,\n    response: undefined,\n    end: undefined,\n    error: 1648709791914,\n    abort: undefined,\n    phases: {\n      wait: 0,\n      dns: 1,\n      tcp: undefined,\n      tls: undefined,\n      request: undefined,\n      firstByte: undefined,\n      download: undefined,\n      total: 2\n    }\n  }\n}","time":"2022-03-31T06:56:31.916Z","v":0}
> {"name":"[EufySecurity-1.1.1-beta.40]","hostname":"debobpi001","pid":29569,"level":50,"msg":"registerFid - Status return code not 200 { status: undefined, statusText: undefined, data: undefined }","time":"2022-03-31T06:56:31.917Z","v":0}
> {"name":"[EufySecurity-1.1.1-beta.40]","hostname":"debobpi001","pid":29569,"level":50,"msg":"registerFid - Generic Error: Error: FID registration failed with error: undefined\n    at PushNotificationService.registerFid (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:88:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at PushNotificationService.createPushCredentials (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:145:16)\n    at PushNotificationService._open (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:528:32)\n    at PushNotificationService.open (/usr/lib/node_modules/homebridge-eufy-security/rity-1.1.1-beta.40]","hostname":"debobpi001","pid":29569,"level":50,"msg":"Create push credentials Error: Error: FID registration failed with error: Error: FID registration failed with error: undefined\n    at PushNotificationService.registerFid (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:92:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at PushNotificationService.createPushCredentials (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:145:16)\n    at PushNotificationService._open (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:528:32)\n    at PushNotificationService.open (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:592:13)\n    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:603:21)","time":"2022-03-31T06:56:31.930Z","v":0}
> {"name":"[EufySecurity-1.1.1-beta.40]","hostname":"debobpi001","pid":29569,"level":30,"msg":"Push notification connection closed","time":"2022-03-31T06:56:31.931Z","v":0}
> {"name":"[EufySecurity-1.1.1-beta.40]","hostname":"debobpi001","pid":29569,"level":50,"msg":"Push notifications are disabled, because the registration failed!","time":"2022-03-31T06:56:31.933Z","v":0}
> {"name":"[EufySecurity-1.1.1-beta.40]","hostname":"debobpi001","pid":29569,"level":30,"msg":"Retry to register/login for push notification in 120 seconds...","time":"2022-03-31T06:56:31.933Z","v":0}node_modules/eufy-security-client/src/push/service.ts:592:13)\n    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:603:21)","time":"2022-03-31T06:56:31.929Z","v":0}
> {"name":"[EufySecrity-1.1.1-beta.40]","hostname":"debobpi001","pid":29569,"level":50,"msg":"Create push credentials Error: Error: FID registration failed with error: Error: FID registration failed with error: undefined\n    at PushNotificationService.registerFid (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:92:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at PushNotificationService.createPushCredentials (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:145:16)\n    at PushNotificationService._open (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:528:32)\n    at PushNotificationService.open (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:592:13)\n    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:603:21)","time":"2022-03-31T06:56:31.930Z","v":0}
> {"name":"[EufySecurity-1.1.1-beta.40]","hostname":"debobpi001","pid":29569,"level":30,"msg":"Push notification connection closed","time":"2022-03-31T06:56:31.931Z","v":0}
> {"name":"[EufySecurity-1.1.1-beta.40]","hostname":"debobpi001","pid":29569,"level":50,"msg":"Push notifications are disabled, because the registration failed!","time":"2022-03-31T06:56:31.933Z","v":0}
> {"name":"[EufySecurity-1.1.1-beta.40]","hostname":"debobpi001","pid":29569,"level":30,"msg":"Retry to register/login for push notification in 120 seconds...","time":"2022-03-31T06:56:31.933Z","v":0}urity-1.1.1-beta.40]","hostname":"debobpi001","pid":29569,"level":50,"msg":"Create push credentials Error: Error: FID registration failed with error: Error: FID registration failed with error: undefined\n    at PushNotificationService.registerFid (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:92:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at PushNotificationService.createPushCredentials (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:145:16)\n    at PushNotificationService._open (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:528:32)\n    at PushNotificationService.open (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:592:13)\n    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:603:21)","time":"2022-03-31T06:56:31.930Z","v":0}
> {"name":"[EufySecurity-1.1.1-beta.40]","hostname":"debobpi001","pid":29569,"level":30,"msg":"Push notification connection closed","time":"2022-03-31T06:56:31.931Z","v":0}
> {"name":"[EufySecurity-1.1.1-beta.40]","hostname":"debobpi001","pid":29569,"level":50,"msg":"Push notifications are disabled, because the registration failed!","time":"2022-03-31T06:56:31.933Z","v":0}
> {"name":"[EufySecurity-1.1.1-beta.40]","hostname":"debobpi001","pid":29569,"level":30,"msg":"Retry to register/login for push notification in 120 seconds...","time":"2022-03-31T06:56:31.933Z","v":0}

What got my attention is this ECONNREFUSED 127.0.0.1:443

**Comment by karesake** [comment]
So I skipped entering the user data, restarted the HomeBridge and then created the config manually. This is how it works first.

**Comment by bezibaerchen** [comment]
> So I skipped entering the user data, restarted the HomeBridge and then created the config manually. This is how it works first.

Did you create the config within config.json in the plugin itself or in main config file?

**Comment by bezibaerchen** [comment]
Now it is doing something! Needed a combination of manual config, then going in GUI again to answer captcha, multiple restarts, but I see the camera now!

**Comment by fullphat** [comment]
Can you share your manual config?

**Comment by bezibaerchen** [comment]
> Can you share your manual config?

>       {
>             "platform": "EufySecurity",
>             "name": "EufySecurity",
>             "username": "<mailaddress>",
>             "password": "<password>",
>             "country": "DE",
>             "enableDetailedLogging": 1
>         }

**Comment by bezibaerchen** [comment]
UI isnt working for me a hundred percent either, but devices I shared with this account are showing up.

**Comment by fullphat** [comment]
Because I deleted my configuration my single device has now disappeared.  Should have taken a backup... 🙄

**Comment by fullphat** [comment]
Update on my situation.  I realised I hadn't unbridged the plugin after recreating the config so I've done that and rebooted HomeBridge.  Now I have a single alarm system with camera and associated light and motion switches, but also a second camera.

The camera with associated alarm system shows the thumbnail but won't stream.  The second camera is simply "no response".

Settings UI still doesn't work.

**Comment by lenoxys** [comment]
@bezibaerchen please check the latest one if you want you can look at beta page on wiki if you want to know how to revert into an older beta release

**Comment by bezibaerchen** [comment]
> @bezibaerchen please check the latest beta version if you want you can look at beta page on wiki if you want to know how to revert into an older beta release

I installed latest Beta. However I had to remove the sharing for one device. I will install new one and share over the weekend, will then give it another try.
