### ISSUE TITLE
[Bug]: beta .40 has completely broken my T8420

### ISSUE THREAD

**Issue by fullphat** [samemory/homebridge-eufy-security#375]
### What happened?

Installed Beta .40 and I now have two instances of my outdoor floodlight camera but neither work.

If I go to the settings UI and hit "list devices" I get an error (null evaluating station.length).  If I hit "refresh" I get the same error.

beta.33 worked great for me - how do I roll back to this one?

### Device Type

Floodlight (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Mac OS X 11+ (Supported)

**Comment by lenoxys** [comment]
Please refresh your browser cache

**Comment by karesake** [comment]
> Please refresh your browser cache

didnt help

**Comment by fullphat** [comment]
How do I refresh my browser cache on iOS Safari?

At the moment I have no plugin configuration at all in the HomeBridge config file and no way of adding one (other than manually).

**Comment by lenoxys** [comment]
please test the latest one. You might need to clear accessory cache from Homebrige UI for camera you turn into unbridge mode.

**Comment by fullphat** [comment]
> make sure if RTSP is enabled to enable it aswell on Eufy App

The floodlight camera I have doesn't support RTSP.

**Comment by fullphat** [comment]
> please test the latest one. You might need to clear accessory cache from Homebrige UI for camera you turn into unbridge mode.

Installed beta.41 and now I have no settings UI at all.

**Comment by fullphat** [comment]
Sorry, here you go:

![205F2E69-C5E8-4C7F-B10E-C3F6D4E89E4C](https://user-images.githubusercontent.com/11242840/161157171-f8ea1e7e-9dab-420a-ae19-ecd5d6dffa94.png)

**Comment by lenoxys** [comment]
Looks like browser issue. Can you test on chrome or Firefox ?

**Comment by lenoxys** [comment]
I would say using iPhone or iPad to troubleshoot beta version isn't ideal

**Comment by wilbsww** [comment]
UI shows up in chrome, still can't log in via refresh, show device list, and log shows:

[31/03/2022, 18:32:10] [homebridge-eufy-security] Country set: US
Error: EEXIST: file already exists, copyfile '/var/lib/homebridge/persistent.json' -> '/var/lib/homebridge/eufysecurity/persistent.json'
    at Object.copyFileSync (node:fs:2800:3)
    at new EufySecurityPlatform (/usr/local/lib/node_modules/homebridge-eufy-security/src/platform.ts:134:10)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:134:42)
[31/03/2022, 18:32:10] [homebridge-eufy-security] Child bridge process ended
[31/03/2022, 18:32:10] [homebridge-eufy-security] Process Ended. Code: 1, Signal: null

On repeat still

**Comment by lenoxys** [comment]
> UI shows up in chrome, still can't log in via refresh, show device list, and log shows:
> 
> 
> 
> [31/03/2022, 18:32:10] [homebridge-eufy-security] Country set: US
> 
> Error: EEXIST: file already exists, copyfile '/var/lib/homebridge/persistent.json' -> '/var/lib/homebridge/eufysecurity/persistent.json'
> 
>     at Object.copyFileSync (node:fs:2800:3)
> 
>     at new EufySecurityPlatform (/usr/local/lib/node_modules/homebridge-eufy-security/src/platform.ts:134:10)
> 
>     at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:134:42)
> 
> [31/03/2022, 18:32:10] [homebridge-eufy-security] Child bridge process ended
> 
> [31/03/2022, 18:32:10] [homebridge-eufy-security] Process Ended. Code: 1, Signal: null
> 
> 
> 
> On repeat still

Hello can you open a new issue with your error ? Not easy to work on a single issue within only one thread. Let's keep things separate. Appreciate your help on this.

**Comment by fullphat** [comment]
Reverted to beta.33.
