### ISSUE TITLE
[Bug]: beta.40 settings broken

### ISSUE THREAD

**Issue by fullphat** [samemory/homebridge-eufy-security#376]
### What happened?

Trying to fix my issue, I hit "reset everything" in the settings UI.  This generated an error but did apparently delete all my settings.

Now when I enter my credentials and tap "next" I get another error and my settings aren't saved even though I get a green message saying they are.

If I try to restart the bridge I get an error saying the plugin must be configured first.

beta.33 worked great for me, how do I roll back to that?

### Device Type

Floodlight (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Mac OS X 11+ (Supported)

**Comment by lenoxys** [comment]
Duplicate #345
