### ISSUE TITLE
[Bug]: Beta 41 only shows UI in chrome; cannot login (new setup or refresh), no devices shown

### ISSUE THREAD

**Issue by wilbsww** [samemory/homebridge-eufy-security#377]
### What happened?

Mentioned in the previous beta 40 thread; when on beta 41: unless using Chrome, the UI doesn't show. Whether on a fresh install or an upgrade, beta 41 doesn't allow login or refresh login. As such, the device list doesn't show. Additionally, the log goes into a boot loop showing the attached log

### Device Type

Indoor Camera (Supported)

### Plugin Version

beta (Best Effort)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v14 (Supported)

### Operating System

Raspbian 10+ (Supported)

### Relevant log output

```shell
[31/03/2022, 18:32:10] [homebridge-eufy-security] Country set: US

Error: EEXIST: file already exists, copyfile '/var/lib/homebridge/persistent.json' -> '/var/lib/homebridge/eufysecurity/persistent.json'

at Object.copyFileSync (node:fs:2800:3)

at new EufySecurityPlatform (/usr/local/lib/node_modules/homebridge-eufy-security/src/platform.ts:134:10)

at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:134:42)
[31/03/2022, 18:32:10] [homebridge-eufy-security] Child bridge process ended

[31/03/2022, 18:32:10] [homebridge-eufy-security] Process Ended. Code: 1, Signal: null
```

**Comment by karesake** [comment]
**Got the same.** 

_Ordered Netatmo Doorbell and Outdoor Cameras today. Bye!_

**Comment by karesake** [comment]
Yes. I've had enough worrying about it every single day. 

Not through the plugin but through Eufy.

Nothing more HomeKit-enabled Products will come from the company either. Everything that is published are half-finished products where the software is not thought through to the end. Cameras that cannot use real RTSP. Cameras that cannot be connected to the HomeBase, making the built-in siren absolutely useless. An app crammed with ads.

And then let's be honest. Not even the 2c cameras are really HomeKit compatible, only the HomeBase. If one day Eufy closes the API or shuts down the servers, that's it.

The Netatmo have a real HomeKit code and can therefore be operated without a manufacturer app. 

**If you want to buy a large Eufy package, get in touch. Shipping from Germany to France shouldn't be a problem.**

**Comment by lenoxys** [comment]
identify a bug on Bropat lib I've open a case : https://github.com/bropat/eufy-security-client/issues/136

**Comment by lenoxys** [comment]
@karesake, fully understand! shame to have homebase but rely on Cloud API to work.

I've already have a huge setup on my own miss the floodlight but it will be for test purpose only.

**Comment by wilbsww** [comment]
@lenoxys I am, even changed the password to make sure nothing was going wrong on that end.

**Comment by lenoxys** [comment]
@wilbsww another thing before we need to dig further, can you follow the [reset procedure](https://github.com/samemory/homebridge-eufy-security/wiki/Basic-Troubleshooting#reset--clear) ?

**Comment by wilbsww** [comment]
@lenoxys tried reset multiple times over; ended up having to revert to beta 33. The child bridge was rebooting so many times it would eventually crash the whole home bridge instance. If it wasn't set up as a child bridge, then the whole instance would crash right away. 

Happy to set up something remote and work on things though!

**Comment by lenoxys** [comment]
let's have a look : https://meet.google.com/ahb-cfyd-net

**Comment by lenoxys** [comment]
ok looks fixed, we did see other bugs during the session but nothing related to the one described above. Closing this one.

I will open a new one with duplicate bridge camera.
