### ISSUE TITLE
[enhancement]: Support Doorbell Dual

### ISSUE THREAD

**Issue by bezibaerchen** [samemory/homebridge-eufy-security#379]
### Describe the solution you'd like

Please add support for Doorbell Dual.

Currently (Beta 43):

> [4/3/2022, 10:10:19 AM] [EufySecurity-1.1.1-beta.43] DEBUG: CameraMaxLivestreamDuration: 30
> [4/3/2022, 10:10:19 AM] [EufySecurity-1.1.1-beta.43] DEBUG: Found 1 stations.
> [4/3/2022, 10:10:19 AM] [EufySecurity-1.1.1-beta.43] DEBUG: Found Station <serial> Fuchsbau Home Base STATION { value: '192.168.1.187', timestamp: 1648912003000 }
> [4/3/2022, 10:10:19 AM] [EufySecurity-1.1.1-beta.43] DEBUG: Found 1 devices.
> [4/3/2022, 10:10:19 AM] [EufySecurity-1.1.1-beta.43] DEBUG: Found device <serial> Doorbell undefined
> [4/3/2022, 10:10:19 AM] [EufySecurity-1.1.1-beta.43] DEBUG: Fuchsbau Home Base UUID: <UUID>
> [4/3/2022, 10:10:19 AM] [EufySecurity-1.1.1-beta.43] DEBUG: Fuchsbau Home Base Constructed Station
> [4/3/2022, 10:10:19 AM] [EufySecurity-1.1.1-beta.43] INFO:  Updating accessory: Fuchsbau Home Base
> [4/3/2022, 10:10:19 AM] [EufySecurity-1.1.1-beta.43] DEBUG: Doorbell UUID: <UUID>
> [4/3/2022, 10:10:19 AM] [EufySecurity-1.1.1-beta.43] WARN:  This accessory is not compatible with HomeBridge Eufy Security plugin: Doorbell Type: 91
> [4/3/2022, 10:10:20 AM] [EufySecurity-1.1.1-beta.43] DEBUG: Fuchsbau Home Base GET StationCurrentMode: { value: 3, timestamp: 1648912003000 }
> [4/3/2022, 10:10:20 AM] [EufySecurity-1.1.1-beta.43] DEBUG: Fuchsbau Home Base GET StationCurrentMode: { value: 3, timestamp: 1648912003000 }
> [4/3/2022, 10:10:23 AM] [EufySecurity-1.1.1-beta.43] DEBUG: Fuchsbau Home Base GET StationCurrentMode: { value: 3, timestamp: 1648912003000 }
> [4/3/2022, 10:10:23 AM] [EufySecurity-1.1.1-beta.43] DEBUG: Fuchsbau Home Base GET StationCurrentMode: { value: 3, timestamp: 1648912003000 }
> 
>

**Comment by bezibaerchen** [comment]
Addition:

Offical Model / Device should be T8213

**Comment by lenoxys** [comment]
This need to be supported first on the @bropat lib, I'm not sure how to handle 2 cameras not sure you will get the same experience than on Eufy APP

**Comment by bezibaerchen** [comment]
I definitely dont need both cams :-) But I get your point. Awaiting patiently then.

**Comment by bezibaerchen** [comment]
Obviously kinda working already:

https://github.com/bropat/eufy-security-client/issues/126

**Comment by lenoxys** [comment]
https://github.com/homebridge-eufy-security/plugin/issues/5

**Comment by lenoxys** [comment]
please use the link above to update. I'm locking this topics since we're moving into a new repo. Sorry for the inconvenience.
