### ISSUE TITLE
[Bug]: "Push Closed" Constant in Logs

### ISSUE THREAD

**Issue by saltysmith1** [samemory/homebridge-eufy-security#380]
### What happened?

not sure if its a bug or not but recently in my logs im getting Push Closed! repeated like every 30 ish seconds have included a screen shot of the problem

hope someone can help thanks 
<img width="576" alt="Screenshot 2022-04-03 at 12 58 35" src="https://user-images.githubusercontent.com/87123578/161427057-b905e663-c3fe-4b5d-8e2e-20776701420a.png">

### Device Type

Station (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

**Comment by lenoxys** [comment]
This is normal behavior. On the last beta we've remove a lot of info message. This will be reflected soon on main branch

**Comment by saltysmith1** [comment]
Thanks for your reply i will close this now
