### ISSUE TITLE
[enhancement]: Support for Eufy Video Doorbell Dual

### ISSUE THREAD

**Issue by bambam1979** [samemory/homebridge-eufy-security#383]
### Describe the solution you'd like

Hello, first of all a big thank you for your great work. The plugin is really great and works without any problems. But I have one big request. I bought the Dual Doorbell from Dufy. Unfortunately, this is not yet supported by the plugin. It is marked as "undefined" under Type and is not included. A support would be really great.
Thanks, Enrico

**Comment by bambam1979** [comment]
Yes

**Comment by jbh8063** [comment]
Following

**Comment by bezibaerchen** [comment]
+1
I opened https://github.com/samemory/homebridge-eufy-security/issues/379 for this already.
Maybe I did it wrong :-)

**Comment by lenoxys** [comment]
please use the link above to update. I'm locking this topics since we're moving into a new repo. Sorry for the inconvenience.
