### ISSUE TITLE
[Bug]: Homebase not changing modes

### ISSUE THREAD

**Issue by smelly3443** [samemory/homebridge-eufy-security#385]
### What happened?

When changing modes in homekit, Homebase mode doesn't change from arming.  Im using Hoobs.

### Device Type

Station (Supported)

### Plugin Version

other (UnSupported)

### HomeBridge Version

other (UnSupported)

### NodeJS Version

other (UnSupported)

### Operating System

Raspbian 10+ (Supported)

**Comment by lenoxys** [comment]
Should be fixed.
