### ISSUE TITLE
[Bug]: HomeBase stays on "Triggered"

### ISSUE THREAD

**Issue by mariomaz87** [samemory/homebridge-eufy-security#388]
### What happened?

Hi, when my alarm is triggered, in HomeKit the Homebase is "Triggered" and I can't get it back to its previous state by changing the status either from HomeKit or Eufy app. If I change to another status, after a few minutes it goes back to triggered. I have to reset HomeBridge. I tried also with the latest beta. Thanks!

### Device Type

Station (Supported)

### Plugin Version

v1.0.x (Supported)

### HomeBridge Version

v1.4.x (Supported)

### NodeJS Version

v16 (Supported)

### Operating System

Raspbian 10+ (Supported)

**Comment by mariomaz87** [comment]
> Did you check this [Common Issues](https://github.com/samemory/homebridge-eufy-security/wiki/Common-Issues) pages ?

Yes, but I did not find anything about my issue. By installing the beta I also started from scratch with the configuration

**Comment by lenoxys** [comment]
should be fixed by #385

**Comment by mariomaz87** [comment]
> should be fixed by #385

Yep, the problem is fixed with the latest beta. Thanks!

**Comment by mariomaz87** [comment]
I have a different issue now, I don’t know if it’s related. I can “dismiss” the triggered status now, but after a few minutes I get another HomeKit alert and the Eufy Base is triggered again. In Eufy app I don’t have any notification. I have to restart HomeBridge to stop the alerts.

**Comment by lenoxys** [comment]
Can you open a new issue please ? Describing what your facing and with debug log associated ? Thanks !
