### ISSUE TITLE
HomeBase Security Status switch off - but no reaction in HomeKit.

### ISSUE THREAD

**Issue by karesake** [samemory/homebridge-eufy-security#39]
Hi there,

Found a little Problem. We use the KeyPad to switch the Security Modes. The "Away" und "Home" Mode works great but if I click the "Off" Button, only the Eufy HomeBase switch to "off" mode - no reaction in HomeKit. 

To change the plugin settings does not work.

**Comment by schliemann** [comment]
Have you mapped Eufy off mode to Homekit off mode?

export enum GuardMode {    UNKNOWN = -1,    AWAY = 0,    HOME = 1,    DISARMED = 63,    SCHEDULE = 2,    GEO = 47,    CUSTOM1 = 3,    CUSTOM2 = 4,    CUSTOM3 = 5,    OFF = 6}

**Comment by karesake** [comment]
Its correctly Set. HomeBase switchs to „Off“ but no response in HomeKit. 

Whether I use "63" or "6".

**Comment by schliemann** [comment]
But you do get notifications on setting Away mode?

**Comment by karesake** [comment]
Yes. Away and Home Mode are working great. The HomeBase switch to the right mode and HomeKit also. Only the off Mode not.

**Comment by schliemann** [comment]
I will try and test it tonight.

**Comment by PeterAlexander75** [comment]
Tested. I can can confirm this is the case for me, too.

```
 "username": "username",
            "password": "password",
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 63,
            "platform": "EufySecurity"
```

**Comment by schliemann** [comment]
@PeterAlexander75 hkOff should be "6" to work with eufy off.

**Comment by PeterAlexander75** [comment]
Set to 6, rebooted homebridge, same result.

**Comment by karesake** [comment]
Also with 6 only HomeBase is in Off Mode. 

<a href="https://ibb.co/2j9n4P5"><img src="https://i.ibb.co/2j9n4P5/21685-B01-DFAD-4-EA4-A165-1-D77-F0-EE873-B.jpg" alt="21685-B01-DFAD-4-EA4-A165-1-D77-F0-EE873-B" border="0"></a> <a href="https://ibb.co/6wsrpyh"><img src="https://i.ibb.co/6wsrpyh/CE8-C76-F5-4-CE9-4307-BDAB-5-CF24024-F30-D.jpg" alt="CE8-C76-F5-4-CE9-4307-BDAB-5-CF24024-F30-D" border="0"></a>

Nothing when switch to off Mode 

<a href="https://ibb.co/0yDnW89"><img src="https://i.ibb.co/0yDnW89/FB389-B50-16-F0-4-D33-86-A5-F0-F32-EEF66-BF.jpg" alt="FB389-B50-16-F0-4-D33-86-A5-F0-F32-EEF66-BF" border="0"></a>

but when switch to Away or home mode 

<a href="https://ibb.co/Cz5Pq6n"><img src="https://i.ibb.co/Cz5Pq6n/CB06-F0-FC-AC8-E-4389-B489-7724-D7-C5-CA19.jpg" alt="CB06-F0-FC-AC8-E-4389-B489-7724-D7-C5-CA19" border="0"></a>

**Comment by schliemann** [comment]
Might be a problem with the eufy-security-client then.

**Comment by lenoxys** [comment]
Code 6 is triggered  when disabled  by Keypad instead of 63. Confirmed on my lab. I'm pushing the change.

**Comment by lenoxys** [comment]
#41

**Comment by schliemann** [comment]
@lenoxys Can you elaborate on what in your PR fixed the event not being triggered. I can see you added "this.eufyStation.connect()". I thought the station already had a connection when the connection is established in the platform startup?

**Comment by lenoxys** [comment]
Hhaaa I forget to remove this line I was trying p2p. I will push the tentative to fix the motion on doorbell and remove this one

**Comment by schliemann** [comment]
Perfect and awesome work you did. But how did you fix the off mode?

**Comment by lenoxys** [comment]
Line 164 in SecuritySystemPlatformAccessory.ts
`      case 6: // 6 is triggered  when disabled  by Keypad
        return this.convertMode(63);`

Code 6 mean disarmed means everything is desactivated. while 63 it's desactivated but you can still enable thing.

**Comment by schliemann** [comment]
I get it now. Thought it was already mapped there. Apparantly not. Great work 👍🏻

**Comment by schliemann** [comment]
Tested and solved. Please close.

**Comment by schliemann** [comment]
@samemory please close this.
