### ISSUE TITLE
Open/Close trigger is not implemented

### ISSUE THREAD

**Issue by coryforman** [samemory/homebridge-eufy-security#391]
Just got a new Eufy smart lock (the finger print version with WiFi) and verified it’s on the compatible list per documentation. 

When re-configuring my Eufy setup, it finds the lock and adds it into HomeKit. When I unlock the door, it just gets stuck on “unlocking…” and nothing happens. I viewed the logs for HomeBridge and see the following error:

[10/04/2022, 17:40:31] [EufySecurity] Open/Close trigger is not implemented

Any help would be appreciated.

**Comment by lenoxys** [comment]
Did you use beta version ?

**Comment by coryforman** [comment]
> Did you use beta version ?

Negative, I am on the latest stable (1.0.8).

**Comment by lenoxys** [comment]
Lock feature is available on beta only.

**Comment by coryforman** [comment]
> Lock feature is available on beta only.

Ah got it, thank you for the answer (and all your work on this plugin). I believe I saw somewhere the latest beta is set to go stable within the next 2 weeks?

**Comment by lenoxys** [comment]
yes, you can track it into our new repo : 

https://github.com/homebridge-eufy-security/plugin/issues/1
