### ISSUE TITLE
Bug vidéo battery doorbell

### ISSUE THREAD

**Issue by technikosoldat** [samemory/homebridge-eufy-security#46]
Hello, I updated to 0.2.3. The chime on the homepod and notifications to indicate that a person has ringed works. But there is always a problem with the video stream. The video stream on the thumbnails does not update, and when we want to see the bell camera, I have a eufy white screen that lasts more than a minute before seeing the video appear. To give an example, I watched the video of my camera last night at 11 p.m. I have a person who rang this morning. When I go to the home app, on the thumbnail of the doorbell camera I still have last night's photo and not the image of the person who rang this morning. In any case, thank you for the work you do, updates arrive regularly and I am extremely happy with them. Good luck for the future

**Comment by schliemann** [comment]
@lenoxys Pretty sure https://github.com/samemory/homebridge-eufy-security/blob/108274f5c620c61ad5f865dfc1155c80225119ef/src/streamingDelegate.ts#L210 should have a ".value" in the end since the object returned contains both url and timestamp.

**Comment by lenoxys** [comment]
Hey ! got a compilation error with the `.value`

On my lab it does. the url is the latest one but streamdelegate doesn't take care of it.

**Comment by lenoxys** [comment]
Lol just put back the .value and it's working without compilation issue
>.<

**Comment by schliemann** [comment]
Yeah. Only issue then is that the getLastCameraImageURL() doesn't update unless an event is triggered for the camera. My last screenshot is still my neighbor walking around with a broom :)

**Comment by lenoxys** [comment]
I do receive the url every minute but the screenshot won't change if nothing happened at the camera level. Not sure we should force to retrieve one since it could impact the battery.

**Comment by schliemann** [comment]
I have created an issue on bropats repo.

**Comment by schliemann** [comment]
@lenoxys If you have time at some point it would be awesome if you could verify if the pr from the client library automatically can push the picture url.

https://github.com/bropat/eufy-security-client/pull/20

**Comment by lenoxys** [comment]
> @lenoxys If you have time at some point it would be awesome if you could verify if the pr from the client library automatically can push the picture url.
> 
> [bropat/eufy-security-client#20](https://github.com/bropat/eufy-security-client/pull/20)

Yeah it does update when motion is triggered

**Comment by schliemann** [comment]
But not on doorbell pressed.

**Comment by lenoxys** [comment]
Yeah you're right

**Comment by schliemann** [comment]
Are you sure? I do definetely receive a push notification on my iphone with a snapshot on my phone.

**Comment by lenoxys** [comment]
Sure if recording disabled nothing updated if recording enabled I got the snap

**Comment by schliemann** [comment]
When you say recording enabled do you then mean this hightligted setting?

![A2E5F2C9-8199-43A4-85F4-9CAF00F204F1](https://user-images.githubusercontent.com/10818044/123613743-fb723700-d803-11eb-9b6a-fa50fb51a9cc.jpeg)

**Comment by lenoxys** [comment]
![image](https://user-images.githubusercontent.com/3996456/123623844-337e7780-d80e-11eb-8346-890cde2a7854.png)

No, I was talking about the security profile

**Comment by schliemann** [comment]
Duplicate of https://github.com/samemory/homebridge-eufy-security/issues/28. Please close.

**Comment by lenoxys** [comment]
Duplicate of #28. Closing
