### ISSUE TITLE
Shouldn't we just pass eufy mode so the user can handle mapping in config?

### ISSUE THREAD

**Issue by schliemann** [samemory/homebridge-eufy-security#47]
I'm not quite sure about the last PR change regarding differences between using the "disarmed" and "off" mode.

https://github.com/samemory/homebridge-eufy-security/blob/108274f5c620c61ad5f865dfc1155c80225119ef/src/securitySystemPlatformAccessory.ts#L167

Wouldn't the correct thing be to let the user map this in the config instead? The "off" mode has the advantage that it is configurable. Which "Disarmed" isn't.

**Comment by schliemann** [comment]
What do you think @lenoxys?

**Comment by lenoxys** [comment]
I'm okay ! I've put the change in the PR #45
