### ISSUE TITLE
Get Alarm event

### ISSUE THREAD

**Issue by lenoxys** [samemory/homebridge-eufy-security#51]
Getting alarm event and triggering into home app

Waiting approval from bropat because we use his Eufy-security-client lib to get event :

Tracking the PR here : https://github.com/bropat/eufy-security-client/pull/18

**Comment by technikosoldat** [comment]
👍🏼

**Comment by schliemann** [comment]
I can confirm this works.
https://user-images.githubusercontent.com/10818044/126342420-2e4459ce-126a-45fb-bf30-ce34e378f1c3.MOV

**Comment by schliemann** [comment]
I believe the issue can be closed.

**Comment by lenoxys** [comment]
Alarm now trigger!
