### ISSUE TITLE
Bug Doorbell

### ISSUE THREAD

**Issue by technikosoldat** [samemory/homebridge-eufy-security#55]
Hello team, there are 2 bugs concerning the bell. The first bug is that when a person rings we receive two notifications on the phone and the homepod rings twice. The second Bug is the fact that the video of the doorbell on the home application takes about thirty seconds to appear, which is a problem. I hope you will succeed in correcting these problems. Thank you again for your work!

**Comment by karesake** [comment]
The funny thing is, on the Apple TV i’ve got a livestream in five seconds.

**Comment by technikosoldat** [comment]
How did you configure the video on the eufy app regarding the bell?
![3DEB5CA4-2FE5-46CA-B967-A2FCB2BCC60D](https://user-images.githubusercontent.com/77143914/123471993-dd83b700-d5f6-11eb-8a71-bcc71ba2d813.png)

**Comment by Kneudel** [comment]
In my cases it take 5-10 seconds till the videostream starts. 
What not works is, if I get the push notification for a ring and long press on it, I don't get a video.
