### ISSUE TITLE
no devices after Update to 0.25

### ISSUE THREAD

**Issue by Kneudel** [samemory/homebridge-eufy-security#60]
no devices are displaying anymore after installing update to 0.25. (Eufy Base and Doorbell in my case)
Switch back to 0.24 solves the problem.

**Comment by russbiscardine** [comment]
Thanks for or working on this project, much appreciated.

I have experienced the same issue. In my case it was Base Station and all attached devices. 2 x Motion sensors and 8 x contact sensors. Motion sensors do not update in HomeKit their status, whereas contact sensors do and are immediate.

**Comment by samemory** [comment]
I have rolled back this latest version until we can figure out how to fix some of these issues.
