### ISSUE TITLE
Using StatusFault for alarm instead of SecuritySystemCurrentState.ALARM_TRIGGERED

### ISSUE THREAD

**Issue by schliemann** [samemory/homebridge-eufy-security#68]
@lenoxys 

Shouldn't we use SecuritySystemCurrentState.ALARM_TRIGGERED instead of updating StatusFault?

https://github.com/samemory/homebridge-eufy-security/blob/2184a06d3ea042be86a0342c0f2e009f6b7c3291/src/securitySystemPlatformAccessory.ts#L149-L150

**Comment by lenoxys** [comment]
good point if you look above it is commented. I've updated to remove the commented line #70

**Comment by schliemann** [comment]
Awesome.

**Comment by schliemann** [comment]
This will be fixed when dev is merged into master.
