### ISSUE TITLE
HOOBS plug in 0.2.5 won't install - possible to revert to 0.2.4?

### ISSUE THREAD

**Issue by sxorp** [samemory/homebridge-eufy-security#73]
Would it be possible to revert the HOOBS plugin listed as 0.2.5 to 0.2.4

the current version results in this error:

7/3/2021, 9:18:52 AM npm
7/3/2021, 9:18:52 AM  ERR! code ENOLOCAL
7/3/2021, 9:18:52 AM npm
7/3/2021, 9:18:52 AM ERR! Could not install from "node_modules/homebridge-eufy-security/eufy-security-client" as it does not contain a package.json file.
7/3/2021, 9:18:52 AM 
7/3/2021, 9:18:52 AM npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-07-03T16_18_52_158Z-debug.log

**Comment by samemory** [comment]
I think things should be fixed now. Not sure how you revert in HOOBS but in the Homebridge UI you can click on the wrench icon and select install previous version. Also, the dev version which is now labeled 0.2.7 should be working and contains many fixes. However, need some more testing before I update that to the latest tag.
