### ISSUE TITLE
Eufy Motion Sensor not triggering 

### ISSUE THREAD

**Issue by saltysmith1** [samemory/homebridge-eufy-security#78]
HI 
I have a Motion Sensor currently on firmware version 2.0.1.1, it has added ok to HomeKit but it doesn't trigger when Motion is detected (Eufy App can see it shows motion detected)

Not sure if i have done something wrong hope you can help.

Im currently running HOOBS 4.0.74 with node 14.17.2

Thanks 

Chris

**Comment by schliemann** [comment]
Do you have push notifications enabled for the motion sensor in the current security mode? We only update triggers on push notifications currently.

**Comment by saltysmith1** [comment]
Hey @schliemann i didn’t have push notifications enabled for that particular device, i turned it on (Eufy App) but still not triggering. I tried the same with one of my eufy cameras and the same wasn’t triggering. I also have 2 door contacts and they both work

**Comment by schliemann** [comment]
@saltysmith1 Ok. I don't have a motion sensor myself, except for the one in the cameras. And haven't tested those. There might be an issue with push notifications for motion sensor devices. Maybe @lenoxys or @samemory can confirm this.

**Comment by saltysmith1** [comment]
Thanks @schliemann

**Comment by saltysmith1** [comment]
@russbiscardine glad it’s not just me, thought being a noob I was doing something wrong, 

Do you have any cameras exposed and see there motion?

@lenoxys @samemory any news on this at all please

**Comment by schliemann** [comment]
I'll test motion on my camera tomorrow. Then we can determine if it is a general motion problem or only the motion sensor.

**Comment by lenoxys** [comment]
I'm not at home can't do the test

**Comment by schliemann** [comment]
Camera motion detection doesn't trigger.

**Comment by russbiscardine** [comment]
Hello all. I tried removing a native HomeKit Eufy camera (Indoor Cam). Then enabling it as accessible to my 2nd user which is the one assigned in the Eufy Homebridge config and restarted Homebridge and unfortunately the server would not stay up and kept crashing and rebooting.

**Comment by njuart** [comment]
I can confirm that exposed in Homekit motion sensor doesn't work. It is present but doesn't trigger any motion activity, contact sensor works fine. Also push notification are on and in Eufy app motion sensor works as expected.

**Comment by schliemann** [comment]
Motion on cameras work in the PR I have pendling.

**Comment by njuart** [comment]
> Motion on cameras work in the PR I have pendling.

Cool! And what about standalone motion sensor?

**Comment by schliemann** [comment]
Unfortunately I don't have access to a motion sensor. So can't test it.

**Comment by schliemann** [comment]
@njuart Can you share you log with enabledetailed logging enabled when you trigger motion?

**Comment by njuart** [comment]
> @njuart Can you share your log with enabledetailed logging enabled when you trigger motion?

Yup, will try 👍

**Comment by njuart** [comment]
Weird, but I see nothing in HB logs when I trigger motion.

> [7/25/2021, 10:52:07 AM] [EufySecurity] Handle Station Raw Property Changes:  --  1151 1 1627199527940
[7/25/2021, 10:52:07 AM] [EufySecurity] Received onStationCurrentModePushNotification - currentMode 1 homekitCurrentMode 3
[7/25/2021, 10:52:07 AM] [EufySecurity] Handle Station Property Changes:  --  currentMode { value: 1, timestamp: 1627199527940 }
[7/25/2021, 10:52:07 AM] [EufySecurity] Handle Station Raw Property Changes:  --  1102 14614 1627199527940
[7/25/2021, 10:52:07 AM] [EufySecurity] Handle Station Raw Property Changes:  --  1154 0 1627199527940
[7/25/2021, 10:52:07 AM] [EufySecurity] Handle Station Raw Property Changes:  --  1201 0 1627199527940
[7/25/2021, 10:52:07 AM] [EufySecurity] Handle Station Raw Property Changes:  --  1147 1627199527 1627199527940
[7/25/2021, 10:52:07 AM] [EufySecurity] Handle Station Raw Property Changes:  --  1137 0 1627199527940
[7/25/2021, 10:52:07 AM] [EufySecurity] Handle Station Raw Property Changes:  --  1162 0 1627199527940
[7/25/2021, 10:52:07 AM] [EufySecurity] Handle Station Raw Property Changes:  --  1660 -1 1627199527940
[7/25/2021, 10:52:07 AM] [EufySecurity] Handle Station Raw Property Changes:  --  1664 1 1627199527940
[7/25/2021, 10:52:07 AM] [EufySecurity] Handle Station Raw Property Changes:  --  1165 [] 1627199527940
{"name":"eufyLog","hostname":"raspberrypi","pid":784,"level":30,"msg":"Push notification connection successfully established","time":"2021-07-25T07:52:08.624Z","v":0}
[7/25/2021, 11:01:38 AM] [EufySecurity] Handle Station Raw Property Changes:  --  1147 1627200098 1627200098735
[7/25/2021, 11:02:07 AM] [EufySecurity] Handle Station Raw Property Changes:  --  1147 1627200127 1627200127885
[7/25/2021, 11:11:39 AM] [EufySecurity] Handle Station Raw Property Changes:  --  1147 1627200698 1627200699205
[7/25/2021, 11:21:39 AM] [EufySecurity] Handle Station Raw Property Changes:  --  1147 1627201299 1627201299676 <

But I see logged motion in Eufy app

![IMG_2784](https://user-images.githubusercontent.com/21228802/126892910-0c2c4878-e981-49d0-a3b8-36754f1d34fe.jpg)

**Comment by schliemann** [comment]
Have you enabled detailed logging?

**Comment by njuart** [comment]
> Have you enabled detailed logging?

Yup

![image](https://user-images.githubusercontent.com/21228802/126893141-f8ed17f3-101b-461f-a5e5-a1d9de91886b.png)

**Comment by schliemann** [comment]
So the problem with the detailed logging of the plugin is that the log level is too high. I might make a new pr for enabling verbose or silly logging.

**Comment by lenoxys** [comment]
Should be fixed #93

**Comment by saltysmith1** [comment]
I can confirm its partly fixed, this now works on the Cameras but still nothing for the Indoor Motion Sensor

**Comment by njuart** [comment]
> I can confirm its partly fixed, this now works on the Cameras but still nothing for the Indoor Motion Sensor

But it's not merged to master yet, as I understood

**Comment by saltysmith1** [comment]
@njuart hmmmm I thought 0.2.12 was released to fix this am I wrong?

**Comment by schliemann** [comment]
0.2.12 only fixed motion for cameras. The next version will hopefully fix motion for motion sensors.

**Comment by saltysmith1** [comment]
> 0.2.12 only fixed motion for cameras. The next version will hopefully fix motion for motion sensors.

Cheers for the clarification 👍

**Comment by njuart** [comment]
> 0.2.12 only fixed motion for cameras. The next version will hopefully fix motion for motion sensors.

Guys, thx for amazing work! New version fixes Motion sensor

![image](https://user-images.githubusercontent.com/21228802/127435463-126fa2e3-86ff-4fe4-b5bd-e0b2072bddee.jpeg)

**Comment by russbiscardine** [comment]
Thank you so much. I can confirm that this is indeed working on my two Eufy motion sensors. Both report motion as expected in HomeKit. Good work!

**Comment by saltysmith1** [comment]
👏👏👏 all fixed motion sensor now detecting motion thanks for all your work

**Comment by lenoxys** [comment]
Glad to here now !
