### ISSUE TITLE
The error with the plugin not being referenced

### ISSUE THREAD

**Issue by schliemann** [samemory/homebridge-eufy-security#8]
https://github.com/samemory/homebridge-eufy-security-control/blob/d91e6fdb524a1ddfa6ef3fa0d3e69012bfba8e66/src/index.ts#L10

The error might be that you don't pass the plugin name to registerPlatform?

https://github.com/ptz0n/homebridge-verisure/blob/master/index.js

**Comment by samemory** [comment]
This error went away for me. I have the plugin name referenced the way they had it in the template. If it still shows up maybe we can try a different way or something. 
`
this.api.registerPlatformAccessories(PLUGIN_NAME, PLATFORM_NAME, [            accessory,          ]);
`
