### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by Mat2Ks** [samemory/homebridge-eufy-security#81]
Plugin Error

[14.07.2021, 11:38:10] [homebridge-eufy-security] Restoring existing accessory from cache: Bedroom
[14.07.2021, 11:38:10] [homebridge-eufy-security] Restoring existing accessory from cache: Living Room
[14.07.2021, 11:38:10] [homebridge-eufy-security] Restoring existing accessory from cache: Outdoor Garden
[14.07.2021, 11:38:10] [homebridge-eufy-security] Restoring existing accessory from cache: Hall Entryway
[14.07.2021, 11:38:10] [homebridge-eufy-security] Restoring existing accessory from cache: Outdoor
[14.07.2021, 11:38:11] [homebridge-eufy-security] Restoring existing accessory from cache: Susan Room
[14.07.2021, 11:38:11] [homebridge-eufy-security] Restoring existing accessory from cache: Charlie Room
[14.07.2021, 11:38:11] [homebridge-eufy-security] Restoring existing accessory from cache: Bedroom
[14.07.2021, 11:38:11] [homebridge-eufy-security] Restoring existing accessory from cache: Living Room
[14.07.2021, 11:38:11] [homebridge-eufy-security] Restoring existing accessory from cache: Outdoor Garden
[14.07.2021, 11:38:11] [homebridge-eufy-security] Restoring existing accessory from cache: Hall Entryway
[14.07.2021, 11:38:11] [homebridge-eufy-security] Restoring existing accessory from cache: Outdoor
[14.07.2021, 11:38:11] [homebridge-eufy-security] Restoring existing accessory from cache: Susan Room
[14.07.2021, 11:38:11] [homebridge-eufy-security] Restoring existing accessory from cache: Charlie Room
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":50,"msg":"P2PClientProtocol.lookup(): station: T8400P202024203E - All address lookup tentatives failed.","time":"2021-07-14T09:38:11.322Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":30,"msg":"Disconnected from station T8400P202024203E","time":"2021-07-14T09:38:17.492Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":50,"msg":"P2PClientProtocol.lookup(): station: T8400P2020280B5C - All address lookup tentatives failed.","time":"2021-07-14T09:38:17.495Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":30,"msg":"Disconnected from station T8400P2020280B5C","time":"2021-07-14T09:38:18.284Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":30,"msg":"Connected to station T8400P2020280834 on host 192.168.1.33 and port 18684","time":"2021-07-14T09:38:18.558Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":30,"msg":"Connected to station T8400P2020280DDC on host 192.168.1.31 and port 12615","time":"2021-07-14T09:38:18.589Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":30,"msg":"Connected to station T8400P20202909DF on host 192.168.1.30 and port 10945","time":"2021-07-14T09:38:18.625Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":50,"msg":"Error: Error: socket hang up\n    at connResetException (internal/errors.js:607:14)\n    at TLSSocket.socketOnEnd (_http_client.js:493:23)\n    at TLSSocket.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21) {\n  code: 'ECONNRESET',\n  config: {\n    url: 'https://android.clients.google.com/checkin',\n    method: 'post',\n    data: <Buffer 0a 0f 31 30 39 32 36 39 39 39 33 38 31 33 37 30 39 10 00 22 65 0a 61 0a 37 67 6f 6f 67 6c 65 2f 72 61 7a 6f 72 2f 66 6c 6f 3a 35 2e 30 2e 31 2f 4c 52 ... 174 more bytes>,\n    headers: {\n      Accept: 'application/json, text/plain, */*',\n      'X-Auth-Token': '30352ae92e5dab8e8ed0426a546e4582e248396d5f81eea0',\n      'Content-Type': 'application/x-protobuf',\n      'User-Agent': 'axios/0.21.1',\n      'Content-Length': 224\n    },\n    transformRequest: [ [Function: transformRequest] ],\n    transformResponse: [ [Function: transformResponse] ],\n    timeout: 0,\n    adapter: [Function: httpAdapter],\n    responseType: 'arraybuffer',\n    xsrfCookieName: 'XSRF-TOKEN',\n    xsrfHeaderName: 'X-XSRF-TOKEN',\n    maxContentLength: -1,\n    maxBodyLength: -1,\n    validateStatus: [Function: validateStatus]\n  },\n  request: <ref *1> Writable {\n    _writableState: WritableState {\n      objectMode: false,\n      highWaterMark: 16384,\n      finalCalled: false,\n      needDrain: false,\n      ending: false,\n      ended: false,\n      finished: false,\n      destroyed: false,\n      decodeStrings: true,\n      defaultEncoding: 'utf8',\n      length: 0,\n      writing: false,\n      corked: 0,\n      sync: true,\n      bufferProcessing: false,\n      onwrite: [Function: bound onwrite],\n      writecb: null,\n      writelen: 0,\n      afterWriteTickInfo: null,\n      buffered: [],\n      bufferedIndex: 0,\n      allBuffers: true,\n      allNoop: true,\n      pendingcb: 0,\n      prefinished: false,\n      errorEmitted: false,\n      emitClose: true,\n      autoDestroy: true,\n      errored: null,\n      closed: false\n    },\n    _events: [Object: null prototype] {\n      response: [Function: handleResponse],\n      error: [Function: handleRequestError]\n    },\n    _eventsCount: 2,\n    _maxListeners: undefined,\n    _options: {\n      maxRedirects: 21,\n      maxBodyLength: 10485760,\n      protocol: 'https:',\n      path: '/checkin',\n      method: 'POST',\n      headers: [Object],\n      agent: undefined,\n      agents: [Object],\n      auth: undefined,\n      hostname: 'android.clients.google.com',\n      port: null,\n      nativeProtocols: [Object],\n      pathname: '/checkin'\n    },\n    _ended: true,\n    _ending: true,\n    _redirectCount: 0,\n    _redirects: [],\n    _requestBodyLength: 224,\n    _requestBodyBuffers: [ [Object] ],\n    _onNativeResponse: [Function (anonymous)],\n    _currentRequest: ClientRequest {\n      _events: [Object: null prototype],\n      _eventsCount: 7,\n      _maxListeners: undefined,\n      outputData: [],\n      outputSize: 0,\n      writable: true,\n      destroyed: false,\n      _last: true,\n      chunkedEncoding: false,\n      shouldKeepAlive: false,\n      _defaultKeepAlive: true,\n      useChunkedEncodingByDefault: true,\n      sendDate: false,\n      _removedConnection: false,\n      _removedContLen: false,\n      _removedTE: false,\n      _contentLength: null,\n      _hasBody: true,\n      _trailer: '',\n      finished: true,\n      _headerSent: true,\n      socket: [TLSSocket],\n      _header: 'POST /checkin HTTP/1.1\\r\\n' +\n        'Accept: application/json, text/plain, */*\\r\\n' +\n        'X-Auth-Token: 30352ae92e5dab8e8ed0426a546e4582e248396d5f81eea0\\r\\n' +\n        'Content-Type: application/x-protobuf\\r\\n' +\n        'User-Agent: axios/0.21.1\\r\\n' +\n        'Content-Length: 224\\r\\n' +\n        'Host: android.clients.google.com\\r\\n' +\n        'Connection: close\\r\\n' +\n        '\\r\\n',\n      _keepAliveTimeout: 0,\n      _onPendingData: [Function: noopPendingOutput],\n      agent: [Agent],\n      socketPath: undefined,\n      method: 'POST',\n      maxHeaderSize: undefined,\n      insecureHTTPParser: undefined,\n      path: '/checkin',\n      _ended: false,\n      res: null,\n      aborted: false,\n      timeoutCb: null,\n      upgradeOrConnect: false,\n      parser: null,\n      maxHeadersCount: null,\n      reusedSocket: false,\n      host: 'android.clients.google.com',\n      protocol: 'https:',\n      _redirectable: [Circular *1],\n      [Symbol(kCapture)]: false,\n      [Symbol(kNeedDrain)]: false,\n      [Symbol(corked)]: 0,\n      [Symbol(kOutHeaders)]: [Object: null prototype]\n    },\n    _currentUrl: 'https://android.clients.google.com/checkin',\n    [Symbol(kCapture)]: false\n  },\n  response: undefined,\n  isAxiosError: true,\n  toJSON: [Function: toJSON]\n}","time":"2021-07-14T09:38:18.774Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":50,"msg":"Status return code not 200 { status: undefined, statusText: undefined, data: undefined }","time":"2021-07-14T09:38:18.776Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":50,"msg":"Generic Error: Error: Google checkin failed with error: undefined\n    at PushNotificationService.executeCheckin (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:205:23)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at PushNotificationService.loginPushCredentials (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:168:33)\n    at PushNotificationService._open (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:497:32)\n    at PushNotificationService.open (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:544:9)","time":"2021-07-14T09:38:19.206Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":50,"msg":"Push credentials login Error: Error: Google checkin failed with error: Error: Google checkin failed with error: undefined\n    at PushNotificationService.executeCheckin (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:209:19)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at PushNotificationService.loginPushCredentials (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:168:33)\n    at PushNotificationService._open (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:497:32)\n    at PushNotificationService.open (/usr/lib/node_modules/homebridge-eufy-security/node_modules/eufy-security-client/src/push/service.ts:544:9)","time":"2021-07-14T09:38:19.212Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":50,"msg":"Push notifications are disabled, because the registration failed!","time":"2021-07-14T09:38:19.214Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":30,"msg":"Retry to register/login for push notification in 5 seconds...","time":"2021-07-14T09:38:19.216Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":30,"msg":"Retry to register/login for push notification","time":"2021-07-14T09:39:00.552Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":50,"msg":"P2PClientProtocol.lookup(): station: T8400P2020242A5F - All address lookup tentatives failed.","time":"2021-07-14T09:39:00.571Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":30,"msg":"Disconnected from station T8400P2020242A5F","time":"2021-07-14T09:39:04.284Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":50,"msg":"P2PClientProtocol.lookup(): station: T8400P20202909DF - All address lookup tentatives failed.","time":"2021-07-14T09:39:39.625Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":30,"msg":"Disconnected from station T8400P20202909DF","time":"2021-07-14T09:39:40.879Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":50,"msg":"P2PClientProtocol.lookup(): station: T8400P2020280834 - All address lookup tentatives failed.","time":"2021-07-14T09:39:40.880Z","v":0}
{"name":"eufyLog","hostname":"hkbridge","pid":2501,"level":30,"msg":"Disconnected from station T8400P2020280834","time":"2021-07-14T09:39:43.250Z","v":0}

**Comment by schliemann** [comment]
This very much looks like an issue with the client library. Have you ever been able to get the plugin running?

**Comment by Mat2Ks** [comment]
Yes. It was running about 2-3 hours, but atm Im not able to run it.

**Comment by schliemann** [comment]
Have you tried cutting power from the base station.

**Comment by Mat2Ks** [comment]
I haven't got  eufy base station - only 7x 2K Indoor Cam.

**Comment by schliemann** [comment]
@Mat2Ks Any luck since?

**Comment by Mat2Ks** [comment]
After UPDATE. Motion sensors from Indoor 2K added to HomeKit - but still doesn’t work. Eufy detecting motion, Home not

**Comment by schliemann** [comment]
@Mat2Ks The motion sensors not working is another issue which impacts all cameras. We will investigate this.

**Comment by schliemann** [comment]
For now I guess this issue can be closed?

**Comment by Mat2Ks** [comment]
(node:2254) UnhandledPromiseRejectionWarning: TypeError: this.eufyDevice.isMotionDetected is not a function
    at CameraAccessory.isMotionDetected (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:170:46)
    at CameraAccessory.handleMotionDetectedGet (/usr/lib/node_modules/homebridge-eufy-security/src/accessories/CameraAccessory.ts:180:37)
    at MotionDetected.emit (events.js:327:22)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at MotionDetected.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
(node:2254) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1513)

**Comment by schliemann** [comment]
What is the model in homekit for your cameras?

![Uploading E6774DAA-2F90-410C-AA28-86F3A8DF2683.jpeg…]()

**Comment by Mat2Ks** [comment]
![F792C2B8-CB60-47EA-8CB1-DD2BE74525DB](https://user-images.githubusercontent.com/80457994/126786335-3ba7a7e4-76e4-4d1f-bc72-51421eec0fc2.jpeg)

**Comment by lenoxys** [comment]
can you test on  0.2.13 ?
