### ISSUE TITLE
No devices found - Does not seem to login to Eufy

### ISSUE THREAD

**Issue by jacoblukewood** [samemory/homebridge-eufy-security#85]
**Describe The Bug:**
Plugin does not find any devices. Using an incorrect login also does not trigger any errors.

**To Reproduce:**
Fresh install

**Expected behavior:**
Devices should appear or errors should be logged

**Logs:**

```
[7/17/2021, 9:42:10 PM] [EufySecurity] Initializing EufySecurity platform...
[7/17/2021, 9:42:10 PM] [EufySecurity] Finished initializing platform: undefined
[7/17/2021, 9:42:10 PM] [EufySecurity] enableDetailedLogging: undefined
[7/17/2021, 9:42:10 PM] [EufySecurity] discoveringDevices
[7/17/2021, 9:42:10 PM] [EufySecurity] EMAIL
[7/17/2021, 9:42:10 PM] [EufySecurity] PASSWORD
Preparing Advertiser for 'Homebridge 3558 DDB9' using bonjour-hap backend!
Setup Payload:
X-HM://XXXXXXXX
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ XXXXXXXXX │     
    └────────────┘     
                       
Starting to advertise 'Homebridge XXXXXXXXX' using bonjour-hap backend!
[7/17/2021, 9:42:10 PM] Homebridge v1.3.4 (Homebridge XXXXX) is running on port 51888.
[7/17/2021, 9:42:11 PM] [EufySecurity] EufyClient connected false
[7/17/2021, 9:42:11 PM] [EufySecurity] PollingInterval: 10
[7/17/2021, 9:42:11 PM] [EufySecurity] Refresh data from cloud and schedule next refresh.
[7/17/2021, 9:42:14 PM] [EufySecurity] Found 0 devices.
[7/17/2021, 9:42:14 PM] [EufySecurity] Found 0 hubs.
```

**Plugin Config:**

```json
{
            "username": "EMAIL",
            "password": "PASSWORD",
            "hkHome": 1,
            "hkAway": 0,
            "hkNight": 3,
            "hkOff": 63,
            "hkDisarmed": 6,
            "platform": "EufySecurity"
        }
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 1.3.4
* **Node.js Version**: v14.17.0
* **NPM Version**: 7.18.1
* **Operating System**: macOS 11.2.3

**Comment by schliemann** [comment]
EufyClient connected false means that the client failed to connect. Are you sure the user has access and the password is correct? Can you enable detailed logging?

**Comment by jacoblukewood** [comment]
> EufyClient connected false means that the client failed to connect. Are you sure the user has access and the password is correct? Can you enable detailed logging?

Could you please clarify what you mean by the user has access? The login details I'm using are the same used to set up the camera and function on the Eufy app. Is there something to enable on the account to allow access?

Detailed logging shows the following additional logs.
`{"name":"eufyLog","hostname":"Jacobs-MacBook-Air.local","pid":30289,"level":50,"msg":"Response code not ok { code: 100028, msg: 'Failed to request.' }","time":"2021-07-17T23:45:30.637Z","v":0}
{"name":"eufyLog","hostname":"Jacobs-MacBook-Air.local","pid":30289,"level":50,"msg":"Token error { method: 'post', endpoint: 'app/get_hub_list' }","time":"2021-07-17T23:45:30.637Z","v":0}
{"name":"eufyLog","hostname":"Jacobs-MacBook-Air.local","pid":30289,"level":50,"msg":"Status return code 401, invalidate token { status: 401, statusText: 'Unauthorized' }","time":"2021-07-17T23:45:31.593Z","v":0}
{"name":"eufyLog","hostname":"Jacobs-MacBook-Air.local","pid":30289,"level":50,"msg":"Status return code not 200 { status: 401, statusText: 'Unauthorized' }","time":"2021-07-17T23:45:31.593Z","v":0}
{"name":"eufyLog","hostname":"Jacobs-MacBook-Air.local","pid":30289,"level":50,"msg":"Response code not ok { code: 100028, msg: 'Failed to request.' }","time":"2021-07-17T23:45:32.295Z","v":0}
{"name":"eufyLog","hostname":"Jacobs-MacBook-Air.local","pid":30289,"level":50,"msg":"Token error { method: 'post', endpoint: 'app/get_devs_list' }","time":"2021-07-17T23:45:32.295Z","v":0}
{"name":"eufyLog","hostname":"Jacobs-MacBook-Air.local","pid":30289,"level":50,"msg":"Status return code 401, invalidate token { status: 401, statusText: 'Unauthorized' }","time":"2021-07-17T23:45:33.243Z","v":0}
{"name":"eufyLog","hostname":"Jacobs-MacBook-Air.local","pid":30289,"level":50,"msg":"Status return code not 200 { status: 401, statusText: 'Unauthorized' }","time":"2021-07-17T23:45:33.244Z","v":0}`

**Comment by jacoblukewood** [comment]
Creating a new Eufy account and inviting it as a guest solved the issue.
