### ISSUE TITLE
StationGuardModeProperty doesn't support Off in 0.9.2

### ISSUE THREAD

**Issue by schliemann** [samemory/homebridge-eufy-security#88]
The new release of the eufy-security-client no longer supports Off for stations:

https://github.com/bropat/eufy-security-client/issues/27

Maybe it is possible to set it via UpdateDeviceProperty on a keypad device. But it will be cumbersome.

**Comment by njuart** [comment]
Yes, also noticed this, when it is mapped to Off mode, HB crashes.

**Comment by schliemann** [comment]
I'll maybe take a look at it tonight.

**Comment by lenoxys** [comment]
I just tested on the last version 2.1.13 looks good for me I don't see any crash of HB when switching from an arming mode to another.

Can you enable detailed logging on plugin configuration and debug mode on HB config ?

**Comment by schliemann** [comment]
It only throw errors if you have mapped hkOff to 6.

**Comment by lenoxys** [comment]
try the new beta version

**Comment by schliemann** [comment]
Works in the new beta.
