### ISSUE TITLE
Hoobs issue

### ISSUE THREAD

**Issue by mrota83** [samemory/homebridge-eufy-security#89]
when i try to install the plugin with hoobs i get a error fail to install

NPM
ERR! code etarget
npm
ERR! notarget  no matching version found for homebridge-eufy-security 0.2.11. in most cases you or one of your dependencies are requesting npm err!

**Comment by schliemann** [comment]
Odd. Maybe @samemory or @lenoxys knows what's wrong.

**Comment by lenoxys** [comment]
We don't support Hoobs sorry. Don't have time to look on it.

**Comment by schliemann** [comment]
Can you try 0.2.12?

**Comment by mrota83** [comment]
> Can you try 0.2.12?

Don’t work

**Comment by lenoxys** [comment]
I've open a case on HOOBS website. Looks like the latest beta version is not available

**Comment by mcarroll779** [comment]
Is there any support for HOOBS now? I’ve installed it and I’m getting this in the log when I start running the plug-in

Eufy SecurityWARNINGunhandled rejection: TypeError: Cannot read property 'indexOf' of undefined

Thanks 😊
