### ISSUE TITLE
A bit of a spam in logs after update to 0.2.13

### ISSUE THREAD

**Issue by njuart** [samemory/homebridge-eufy-security#96]
Hi, after latest update (0.2.13) I see quite a bit of a spam in logs almost every minute, is it ok? Detailed logging is off, just in case. Thx

![image](https://user-images.githubusercontent.com/21228802/127488487-35ae221c-7d0c-43ad-be32-db770cef6a70.png)

**Comment by lenoxys** [comment]
hey, you can disable the enabledetaillogging settings.

**Comment by njuart** [comment]
> hey, you can disable the enabledetaillogging settings.

But I've mentioned that it's disabled =)

**Comment by lenoxys** [comment]
Hum weird, did you restart hb ?

**Comment by njuart** [comment]
> Hum weird, did you restart hb ?

Yup, even restarted container.

**Comment by lenoxys** [comment]
@schliemann @samemory do you have the same issue ? I do not have

**Comment by schliemann** [comment]
Were you looking at the hallway room in the Home app when all the logging occurred?

**Comment by njuart** [comment]
> @njuart  Were you looking at the hallway room in the Home app when all the logging occurred?

Nope, record in logs appears every time when sensor is triggered.

**Comment by lenoxys** [comment]
I've pushed another update to remove extra logs when log détail aren't enabled

**Comment by njuart** [comment]
> I've pushed another update to remove extra logs when log détail aren't enabled

Cool, I believe it's not yet merged to master right?

**Comment by schliemann** [comment]
@njuart There are no active pull requests. So I think everything is merged.

**Comment by lenoxys** [comment]
I put my code on DEV branch, to install dev it's all in the homebridge ui :

On plugin menu, click the setting icon :
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/3996456/127869958-27a25eee-f786-440c-9dce-93adae2f94d7.png">

Then click on "install previous version", you will be able to select the 0.3.4 dev version.

<img width="554" alt="image" src="https://user-images.githubusercontent.com/3996456/127870018-ff3ca176-5a15-4017-83ca-8ea4507a02d1.png">


To come back to the stable branch, select the latest flagged version.

**Comment by njuart** [comment]
@lenoxys Thx a lot, that's what I thought, but didn't know which version to choose

**Comment by njuart** [comment]
Just checked, it's not spamming anymore 👍

**Comment by lenoxys** [comment]
thanks for your feedback !
